export const aavegotchiDiamondAddressMatic =
  "0x86935F11C86623deC8a25696E1C19a8659CbF95d";
export const fudAddress = "0x403e967b044d4be25170310157cb1a4bf10bdd0f";
export const fomoAddress = "0x44a6e0be76e1d9620a7f76588e4509fe4fa8e8c8";
export const alphaAddress = "0x6a3e7c3c6ef65ee26975b12293ca1aad7e1daed2";
export const kekAddress = "0x42e5e06ef5b90fe15f853f59299fc96259209c5c";
export const ghstAddress = "0x385eeac5cb85a38a9a07a70c73e0a3271cfb54a7";
export const aavegotchiDAOAddress =
  "0xb208f8BB431f580CC4b216826AFfB128cd1431aB";
export const pixelcraftAddress = "0xD4151c984e6CF33E04FFAAF06c3374B2926Ecc64";
export const playerRewardsAddress =
  "0x27df5c6dcd360f372e23d5e63645ec0072d0c098";
export const snapshotGraphUrl = "https://hub.snapshot.org/graphql";

export const WEARABLE_GAP_OFFSET = 1000000000;

// Forge asset token IDs
export const ALLOY = WEARABLE_GAP_OFFSET;
export const ESSENCE = WEARABLE_GAP_OFFSET + 1;
export const GEODE_COMMON = WEARABLE_GAP_OFFSET + 2;
export const GEODE_UNCOMMON = WEARABLE_GAP_OFFSET + 3;
export const GEODE_RARE = WEARABLE_GAP_OFFSET + 4;
export const GEODE_LEGENDARY = WEARABLE_GAP_OFFSET + 5;
export const GEODE_MYTHICAL = WEARABLE_GAP_OFFSET + 6;
export const GEODE_GODLIKE = WEARABLE_GAP_OFFSET + 7;

export const CORE_BODY_COMMON = WEARABLE_GAP_OFFSET + 8;
export const CORE_BODY_UNCOMMON = WEARABLE_GAP_OFFSET + 9;
export const CORE_BODY_RARE = WEARABLE_GAP_OFFSET + 10;
export const CORE_BODY_LEGENDARY = WEARABLE_GAP_OFFSET + 11;
export const CORE_BODY_MYTHICAL = WEARABLE_GAP_OFFSET + 12;
export const CORE_BODY_GODLIKE = WEARABLE_GAP_OFFSET + 13;

export const CORE_FACE_COMMON = WEARABLE_GAP_OFFSET + 14;
export const CORE_FACE_UNCOMMON = WEARABLE_GAP_OFFSET + 15;
export const CORE_FACE_RARE = WEARABLE_GAP_OFFSET + 16;
export const CORE_FACE_LEGENDARY = WEARABLE_GAP_OFFSET + 17;
export const CORE_FACE_MYTHICAL = WEARABLE_GAP_OFFSET + 18;
export const CORE_FACE_GODLIKE = WEARABLE_GAP_OFFSET + 19;

export const CORE_EYES_COMMON = WEARABLE_GAP_OFFSET + 20;
export const CORE_EYES_UNCOMMON = WEARABLE_GAP_OFFSET + 21;
export const CORE_EYES_RARE = WEARABLE_GAP_OFFSET + 22;
export const CORE_EYES_LEGENDARY = WEARABLE_GAP_OFFSET + 23;
export const CORE_EYES_MYTHICAL = WEARABLE_GAP_OFFSET + 24;
export const CORE_EYES_GODLIKE = WEARABLE_GAP_OFFSET + 25;

export const CORE_HEAD_COMMON = WEARABLE_GAP_OFFSET + 26;
export const CORE_HEAD_UNCOMMON = WEARABLE_GAP_OFFSET + 27;
export const CORE_HEAD_RARE = WEARABLE_GAP_OFFSET + 28;
export const CORE_HEAD_LEGENDARY = WEARABLE_GAP_OFFSET + 29;
export const CORE_HEAD_MYTHICAL = WEARABLE_GAP_OFFSET + 30;
export const CORE_HEAD_GODLIKE = WEARABLE_GAP_OFFSET + 31;

export const CORE_HANDS_COMMON = WEARABLE_GAP_OFFSET + 32;
export const CORE_HANDS_UNCOMMON = WEARABLE_GAP_OFFSET + 33;
export const CORE_HANDS_RARE = WEARABLE_GAP_OFFSET + 34;
export const CORE_HANDS_LEGENDARY = WEARABLE_GAP_OFFSET + 35;
export const CORE_HANDS_MYTHICAL = WEARABLE_GAP_OFFSET + 36;
export const CORE_HANDS_GODLIKE = WEARABLE_GAP_OFFSET + 37;

export const CORE_PET_COMMON = WEARABLE_GAP_OFFSET + 38;
export const CORE_PET_UNCOMMON = WEARABLE_GAP_OFFSET + 39;
export const CORE_PET_RARE = WEARABLE_GAP_OFFSET + 40;
export const CORE_PET_LEGENDARY = WEARABLE_GAP_OFFSET + 41;
export const CORE_PET_MYTHICAL = WEARABLE_GAP_OFFSET + 42;
export const CORE_PET_GODLIKE = WEARABLE_GAP_OFFSET + 43;
