import { ethers } from "ethers";
import { Exceptions } from "../scripts/itemTypeHelpers";

export const front = ethers.utils.formatBytes32String("wearables-front");
export const back = ethers.utils.formatBytes32String("wearables-back");
export const left = ethers.utils.formatBytes32String("wearables-left");
export const right = ethers.utils.formatBytes32String("wearables-right");

export const allExceptions: Exceptions[] = [
  //body
  {
    itemId: 40,
    slotPosition: 0,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 132,
    slotPosition: 0,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 132,
    slotPosition: 0,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 132,
    slotPosition: 0,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 307,
    slotPosition: 0,
    side: "wearables-back",
    exceptionBool: true,
  },

  //face
  {
    itemId: 18,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 18,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 18,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 18,
    slotPosition: 1,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 55,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 55,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 55,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 140,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 140,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 216,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 216,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 216,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 240,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 240,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 240,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },

  //eyes
  {
    itemId: 301,
    slotPosition: 2,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 301,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 301,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },

  {
    itemId: 66,
    slotPosition: 2,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 66,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 66,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 66,
    slotPosition: 2,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 199,
    slotPosition: 2,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 199,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 199,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 199,
    slotPosition: 2,
    side: "wearables-front",
    exceptionBool: true,
  },

  //head

  {
    itemId: 27,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 27,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 27,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 27,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 30,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 30,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 30,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 30,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 33,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 33,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 33,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 33,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  {
    itemId: 72,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 72,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 72,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 72,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  {
    itemId: 144,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 144,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 144,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 144,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 145,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 145,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 145,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 145,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 161,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 161,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 161,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 161,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  {
    itemId: 242,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 242,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 242,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  {
    itemId: 292,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 292,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 292,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 292,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 302,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 302,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 302,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 302,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 308,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 308,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 308,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 308,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  //right hand
  {
    itemId: 23,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 23,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 4,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 4,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 4,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 312,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 312,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },

  //left hand
  {
    itemId: 23,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 23,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 5,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 5,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 5,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 312,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 312,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },

  //pet
  {
    itemId: 151,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 152,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 153,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 154,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 155,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 156,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 233,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 236,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 237,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 238,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 261,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 305,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 4,
    exceptionBool: true,
    side: "wearables-right",
  },
  {
    itemId: 217,
    slotPosition: 4,
    exceptionBool: true,
    side: "wearables-right",
  },
  {
    itemId: 223,
    slotPosition: 4,
    exceptionBool: true,
    side: "wearables-right",
  },
  {
    itemId: 201,
    slotPosition: 5,
    exceptionBool: true,
    side: "wearables-left",
  },
  {
    itemId: 217,
    slotPosition: 5,
    exceptionBool: true,
    side: "wearables-left",
  },
  {
    itemId: 223,
    slotPosition: 5,
    exceptionBool: true,
    side: "wearables-left",
  },
  {
    itemId: 261,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 151,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 152,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },

  {
    itemId: 153,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 154,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 155,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 156,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 353,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 361,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 374,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 371,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 371,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },

  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 381,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 381,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 381,
    slotPosition: 2,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 406,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 410,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 413,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 415,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 417,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
];
