import { bodyWearableBack } from "../scripts/svgHelperFunctions";

const fs = require("fs");

export const wearablesRightSvgs = [
  wearable("0_VoidRight"),
  wearable("1_CamoHatRight"),
  wearable("2_CamoPantsRight"), // body but doesn't have sleeves
  wearable("3_MK2GrenadeRight"),
  wearable("4_SnowCamoHatRight"),
  wearable("5_SnowCamoPantsRight"), // body but no sleeves
  wearable("6_M67GrenadeRight"),
  wearable("7_MarineCapRight"),
  bodyWearableRight("8_MarineJacket"), // bodyWearableRight("8_MarineJacket"),
  wearable("9_WalkieTalkieRight"),
  wearable("10_LinkWhiteHatRight"),
  bodyWearableRight("11_MessDress"), // bodyWearableRight("11_MessDress"),
  wearable("12_LinkBubblyRight"),
  wearable("13_SergeyBeardRight"),
  wearable("14_SergeyEyesRight"),
  bodyWearableRight("15_RedPlaid"), // bodyWearableRight("15_RedPlaid"),
  bodyWearableRight("16_BluePlaid"), //  bodyWearableRight("16_BluePlaid"),
  wearable("17_LinkCubeRight"),
  wearable("18_AaveHeroMaskRight"),
  bodyWearableRight("19_AaveHeroShirt"), // bodyWearableRight("19_AaveHeroShirt"),
  wearable("20_AavePlushRight"),
  wearable("21_CaptainAaveMaskRight"),
  bodyWearableRight("22_CaptainAaveSuit"), // bodyWearableRight("22_CaptainAaveSuit"),
  wearable("23_CaptainAaveShieldRight"),
  wearable("24_ThaaveHelmetRight"),
  bodyWearableRight("25_ThaaveSuit"), // bodyWearableRight("25_ThaaveSuit"),
  wearable("26_ThaaveHammerRight"),
  wearable("27_MarcHairRight"),
  bodyWearableRight("28_MarcOutfit"), // bodyWearableRight("28_MarcOutfit"),
  wearable("29_REKTSignRight"),
  wearable("30_JordanHairRight"),
  bodyWearableRight("31_JordanSuit"), // bodyWearableRight("31_JordanSuit"),
  wearable("32_AaveFlagRight"),
  wearable("33_StaniHairRight"),
  wearable("34_StaniVestRight"), // bodyWearableRight("34_StaniVest"),
  wearable("35_AaveBoatRight"),
  wearable("36_ETHMaxiGlassesRight"),
  bodyWearableRight("37_ETHTShirt"),
  wearable("38_32ETHCoinRight"),
  wearable("39_FoxyMaskRight"),
  wearable("40_FoxyTailRight"), // body but no sleeves
  wearable("41_TrezorWalletRight"),
  wearable("42_NogaraEagleMaskRight"),
  bodyWearableRight("43_NogaraEagleArmor"),
  wearable("44_DAOEggRight"),
  wearable("45_ApeMaskRight"),
  bodyWearableRight("46_HalfRektShirt"),
  wearable("47_WaifuPillowRight"),
  wearable("48_XibotMohawkRight"),
  wearable("49_CoderdanShadesRight"),
  bodyWearableRight("50_GldnXrossRobe"),
  wearable("51_MudgenDiamondRight"),
  wearable("52_GalaxyBrainRight"),
  wearable("53_AllSeeingEyesRight"),
  bodyWearableRight("54_LlamacornShirt"),
  "55_AagentHeadsetRight",
  bodyWearableRight("56_AagentShirt"),
  wearable("57_AagentShadesRight"),
  wearable("58_AagentPistolRight"),
  wearable("59_AagentFedoraHatRight"),
  wearable("60_WizardHatRight"),
  wearable("61_WizardHatLegendaryRight"),
  wearable("62_WizardHatMythicalRight"),
  wearable("63_WizardHatGodlikeRight"),
  wearable("64_WizardStaffRight"),
  wearable("65_WizardStaffLegendaryRight"),
  wearable("66_FutureWizardVisorRight"),
  wearable("67_FarmerStrawHatRight"),
  wearable("68_FarmerJeansRight"), // Body but no sleeves
  wearable("69_FarmerPitchforkRight"),
  wearable("70_FarmerHandsawRight"),
  wearable("71_SantagotchiHatRight"),
  wearable("72_JaayHairpieceRight"),
  wearable("73_JaayGlassesRight"),
  bodyWearableRight("74_JaayHaoSuit"),
  "75_OKexSignRight",
  wearable("76_BigGHSTTokenRight"),
  wearable("77_BitcoinBeanieRight"),
  wearable("78_SkaterJeansRight"), // Body but no sleeves
  wearable("79_SkateboardRight"),
  wearable("80_SushiHeadbandRight"),
  wearable("81_SushiRobeRight"), // Body but not sleeves
  wearable("82_SushiRollRight"),
  wearable("83_SushiKnifeRight"),
  wearable("84_GentlemanHatRight"),
  bodyWearableRight("85_GentlemanSuit"),
  "86_GentlemanMonocleRight",
  wearable("87_MinerHelmetRight"),
  wearable("88_MinerJeansRight"), // Body but no sleeves
  wearable("89_MinerPickaxeRight"),
  wearable("90_PajamaHatRight"),
  bodyWearableRight("91_PajamaPants"),
  wearable("92_BedtimeMilkRight"),
  wearable("93_FluffyBlanketRight"),
  wearable("94_RunnerSweatbandRight"),
  wearable("95_RunnerShortsRight"), // Body but no sleeves
  wearable("96_WaterBottleRight"),
  wearable("97_PillboxHatRight"),
  wearable("98_LadySkirtRight"), // Body but no sleeves
  wearable("99_LadyParasolRight"),
  wearable("100_LadyClutchRight"),
  wearable("101_WitchHatRight"),
  bodyWearableRight("102_WitchCape"),
  wearable("103_WitchWandRight"),
  wearable("104_PortalMageHelmetRight"),
  bodyWearableRight("105_PortalMageArmor"),
  wearable("106_PortalMageAxeRight"),
  wearable("107_PortalMageBlackAxeRight"),
  wearable("108_RastaDredsRight"),
  bodyWearableRight("109_RastaShirt"),
  wearable("110_JamaicanFlagRight"),
  wearable("111_HazmatHoodRight"),
  bodyWearableRight("112_HazmatSuit"),
  wearable("113_UraniumRodRight"),
  bodyWearableRight("114_RedHawaiianShirt"),
  bodyWearableRight("115_BlueHawaiianShirt"),
  wearable("116_CoconutRight"),
  wearable("117_DealWithItShadesRight"),
  wearable("118_WaterJugRight"),
  wearable("119_BabyBottleRight"),
  wearable("120_MartiniRight"),
  wearable("121_WineBottleRight"),
  wearable("122_MilkshakeRight"),
  wearable("123_AppleJuiceRight"),
  wearable("124_BeerHelmetRight"),
  bodyWearableRight("125_TrackSuit"),
  wearable("126_KinshipPotion"),
  wearable("127_GreaterKinshipPotion"),
  wearable("128_XPPotion"),
  wearable("129_GreaterXPPotion"),
  wearable("130_FireballRight"),
  wearable("131_DragonHornsRight"),
  wearable("132_DragonWingsRight"),
  wearable("133_PointyHornsRight"), // Body wearable but not sleeves
  wearable("134_L2SignRight"),
  bodyWearableRight("135_PolygonShirt"),
  wearable("136_PolygonCapRight"),
  wearable("137_VoteSignRight"),
  bodyWearableRight("138_SnapshotShirt"),
  wearable("139_SnapshotHatRight"),
  wearable("140_ElfEarsRight"),
  wearable("141_GemstoneRingRight"),
  wearable("142_PrincessTiaraRight"),
  wearable("143_GoldNecklaceRight"),
  wearable("144_PrincessHairRight"),
  wearable("145_GodliLocksRight"),
  wearable("146_ImperialMoustacheRight"),
  wearable("147_TinyCrownRight"),
  wearable("148_RoyalScepterRight"),
  wearable("149_RoyalCrownRight"),
  bodyWearableRight("150_RoyalRobes"),
  wearable("151_CommonRoflRight"),
  wearable("152_UncommonRoflRight"),
  wearable("153_RareRoflRight"),
  wearable("154_LegendaryRoflRight"),
  wearable("155_MythicalRoflRight"),
  wearable("156_GodlikeRoflRight"),
  "157_LilPumpGoateeLeft",
  wearable("158_LilPumpDrinkRight"),
  wearable("159_LilPumpShadesRight"),
  bodyWearableRight("160_LilPumpThreads"),
  wearable("161_LilPumpDreadsRight"),
  bodyWearableRight("162_MiamiShirt"),
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  wearable("199_SteampunkGlassesRight"),
  wearable("200_SteampunkRight"),
  wearable("201_SteampunkGloveRight"),
  wearable("202_CyberpunkVRRight"),
  bodyWearableRight("203_GamerJacket"),
  wearable("204_CyberpunkControlRight"),
  wearable("205_GotchiMugRight"),
  wearable("206_BikerHelmetRight"),
  wearable("207_BikerJacketRight"),
  wearable("208_AviatorsRight"),
  wearable("209_HorsehoeMustacheRight"),
  wearable("210_H1backgroundRight"),
  wearable("211_GuyFauwkesMaskRight"),
  wearable("212_1337LaptopRight"),
  bodyWearableRight("213_H4xx0rShirt"),
  wearable("214_MatrixEyesRight"),
  wearable("215_CyborgEyeRight"),
  wearable("216_RainbowVomitRight"),
  wearable("217_CyborgGunRight"),
  wearable("218_MohawkRight"),
  wearable("219_MuttonChopsRight"),
  bodyWearableRight("220_PunkShirt"),
  wearable("221_PirateHatRight"),
  bodyWearableRight("222_PirateCoat"),
  wearable("223_HookHandRight"),
  wearable("224_PiratePatchRight"),
  wearable("225_BasketballRight"),
  wearable("226_RedHeadbandRight"),
  wearable("227_MJJerseyRight"),
  wearable("228_10GallonHatRight"),
  wearable("229_LassoRight"),
  wearable("230_WraanglerJeansRight"),
  bodyWearableRight("231_ComfyPoncho"),
  wearable("232_PonchoHoodieRight"),
  "233_UncommonCactiRight",
  bodyWearableRight("234_ShaamanPoncho"),
  wearable("235_ShaamanHoodieRight"),
  "236_BlueCactiRight",
  "237_MythicalCactiRight",
  wearable("238_GodlikeCactiRight"),
  wearable("239_WagieCapRight"),
  wearable("240_HeadphonesRight"),
  bodyWearableRight("241_WGMIShirt"),
  wearable("242_YellowManbunRight"),
  wearable("243_TintedShadesRight"),
  bodyWearableRight("244_VNeckShirt"),
  wearable("245_GeckoHatRight"),
  wearable("246_APYShadesRight"),
  wearable("247_UpArrowRight"),
  bodyWearableRight("248_UpOnlyShirt"),
  wearable("249_CoinGeckoEyesRight"),
  bodyWearableRight("250_CoinGeckoTee"),
  wearable("251_CoinGeckoCandiesRight"),
  wearable("252_AastronautHelmetRight"),
  bodyWearableRight("253_AastronautSuit"),
  wearable("254_uGOTCHITokenRight"),
  wearable("255_LilBubbleHelmetRight"),
  bodyWearableRight("256_LilBubbleSpaceSuit"),
  wearable("257_BitcoinGuitarRight"),
  bodyWearableRight("258_Hanfu"),
  wearable("259_BushyEyebrowsRight"),
  wearable("260_AncientBeardRight"),
  261,
  wearable("262_RadarEyesRight"),
  wearable("263_SignalHeadsetRight"),
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  wearable("292_BrunettePonytailRight"),
  bodyWearableRight("293_LeatherTunic"),
  wearable("294_BowandArrowRight"),
  wearable("295_ForkedBeardRight"),
  wearable("296_DoublesidedAxeRight"),
  bodyWearableRight("297_AnimalSkins"),
  wearable("298_HornedHelmetRight"),
  wearable("299_LongbowRight"),
  wearable("300_FeatheredCapRight"),
  wearable("301_AlluringEyesRight"),
  wearable("302_GeishaHeadpieceRight"),
  bodyWearableRight("303_Kimono"),
  wearable("304_PaperFanRight"),
  wearable("305_SusButterflyRight"),
  wearable("306_FlowerStudsRight"),
  bodyWearableRight("307_FairyWings"),
  wearable("308_RedHairRight"),
  wearable("309_CitaadelHelmRight"),
  bodyWearableRight("310_PlateArmor"),
  wearable("311_SpiritSwordRight"),
  wearable("312_PlateShieldRight"),
  wearable("313_KabutoHelmetRight"),
  bodyWearableRight("314_YoroiArmor"),
  wearable("315_HaanzoKatanaRight"),
  316,
  317,
  318,
  319,
  320,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  // Haalloween Party Badge
  332,
  // TOOORKEY CHAASE Badge
  333,
  //szn 4 baadges
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  // forge wearables
  bodyWearableRight("350_PixelcraftTee"),
  wearable("351_3DGlassesRight"),
  wearable("352_PixelcraftSquareRight"),
  wearable("353_NimbusRight"),
  wearable("354_AlchemicaApronRight"),
  wearable("355_SafetyGlassesRight"),
  "356_BandageRight",
  wearable("357_NailGunRight"),
  wearable("358_FlamingApronRight"),
  wearable("359_ForgeGogglesRight"),
  wearable("360_GeodeSmasherRight"),
  wearable("361_GeoRight"),
  bodyWearableRight("362_FAKEShirt"),
  wearable("363_FAKEBeretRight"),
  wearable("364_PaintBrushRight"),
  wearable("365_PaintPaletteRight"),
  bodyWearableRight("366_HeavenlyRobes"),
  wearable("367_EyesofDevotionRight"),
  wearable("368_BeardofDivinityRight"),
  wearable("369_StaffofCreationRight"),
  //forge wearables2
  wearable("370_WavyHairRight"),
  wearable("371_PlasticEarringsRight"),
  bodyWearableRight("372_PartyDress"),
  bodyWearableRight("373_Overalls"),
  "374_LensFrensPlantRight",
  wearable("375_GMSeedsRight"),
  wearable("376_LickBrainRight"),
  wearable("377_LickEyesRight"),
  wearable("378_LickTongueRight"),
  wearable("379_LickTentacleRight"),
  wearable("380_SebastienHairRight"),
  wearable("381_VoxelEyesRight"),
  wearable("382_GOATeeRight"),
  bodyWearableRight("383_SandboxHoodie"),
  wearable("384_FaangsRight"),
  wearable("385_BlockScannersRight"),
  wearable("386_StaffCharmingRight"),
  wearable("387_RoflnogginRight"),
];

export const wearablesBackSvgs = [
  wearable("0_VoidBack"),
  wearable("1_CamoHatBack"),
  wearable("2_CamoPantsBack"), // body but doesn't have sleeves
  wearable("3_MK2Grenade"),
  wearable("4_SnowCamoHatBack"),
  wearable("5_SnowCamoPantsBack"), // body but no sleeves
  wearable("6_M67Grenade"),
  wearable("7_MarineCapBack"),
  bodyWearable("8_MarineJacket"), // bodyWearable("8_MarineJacket"),
  wearable("9_WalkieTalkieBack"),
  wearable("10_LinkWhiteHatBack"),
  bodyWearable("11_MessDress"), // bodyWearable("11_MessDress"),
  wearable("12_LinkBubbly"),
  wearable("13_SergeyBeardBack"),
  "14_SergeyEyesBack", // no eyes for back side
  bodyWearable("15_RedPlaid"), // bodyWearable("15_RedPlaid"),
  bodyWearable("16_BluePlaid"), //  bodyWearable("16_BluePlaid"),
  wearable("17_LinkCubeBack"),
  wearable("18_AaveHeroMaskBack"),
  bodyWearable("19_AaveHeroShirt"), // bodyWearable("19_AaveHeroShirt"),
  wearable("20_AavePlushBack"),
  wearable("21_CaptainAaveMaskBack"),
  bodyWearable("22_CaptainAaveSuit"), // bodyWearable("22_CaptainAaveSuit"),
  wearable("23_CaptainAaveShieldBack"),
  wearable("24_ThaaveHelmetBack"),
  wearable("25_ThaaveSuitBack"), // bodyWearable("25_ThaaveSuit"),
  wearable("26_ThaaveHammerBack"),
  wearable("27_MarcHairBack"),
  bodyWearable("28_MarcOutfit"), // bodyWearable("28_MarcOutfit"),
  wearable("29_REKTSignBack"),
  wearable("30_JordanHairBack"),
  bodyWearable("31_JordanSuit"), // bodyWearable("31_JordanSuit"),
  wearable("32_AaveFlagBack"),
  wearable("33_StaniHairBack"),
  wearable("34_StaniVestBack"), // bodyWearable("34_StaniVest"),
  wearable("35_AaveBoatBack"),
  wearable("36_ETHMaxiGlassesBack"),
  bodyWearable("37_ETHTShirt"),
  wearable("38_32ETHCoinBack"), //may need ETHCoinBackRight
  wearable("39_FoxyMaskBack"),
  wearable("40_FoxyTailBack"), // body but no sleeves
  wearable("41_TrezorWalletBack"),
  wearable("42_NogaraEagleMaskBack"),
  bodyWearable("43_NogaraEagleArmor"),
  wearable("44_DAOEggBack"),
  wearable("45_ApeMaskBack"),
  bodyWearable("46_HalfRektShirt"),
  wearable("47_WaifuPillowBack"),
  wearable("48_XibotMohawkBack"),
  wearable("49_CoderdanShadesBack"),
  bodyWearable("50_GldnXrossRobe"),
  wearable("51_MudgenDiamondBack"),
  wearable("52_GalaxyBrainBack"),
  "53_AllSeeingEyesBack",
  bodyWearable("54_LlamacornShirt"),
  wearable("55_AagentHeadsetBack"),
  bodyWearable("56_AagentShirt"),
  wearable("57_AagentShadesBack"),
  wearable("58_AagentPistolBack"),
  wearable("59_AagentFedoraHatBack"),
  wearable("60_WizardHatBack"),
  wearable("61_WizardHatLegendaryBack"),
  wearable("62_WizardHatMythicalBack"),
  wearable("63_WizardHatGodlikeBack"),
  wearable("64_WizardStaffBack"),
  wearable("65_WizardStaffLegendaryBack"),
  wearable("66_FutureWizardVisorBack"),
  wearable("67_FarmerStrawHatBack"),
  wearable("68_FarmerJeansBack"), // Body but no sleeves
  wearable("69_FarmerPitchforkBack"),
  wearable("70_FarmerHandsawBack"),
  wearable("71_SantagotchiHatBack"),
  wearable("72_JaayHairpieceBack"),
  wearable("73_JaayGlassesBack"),
  bodyWearable("74_JaayHaoSuit"),
  wearable("75_OKexSignBack"),
  wearable("76_BigGHSTTokenBack"),
  wearable("77_BitcoinBeanieBack"),
  wearable("78_SkaterJeansBack"), // Body but no sleeves
  wearable("79_SkateboardBack"),
  wearable("80_SushiHeadbandBack"),
  wearable("81_SushiRobeBack"), // Body but not sleeves
  wearable("82_SushiRollBack"),
  wearable("83_SushiKnifeBack"),
  wearable("84_GentlemanHatBack"),
  bodyWearable("85_GentlemanSuit"),
  "86_GentlemanMonocleBack",
  wearable("87_MinerHelmetBack"),
  wearable("88_MinerJeansBack"), // Body but no sleeves
  wearable("89_MinerPickaxeBack"),
  wearable("90_PajamaHatBack"),
  bodyWearable("91_PajamaPants"),
  wearable("92_BedtimeMilkBack"),
  wearable("93_FluffyBlanketBack"),
  wearable("94_RunnerSweatbandBack"),
  wearable("95_RunnerShortsBack"), // Body but no sleeves
  wearable("96_WaterBottleBack"),
  wearable("97_PillboxHatBack"),
  wearable("98_LadySkirtBack"), // Body but no sleeves
  wearable("99_LadyParasolBack"),
  wearable("100_LadyClutchBack"),
  wearable("101_WitchHatBack"),
  bodyWearable("102_WitchCape"),
  wearable("103_WitchWandBack"),
  wearable("104_PortalMageHelmetBack"),
  bodyWearable("105_PortalMageArmor"),
  wearable("106_PortalMageAxeBack"),
  wearable("107_PortalMageBlackAxeBack"),
  wearable("108_RastaDredsBack"),
  bodyWearable("109_RastaShirt"),
  wearable("110_JamaicanFlagBack"),
  wearable("111_HazmatHoodBack"),
  bodyWearable("112_HazmatSuit"),
  wearable("113_UraniumRodBack"),
  bodyWearable("114_RedHawaiianShirt"),
  bodyWearable("115_BlueHawaiianShirt"),
  wearable("116_CoconutBack"),
  wearable("117_DealWithItShadesBack"),
  wearable("118_WaterJugBack"),
  wearable("119_BabyBottleBack"),
  wearable("120_MartiniBack"),
  wearable("121_WineBottleBack"),
  wearable("122_MilkshakeBack"),
  wearable("123_AppleJuiceBack"),
  wearable("124_BeerHelmetBack"),
  bodyWearable("125_TrackSuit"),
  wearable("126_KinshipPotion"),
  wearable("127_GreaterKinshipPotion"),
  wearable("128_XPPotion"),
  wearable("129_GreaterXPPotion"),
  wearable("130_FireballBack"),
  wearable("131_DragonHornsBack"),
  wearable("132_DragonWingsBack"),
  wearable("133_PointyHornsBack"), // Body wearable but not sleeves
  wearable("134_L2SignBack"),
  bodyWearable("135_PolygonShirt"),
  wearable("136_PolygonCapBack"),
  wearable("137_VoteSignBack"),
  bodyWearable("138_SnapshotShirt"),
  wearable("139_SnapshotHatBack"),
  wearable("140_ElfEarsBack"),
  wearable("141_GemstoneRingBack"),
  wearable("142_PrincessTiaraBack"),
  wearable("143_GoldNecklaceBack"),
  wearable("144_PrincessHairBack"),
  wearable("145_GodliLocksBack"),
  "146_ImperialMoustacheBack",
  wearable("147_TinyCrownBack"),
  wearable("148_RoyalScepterBack"),
  wearable("149_RoyalCrownBack"),
  bodyWearable("150_RoyalRobes"),
  wearable("151_CommonRoflBack"),
  wearable("152_UncommonRoflBack"),
  wearable("153_RareRoflBack"),
  wearable("154_LegendaryRoflBack"),
  wearable("155_MythicalRoflBack"),
  wearable("156_GodlikeRoflBack"),
  "157_LilPumpGoateeLeft",
  wearable("158_LilPumpDrinkBack"),
  wearable("159_LilPumpShadesBack"),
  bodyWearable("160_LilPumpThreads"),
  wearable("161_LilPumpDreadsBack"),
  bodyWearable("162_MiamiShirt"),
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  wearable("199_SteampunkGlassesBack"),
  wearable("200_SteampunkBack"),
  wearable("201_SteampunkGloveBack"),
  wearable("202_CyberpunkVRBack"),
  bodyWearable("203_GamerJacket"),
  wearable("204_CyberpunkControlBack"),
  wearable("205_GotchiMugBack"),
  wearable("206_BikerHelmetBack"),
  wearable("207_BikerJacketBack"),
  wearable("208_AviatorsBack"),
  "209_HorsehoeMustacheBack",
  wearable("210_H1backgroundBack"),
  wearable("211_GuyFauwkesMaskBack"),
  wearable("212_1337LaptopBack"),
  bodyWearable("213_H4xx0rShirt"),
  "214_MatrixEyesBack",
  wearable("215_CyborgEyeBack"),
  wearable("216_RainbowVomitBack"),
  wearable("217_CyborgGunBack"),
  wearable("218_MohawkBack"),
  "219_MuttonChopsBack",
  bodyWearable("220_PunkShirt"),
  wearable("221_PirateHatBack"),
  bodyWearable("222_PirateCoat"),
  wearable("223_HookHandBack"),
  wearable("224_PiratePatchBack"),
  wearable("225_BasketballBack"),
  wearable("226_RedHeadbandBack"),
  wearable("227_MJJerseyBack"),
  wearable("228_10GallonHatBack"),
  wearable("229_LassoBack"),
  wearable("230_WraanglerJeansBack"),
  bodyWearable("231_ComfyPoncho"),
  wearable("232_PonchoHoodieBack"),
  wearable("233_UncommonCactiBack"),
  bodyWearable("234_ShaamanPoncho"),
  wearable("235_ShaamanHoodieBack"),
  wearable("236_BlueCactiBack"),
  wearable("237_MythicalCactiBack"),
  wearable("238_GodlikeCactiBack"),
  wearable("239_WagieCapBack"),
  wearable("240_HeadphonesBack"),
  bodyWearable("241_WGMIShirt"),
  wearable("242_YellowManbunBack"),
  wearable("243_TintedShadesBack"),
  bodyWearable("244_VNeckShirt"),
  wearable("245_GeckoHatBack"),
  wearable("246_APYShadesBack"),
  wearable("247_UpArrowBack"),
  bodyWearable("248_UpOnlyShirt"),
  249,
  bodyWearable("250_CoinGeckoTee"),
  wearable("251_CoinGeckoCandiesBack"),
  wearable("252_AastronautHelmetBack"),
  bodyWearable("253_AastronautSuit"),
  wearable("254_uGOTCHITokenBack"),
  wearable("255_LilBubbleHelmetBack"),
  bodyWearable("256_LilBubbleSpaceSuit"),
  wearable("257_BitcoinGuitarBack"),
  bodyWearable("258_Hanfu"),
  258,
  259,
  wearable("261_AantenaBotBack"),
  262,
  wearable("263_SignalHeadsetBack"),
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  wearable("292_BrunettePonytailBack"),
  bodyWearable("293_LeatherTunic"),
  wearable("294_BowandArrowBack"),
  wearable("295_ForkedBeardBack"),
  wearable("296_DoublesidedAxeBack"),
  bodyWearable("297_AnimalSkins"),
  wearable("298_HornedHelmetBack"),
  wearable("299_LongbowBack"),
  wearable("300_FeatheredCapBack"),
  wearable("301_AlluringEyesBack"),
  wearable("302_GeishaHeadpieceBack"),
  bodyWearable("303_Kimono"),
  wearable("304_PaperFanBack"),
  wearable("305_SusButterflyBack"),
  wearable("306_FlowerStudsBack"),
  bodyWearable("307_FairyWings"),
  wearable("308_RedHairBack"),
  wearable("309_CitaadelHelmBack"),
  bodyWearable("310_PlateArmor"),
  wearable("311_SpiritSwordBack"),
  wearable("312_PlateShieldBack"),
  wearable("313_KabutoHelmetBack"),
  bodyWearable("314_YoroiArmor"),
  wearable("315_HaanzoKatanaBack"),
  316,
  317,
  318,
  319,
  320,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  // Haalloween Party Badge
  332,
  // TOOORKEY CHAASE Badge
  333,
  //szn 4 baadges
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  // forge wearables
  bodyWearable("350_PixelcraftTee"),
  wearable("351_3DGlassesBack"),
  wearable("352_PixelcraftSquareBack"),
  wearable("353_NimbusBack"),
  wearable("354_AlchemicaApronBack"),
  wearable("355_SafetyGlassesBack"),
  "356_BandageBack",
  wearable("357_NailGunBack"),
  wearable("358_FlamingApronBack"),
  wearable("359_ForgeGogglesBack"),
  wearable("360_GeodeSmasherBack"),
  wearable("361_GeoBack"),
  bodyWearable("362_FAKEShirt"),
  wearable("363_FAKEBeretBack"),
  wearable("364_PaintBrushBack"),
  wearable("365_PaintPaletteBack"),
  bodyWearable("366_HeavenlyRobes"),
  "367_EyesofDevotionBack",
  "368_BeardofDivinityBack",
  wearable("369_StaffofCreationBack"),
  //forge wearables2
  wearable("370_WavyHairBack"),
  wearable("371_PlasticEarringsBack"),
  bodyWearable("372_PartyDress"),
  bodyWearable("373_Overalls"),
  wearable("374_LensFrensPlantBack"),
  wearable("375_GMSeedsBack"),
  wearable("376_LickBrainBack"),
  wearable("377_LickEyesBack"),
  "378_LickTongue",
  wearable("379_LickTentacleBack"),
  wearable("380_SebastienHairBack"),
  "381_VoxelEyes",
  "382_GOATee",
  bodyWearable("383_SandboxHoodie"),
  "384_Faangs",
  "385_BlockScanners",
  wearable("386_StaffCharmingBack"),
  wearable("387_RoflnogginBack"),
];

export const wearablesLeftSvgs = [
  wearable("0_VoidLeft"),
  wearable("1_CamoHatLeft"),
  wearable("2_CamoPantsLeft"), // body but doesn't have sleeves
  wearable("3_MK2GrenadeLeft"),
  wearable("4_SnowCamoHatLeft"),
  wearable("5_SnowCamoPantsLeft"), // body but no sleeves
  wearable("6_M67GrenadeLeft"),
  wearable("7_MarineCapLeft"),
  bodyWearableLeft("8_MarineJacket"), // bodyWearableLeft("8_MarineJacket"),
  wearable("9_WalkieTalkieLeft"), //is not left for walkie talkie
  wearable("10_LinkWhiteHatLeft"),
  bodyWearableLeft("11_MessDress"), // bodyWearableLeft("11_MessDress"),
  wearable("12_LinkBubblyLeft"),
  wearable("13_SergeyBeardLeft"),
  wearable("14_SergeyEyesLeft"),
  bodyWearableLeft("15_RedPlaid"), // bodyWearableLeft("15_RedPlaid"),
  bodyWearableLeft("16_BluePlaid"), //  bodyWearableLeft("16_BluePlaid"),
  wearable("17_LinkCubeLeft"),
  wearable("18_AaveHeroMaskLeft"),
  bodyWearableLeft("19_AaveHeroShirt"), // bodyWearableLeft("19_AaveHeroShirt"),
  wearable("20_AavePlushLeft"),
  wearable("21_CaptainAaveMaskLeft"),
  bodyWearableLeft("22_CaptainAaveSuit"), // bodyWearableLeft("22_CaptainAaveSuit"),
  wearable("23_CaptainAaveShieldLeft"),
  wearable("24_ThaaveHelmetLeft"),
  bodyWearableLeft("25_ThaaveSuit"), // bodyWearableLeft("25_ThaaveSuit"),
  wearable("26_ThaaveHammerLeft"),
  wearable("27_MarcHairLeft"),
  bodyWearableLeft("28_MarcOutfit"), // bodyWearableLeft("28_MarcOutfit"),
  "29_REKTSignRight",
  wearable("30_JordanHairLeft"),
  bodyWearableLeft("31_JordanSuit"), // bodyWearableLeft("31_JordanSuit"),
  wearable("32_AaveFlagLeft"),
  wearable("33_StaniHairLeft"),
  wearable("34_StaniVestLeft"), // bodyWearableLeft("34_StaniVest"),
  wearable("35_AaveBoatLeft"),
  wearable("36_ETHMaxiGlassesLeft"),
  bodyWearableLeft("37_ETHTShirt"),
  wearable("38_32ETHCoinRight"),
  wearable("39_FoxyMaskLeft"),
  wearable("40_FoxyTailLeft"), // body but no sleeves
  wearable("41_TrezorWalletLeft"),
  wearable("42_NogaraEagleMaskLeft"),
  bodyWearableLeft("43_NogaraEagleArmor"),
  wearable("44_DAOEggLeft"),
  wearable("45_ApeMaskLeft"),
  bodyWearableLeft("46_HalfRektShirt"),
  wearable("47_WaifuPillowLeft"),
  wearable("48_XibotMohawkLeft"),
  wearable("49_CoderdanShadesLeft"),
  bodyWearableLeft("50_GldnXrossRobe"),
  wearable("51_MudgenDiamondLeft"),
  wearable("52_GalaxyBrainLeft"),
  wearable("53_AllSeeingEyesLeft"),
  bodyWearableLeft("54_LlamacornShirt"),
  wearable("55_AagentHeadsetLeft"),
  bodyWearableLeft("56_AagentShirt"),
  wearable("57_AagentShadesLeft"),
  wearable("58_AagentPistolLeft"),
  wearable("59_AagentFedoraHatLeft"),
  wearable("60_WizardHatLeft"),
  wearable("61_WizardHatLegendaryLeft"),
  wearable("62_WizardHatMythicalLeft"),
  wearable("63_WizardHatGodlikeLeft"),
  wearable("64_WizardStaffLeft"),
  wearable("65_WizardStaffLegendaryLeft"),
  wearable("66_FutureWizardVisorLeft"),
  wearable("67_FarmerStrawHatLeft"),
  wearable("68_FarmerJeansLeft"), // Body but no sleeves
  wearable("69_FarmerPitchforkLeft"),
  wearable("70_FarmerHandsawLeft"),
  wearable("71_SantagotchiHatLeft"),
  wearable("72_JaayHairpieceLeft"),
  wearable("73_JaayGlassesLeft"),
  bodyWearableLeft("74_JaayHaoSuit"),
  wearable("75_OKexSignLeft"),
  wearable("76_BigGHSTTokenLeft"),
  wearable("77_BitcoinBeanieLeft"),
  wearable("78_SkaterJeansLeft"), // Body but no sleeves
  wearable("79_SkateboardLeft"),
  wearable("80_SushiHeadbandLeft"),
  wearable("81_SushiRobeLeft"), // Body but not sleeves
  wearable("82_SushiRollLeft"),
  wearable("83_SushiKnifeLeft"),
  wearable("84_GentlemanHatLeft"),
  bodyWearableLeft("85_GentlemanSuit"),
  wearable("86_GentlemanMonocleLeft"),
  wearable("87_MinerHelmetLeft"),
  wearable("88_MinerJeansLeft"), // Body but no sleeves
  wearable("89_MinerPickaxeLeft"),
  wearable("90_PajamaHatLeft"),
  bodyWearableLeft("91_PajamaPants"),
  wearable("92_BedtimeMilkLeft"),
  wearable("93_FluffyBlanketLeft"),
  wearable("94_RunnerSweatbandLeft"),
  wearable("95_RunnerShortsLeft"), // Body but no sleeves
  wearable("96_WaterBottleLeft"),
  wearable("97_PillboxHatLeft"),
  wearable("98_LadySkirtLeft"), // Body but no sleeves
  wearable("99_LadyParasolLeft"),
  wearable("100_LadyClutchLeft"),
  wearable("101_WitchHatLeft"),
  bodyWearableLeft("102_WitchCape"),
  wearable("103_WitchWandLeft"),
  wearable("104_PortalMageHelmetLeft"),
  bodyWearableLeft("105_PortalMageArmor"),
  wearable("106_PortalMageAxeLeft"),
  wearable("107_PortalMageBlackAxeLeft"),
  wearable("108_RastaDredsLeft"),
  bodyWearableLeft("109_RastaShirt"),
  wearable("110_JamaicanFlagLeft"),
  wearable("111_HazmatHoodLeft"),
  bodyWearableLeft("112_HazmatSuit"),
  wearable("113_UraniumRodLeft"),
  bodyWearableLeft("114_RedHawaiianShirt"),
  bodyWearableLeft("115_BlueHawaiianShirt"),
  wearable("116_CoconutLeft"),
  wearable("117_DealWithItShadesLeft"),
  wearable("118_WaterJugLeft"),
  wearable("119_BabyBottleLeft"),
  wearable("120_MartiniLeft"),
  wearable("121_WineBottleLeft"),
  wearable("122_MilkshakeLeft"),
  wearable("123_AppleJuiceLeft"),
  wearable("124_BeerHelmetLeft"),
  bodyWearableLeft("125_TrackSuit"),
  wearable("126_KinshipPotion"),
  wearable("127_GreaterKinshipPotion"),
  wearable("128_XPPotion"),
  wearable("129_GreaterXPPotion"),
  wearable("130_FireballLeft"),
  wearable("131_DragonHornsLeft"),
  wearable("132_DragonWingsLeft"),
  wearable("133_PointyHornsLeft"), // Body wearable but not sleeves
  wearable("134_L2SignLeft"),
  bodyWearableLeft("135_PolygonShirt"),
  wearable("136_PolygonCapLeft"),
  wearable("137_VoteSignLeft"),
  bodyWearableLeft("138_SnapshotShirt"),
  wearable("139_SnapshotHatLeft"),
  wearable("140_ElfEarsLeft"),
  wearable("141_GemstoneRingLeft"),
  wearable("142_PrincessTiaraLeft"),
  wearable("143_GoldNecklaceLeft"),
  wearable("144_PrincessHairLeft"),
  wearable("145_GodliLocksLeft"),
  wearable("146_ImperialMoustacheLeft"),
  wearable("147_TinyCrownLeft"),
  wearable("148_RoyalScepterLeft"),
  wearable("149_RoyalCrownLeft"),
  bodyWearableLeft("150_RoyalRobes"),
  wearable("151_CommonRoflLeft"),
  wearable("152_UncommonRoflLeft"),
  wearable("153_RareRoflLeft"),
  wearable("154_LegendaryRoflLeft"),
  wearable("155_MythicalRoflLeft"),
  wearable("156_GodlikeRoflLeft"),
  "157_LilPumpGoateeLeft",
  wearable("158_LilPumpDrinkLeft"),
  wearable("159_LilPumpShadesLeft"),
  bodyWearableLeft("160_LilPumpThreads"),
  wearable("161_LilPumpDreadsLeft"),
  bodyWearableLeft("162_MiamiShirt"),
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  wearable("199_SteampunkGlassesLeft"),
  wearable("200_SteampunkLeft"),
  wearable("201_SteampunkGloveLeft"),
  wearable("202_CyberpunkVRLeft"),
  bodyWearableLeft("203_GamerJacket"),
  wearable("204_CyberpunkControlLeft"),
  wearable("205_GotchiMugLeft"),
  wearable("206_BikerHelmetLeft"),
  wearable("207_BikerJacketLeft"),
  wearable("208_AviatorsLeft"),
  wearable("209_HorsehoeMustacheLeft"),
  wearable("210_H1backgroundLeft"),
  wearable("211_GuyFauwkesMaskLeft"),
  wearable("212_1337LaptopLeft"),
  bodyWearableLeft("213_H4xx0rShirt"),
  wearable("214_MatrixEyesLeft"),
  wearable("215_CyborgEyeLeft"),
  wearable("216_RainbowVomitLeft"),
  wearable("217_CyborgGunLeft"),
  wearable("218_MohawkLeft"),
  wearable("219_MuttonChopsLeft"),
  bodyWearableLeft("220_PunkShirt"),
  wearable("221_PirateHatLeft"),
  bodyWearableLeft("222_PirateCoat"),
  wearable("223_HookHandLeft"),
  wearable("224_PiratePatchLeft"),
  wearable("225_BasketballLeft"),
  wearable("226_RedHeadbandLeft"),
  wearable("227_MJJerseyLeft"),
  wearable("228_10GallonHatLeft"),
  wearable("229_LassoLeft"),
  wearable("230_WraanglerJeansLeft"),
  bodyWearableLeft("231_ComfyPoncho"),
  wearable("232_PonchoHoodieLeft"),
  wearable("233_UncommonCactiLeft"),
  bodyWearableLeft("234_ShaamanPoncho"),
  wearable("235_ShaamanHoodieLeft"),
  wearable("236_BlueCactiLeft"),
  wearable("237_MythicalCactiLeft"),
  wearable("238_GodlikeCactiLeft"),
  wearable("239_WagieCapLeft"),
  wearable("240_HeadphonesLeft"),
  bodyWearableLeft("241_WGMIShirt"),
  wearable("242_YellowManbunLeft"),
  wearable("243_TintedShadesLeft"),
  bodyWearableLeft("244_VNeckShirt"),
  wearable("245_GeckoHatLeft"),
  wearable("246_APYShadesLeft"),
  wearable("247_UpArrowLeft"),
  bodyWearableLeft("248_UpOnlyShirt"),
  wearable("249_CoinGeckoEyesLeft"),
  bodyWearableLeft("250_CoinGeckoTee"),
  wearable("251_CoinGeckoCandiesLeft"),
  wearable("252_AastronautHelmetLeft"),
  bodyWearableLeft("253_AastronautSuit"),
  wearable("254_uGOTCHITokenLeft"),
  wearable("255_LilBubbleHelmetLeft"),
  bodyWearableLeft("256_LilBubbleSpaceSuit"),
  wearable("257_BitcoinGuitarLeft"),
  bodyWearableLeft("258_Hanfu"),
  wearable("259_BushyEyebrowsLeft"),
  wearable("260_AncientBeardLeft"),
  wearable("261_AantenaBotLeft"),
  wearable("262_RadarEyesLeft"),
  wearable("263_SignalHeadsetLeft"),
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  wearable("292_BrunettePonytailLeft"),
  bodyWearableLeft("293_LeatherTunic"),
  wearable("294_BowandArrowLeft"),
  wearable("295_ForkedBeardLeft"),
  wearable("296_DoublesidedAxeLeft"),
  bodyWearableLeft("297_AnimalSkins"),
  wearable("298_HornedHelmetLeft"),
  wearable("299_LongbowLeft"),
  wearable("300_FeatheredCapLeft"),
  wearable("301_AlluringEyesLeft"),
  wearable("302_GeishaHeadpieceLeft"),
  bodyWearableLeft("303_Kimono"),
  wearable("304_PaperFanLeft"),
  wearable("305_SusButterflyLeft"),
  wearable("306_FlowerStudsLeft"),
  bodyWearableLeft("307_FairyWings"),
  wearable("308_RedHairLeft"),
  wearable("309_CitaadelHelmLeft"),
  bodyWearableLeft("310_PlateArmor"),
  wearable("311_SpiritSwordLeft"),
  wearable("312_PlateShieldLeft"),
  wearable("313_KabutoHelmetLeft"),
  bodyWearableLeft("314_YoroiArmor"),
  wearable("315_HaanzoKatanaLeft"),
  316,
  317,
  318,
  319,
  320,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  // Haalloween Party Badge
  332,
  // TOOORKEY CHAASE Badge
  333,
  //szn 4 baadges
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  // forge wearables
  bodyWearableLeft("350_PixelcraftTee"),
  wearable("351_3DGlassesLeft"),
  wearable("352_PixelcraftSquareLeft"),
  wearable("353_NimbusLeft"),
  wearable("354_AlchemicaApronLeft"),
  wearable("355_SafetyGlassesLeft"),
  wearable("356_BandageLeft"),
  wearable("357_NailGunLeft"),
  wearable("358_FlamingApronLeft"),
  wearable("359_ForgeGogglesLeft"),
  wearable("360_GeodeSmasherLeft"),
  wearable("361_GeoLeft"),
  bodyWearableLeft("362_FAKEShirt"),
  wearable("363_FAKEBeretLeft"),
  wearable("364_PaintBrushLeft"),
  wearable("365_PaintPaletteLeft"),
  bodyWearableLeft("366_HeavenlyRobes"),
  wearable("367_EyesofDevotionLeft"),
  wearable("368_BeardofDivinityLeft"),
  wearable("369_StaffofCreationLeft"),
  //forge wearables2
  wearable("370_WavyHairLeft"),
  wearable("371_PlasticEarringsLeft"),
  bodyWearableLeft("372_PartyDress"),
  bodyWearableLeft("373_Overalls"),
  wearable("374_LensFrensPlantLeft"),
  wearable("375_GMSeedsLeft"),
  wearable("376_LickBrainLeft"),
  wearable("377_LickEyesLeft"),
  wearable("378_LickTongueLeft"),
  wearable("379_LickTentacleLeft"),
  wearable("380_SebastienHairLeft"),
  wearable("381_VoxelEyesLeft"),
  wearable("382_GOATeeLeft"),
  bodyWearableLeft("383_SandboxHoodie"),
  wearable("384_FaangsLeft"),
  wearable("385_BlockScannersLeft"),
  wearable("386_StaffCharmingLeft"),
  wearable("387_RoflnogginLeft"),
];

export const wearablesLeftSleeveSvgs = [
  // '0_VoidLeft',
  // '1_CamoHatLeft',
  // '2_CamoPantsLeft', // body but doesn't have sleeves
  // '3_MK2GrenadeLeft',
  // '4_SnowCamoHatLeft',
  // "5_SnowCamoPantsLeft", // body but no sleeves
  // '6_M67GrenadeLeft',
  // '7_MarineCapLeft',
  sleeveWearableLeft("8_MarineJacket"), // sleeveWearableLeft("8_MarineJacket"),
  // '9_WalkieTalkieRightSide', //is not left for walkie talkie
  // '10_LinkWhiteHatLeft',
  sleeveWearableLeft("11_MessDress"), // sleeveWearableLeft("11_MessDress"),
  // '12_LinkBubblyLeft',
  // '13_SergeyBeardLeft',
  // '14_SergeyEyesLeft',
  sleeveWearableLeft("15_RedPlaid"), // sleeveWearableLeft("15_RedPlaid"),
  sleeveWearableLeft("16_BluePlaid"), //  sleeveWearableLeft("16_BluePlaid"),
  // '17_LinkCubeLeft',
  // '18_AaveHeroMaskLeft',
  sleeveWearableLeft("19_AaveHeroShirt"), // sleeveWearableLeft("19_AaveHeroShirt"),
  // '20_AavePlushLeft',
  // '21_CaptainAaveMaskLeft',
  sleeveWearableLeft("22_CaptainAaveSuit"), // sleeveWearableLeft("22_CaptainAaveSuit"),
  // '23_CaptainAaveShieldLeft',
  // '24_ThaaveHelmetLeft',
  // sleeveWearableLeft("25_ThaaveSuit"),
  // '26_ThaaveHammerLeft',
  // '27_MarcHairLeft',
  sleeveWearableLeft("28_MarcOutfit"), // sleeveWearableLeft("28_MarcOutfit"),
  // '29_REKTSignLeft',
  // '30_JordanHairLeft',
  sleeveWearableLeft("31_JordanSuit"), // sleeveWearableLeft("31_JordanSuit"),
  // '32_AaveFlagLeft',
  // '33_StaniHairLeft',
  // '34_StaniVestLeft', // sleeveWearableLeft("34_StaniVest"),
  // '35_AaveBoatLeft',
  // '36_ETHMaxiGlassesLeft',
  sleeveWearableLeft("37_ETHTShirt"),
  // '38_32ETHCoinLeft',
  // '39_FoxyMaskLeft',
  // '40_FoxyTailLeft', // body but no sleeves
  // '41_TrezorWalletLeft',
  // '42_NogaraEagleMaskLeft',
  sleeveWearableLeft("43_NogaraEagleArmor"),
  // '44_DAOEggLeft',
  // '45_ApeMaskLeft',
  sleeveWearableLeft("46_HalfRektShirt"),
  // '47_WaifuPillowLeft',
  // '48_XibotMohawkLeft',
  // '49_CoderdanShadesLeft',
  sleeveWearableLeft("50_GldnXrossRobe"),
  // '51_MudgenDiamondLeft',
  // '52_GalaxyBrainLeft',
  // '53_AllSeeingEyesLeft',
  sleeveWearableLeft("54_LlamacornShirt"),
  // '55_AagentHeadsetLeft',
  sleeveWearableLeft("56_AagentShirt"),
  // '57_AagentShadesLeft',
  // '58_AagentPistolLeft',
  // '59_AagentFedoraHatLeft',
  // '60_WizardHatLeft',
  // '61_WizardHatLegendaryLeft',
  // '62_WizardHatMythicalLeft',
  // '63_WizardHatGodlikeLeft',
  // '64_WizardStaffLeft',
  // '65_WizardStaffLegendaryLeft',
  // '66_FutureWizardVisorLeft',
  // '67_FarmerStrawHatLeft',
  // '68_FarmerJeansLeft', // Body but no sleeves
  // '69_FarmerPitchforkLeft',
  // '70_FarmerHandsawLeft',
  // '71_SantagotchiHatLeft',
  // '72_JaayHairpieceLeft',
  // '73_JaayGlassesLeft',
  sleeveWearableLeft("74_JaayHaoSuit"),
  // '75_OKexSignLeft',
  // '76_BigGHSTTokenLeft',
  // '77_BitcoinBeanieLeft',
  // '78_SkaterJeansLeft', // Body but no sleeves
  // '79_SkateboardLeft',
  // '80_SushiHeadbandLeft',
  // '81_SushiRobeLeft', // Body but not sleeves
  // '82_SushiRollLeft',
  // '83_SushiKnifeLeft',
  // '84_GentlemanHatLeft',
  sleeveWearableLeft("85_GentlemanSuit"),
  // '86_GentlemanMonocleLeft',
  // '87_MinerHelmetLeft',
  // '88_MinerJeansLeft', // Body but no sleeves
  // '89_MinerPickaxeLeft',
  // '90_PajamaHatLeft',
  sleeveWearableLeft("91_PajamaPants"),
  // '92_BedtimeMilkLeft',
  // '93_FluffyBlanketLeft',
  // '94_RunnerSweatbandLeft',
  // '95_RunnerShortsLeft', // Body but no sleeves
  // '96_WaterBottleLeft',
  // '97_PillboxHatLeft',
  // '98_LadySkirtLeft', // Body but no sleeves
  // '99_LadyParasolLeft',
  // '100_LadyClutchLeft',
  // '101_WitchHatLeft',
  sleeveWearableLeft("102_WitchCape"),
  // '103_WitchWandLeft',
  // '104_PortalMageHelmetLeft',
  sleeveWearableLeft("105_PortalMageArmor"),
  // '106_PortalMageAxeLeft',
  // '107_PortalMageBlackAxeLeft',
  // '108_RastaDredsLeft',
  sleeveWearableLeft("109_RastaShirt"),
  // '110_JamaicanFlagLeft',
  // '111_HazmatHoodLeft',
  sleeveWearableLeft("112_HazmatSuit"),
  // '113_UraniumRodLeft',
  sleeveWearableLeft("114_RedHawaiianShirt"),
  sleeveWearableLeft("115_BlueHawaiianShirt"),
  // '116_CoconutLeft',
  // '117_DealWithItShadesLeft',
  // '118_WaterJugLeft',
  // '119_BabyBottleLeft',
  // '120_MartiniLeft',
  // '121_WineBottleLeft',
  // '122_MilkshakeLeft',
  // '123_AppleJuiceLeft',
  // '124_BeerHelmetLeft',
  // sleeveWearableLeft("125_TrackSuit"),
  // '126_KinshipPotionLeft',
  // '127_GreaterKinshipPotionLeft',
  // '128_XPPotionLeft',
  // '129_GreaterXPPotionLeft',
  // '130_FireballLeft',
  // '131_DragonHornsLeft',
  // '132_DragonWingsLeft',
  // '133_PointyHornsLeft', // Body wearable but not sleeves
  // '134_L2SignLeft',
  sleeveWearableLeft("135_PolygonShirt"),
  // '136_PolygonCapLeft',
  // '137_VoteSignLeft',
  sleeveWearableLeft("138_SnapshotShirt"),
  // '139_SnapshotHatLeft',
  // '140_ElfEarsLeft',
  // '141_GemstoneRingLeft',
  // '142_PrincessTiaraLeft',
  // '143_GoldNecklaceLeft',
  // '144_PrincessHairLeft',
  // '145_GodliLocksLeft',
  // '146_ImperialMoustacheLeft',
  // '147_TinyCrownLeft',
  // '148_RoyalScepterLeft',
  // '149_RoyalCrownLeft',
  sleeveWearableLeft("150_RoyalRobes"),
  // '151_CommonRoflLeft',
  // '152_UncommonRoflLeft',
  // '153_RareRoflLeft',
  // '154_LegendaryRoflLeft',
  // '155_MythicalRoflLeft',
  // '156_GodlikeRoflLeft',
  // '157_LilPumpGoateeLeft',
  // '158_LilPumpDrinkLeft',
  // '159_LilPumpShadesLeft',
  sleeveWearableLeft("160_LilPumpThreads"),
  // '161_LilPumpDreadsLeft',
  sleeveWearableLeft("162_MiamiShirt"),
  // '199_SteampunkGlassesLeft',
  // '200_SteampunkLeft',
  // '201_SteampunkGlove',
  // '202_CyberpunkVRLeft',
  sleeveWearableLeft("203_GamerJacket"),
  // '204_CyberpunkControlLeft',
  // '205_CoffeeCupLeft',
  // '206_AagentRadioLeft',
  // sleeveWearableLeft('207_BikerJacket'),
  sleeveWearableLeft("213_H4xx0rShirt"),
  sleeveWearableLeft("220_PunkShirt"),
  sleeveWearableLeft("222_PirateCoat"),
  sleeveWearableLeft("231_ComfyPoncho"),
  // sleeveWearableLeft('232_PonchoHoodie'),
  sleeveWearableLeft("234_ShaamanPoncho"),
  sleeveWearableLeft("241_WGMIShirt"),
  sleeveWearableLeft("244_VNeckShirt"),
  sleeveWearableLeft("248_UpOnlyShirt"),
  sleeveWearableLeft("250_CoinGeckoTee"),
  sleeveWearableLeft("253_AastronautSuit"),
  sleeveWearableLeft("256_LilBubbleSpaceSuit"),
  sleeveWearableLeft("258_Hanfu"),
  sleeveWearableLeft("293_LeatherTunic"),
  sleeveWearableLeft("297_AnimalSkins"),
  sleeveWearableLeft("303_Kimono"),
  sleeveWearableLeft("307_FairyWings"),
  sleeveWearableLeft("310_PlateArmor"),
  sleeveWearableLeft("314_YoroiArmor"),
  "sleeves gap",
  "sleeves gap",

  sleeveWearableLeft("316_MarineJacket"),
  sleeveWearableLeft("317_ThaaveSuit"),
  sleeveWearableLeft("318_TrackSuit"),
  // forge wearables
  sleeveWearableLeft("350_PixelcraftTee"),
  sleeveWearableLeft("362_FAKEShirt"),
  sleeveWearableLeft("366_HeavenlyRobes"),
  //forge wearables2
  sleeveWearableLeft("372_PartyDress"),
  sleeveWearableLeft("373_Overalls"),
  sleeveWearableLeft("383_SandboxHoodie"),
];

export const wearablesRightSleeveSvgs = [
  // '0_VoidRight',
  // '1_CamoHatRight',
  // '2_CamoPantsRight', // body but doesn't have sleeves
  // '3_MK2GrenadeRight',
  // '4_SnowCamoHatRight',
  // "5_SnowCamoPantsRight", // body but no sleeves
  // '6_M67GrenadeRight',
  // '7_MarineCapRight',
  sleeveWearableRight("8_MarineJacket"), // sleeveWearableRight("8_MarineJacket"),
  // '9_WalkieTalkie',
  // '10_LinkWhiteHatRight',
  sleeveWearableRight("11_MessDress"), // sleeveWearableRight("11_MessDress"),
  // '12_LinkBubblyRight',
  // '13_SergeyBeardRight',
  // '14_SergeyEyesRight',
  sleeveWearableRight("15_RedPlaid"), // sleeveWearableRight("15_RedPlaid"),
  sleeveWearableRight("16_BluePlaid"), //  sleeveWearableRight("16_BluePlaid"),
  // '17_LinkCubeRight',
  // '18_AaveHeroMaskRight',
  sleeveWearableRight("19_AaveHeroShirt"), // sleeveWearableRight("19_AaveHeroShirt"),
  // '20_AavePlushRight',
  // '21_CaptainAaveMaskRight',
  sleeveWearableRight("22_CaptainAaveSuit"), // sleeveWearableRight("22_CaptainAaveSuit"),
  // '23_CaptainAaveShieldRight',
  // '24_ThaaveHelmetRight',
  // sleeveWearableRight("25_ThaaveSuit"),
  // '26_ThaaveHammerRight',
  // '27_MarcHairRight',
  sleeveWearableRight("28_MarcOutfit"), // sleeveWearableRight("28_MarcOutfit"),
  // '29_REKTSignRight',
  // '30_JordanHairRight',
  sleeveWearableRight("31_JordanSuit"), // sleeveWearableRight("31_JordanSuit"),
  // '32_AaveFlagRight',
  // '33_StaniHairRight',
  // '34_StaniVestRight', // sleeveWearableRight("34_StaniVest"),
  // '35_AaveBoatRight',
  // '36_ETHMaxiGlassesRight',
  sleeveWearableRight("37_ETHTShirt"),
  // '38_32ETHCoinRight',
  // '39_FoxyMaskRight',
  // '40_FoxyTailRight', // body but no sleeves
  // '41_TrezorWalletRight',
  // '42_NogaraEagleMaskRight',
  sleeveWearableRight("43_NogaraEagleArmor"),
  // '44_DAOEggRight',
  // '45_ApeMaskRight',
  sleeveWearableRight("46_HalfRektShirt"),
  // '47_WaifuPillowRight',
  // '48_XibotMohawkRight',
  // '49_CoderdanShadesRight',
  sleeveWearableRight("50_GldnXrossRobe"),
  // '51_MudgenDiamondRight',
  // '52_GalaxyBrainRight',
  // '53_AllSeeingEyesRight',
  sleeveWearableRight("54_LlamacornShirt"),
  // '55_AagentHeadsetRight',
  sleeveWearableRight("56_AagentShirt"),
  // '57_AagentShadesRight',
  // '58_AagentPistolRight',
  // '59_AagentFedoraHatRight',
  // '60_WizardHatRight',
  // '61_WizardHatLegendaryRight',
  // '62_WizardHatMythicalRight',
  // '63_WizardHatGodlikeRight',
  // '64_WizardStaffRight',
  // '65_WizardStaffLegendaryRight',
  // '66_FutureWizardVisorRight',
  // '67_FarmerStrawHatRight',
  // '68_FarmerJeansRight', // Body but no sleeves
  // '69_FarmerPitchforkRight',
  // '70_FarmerHandsawRight',
  // '71_SantagotchiHatRight',
  // '72_JaayHairpieceRight',
  // '73_JaayGlassesRight',
  sleeveWearableRight("74_JaayHaoSuit"),
  // '75_OKexSignRight',
  // '76_BigGHSTTokenRight',
  // '77_BitcoinBeanieRight',
  // '78_SkaterJeansRight', // Body but no sleeves
  // '79_SkateboardRight',
  // '80_SushiHeadbandRight',
  // '81_SushiRobeRight', // Body but not sleeves
  // '82_SushiRollRight',
  // '83_SushiKnifeRight',
  // '84_GentlemanHatRight',
  sleeveWearableRight("85_GentlemanSuit"),
  // '86_GentlemanMonocleRight',
  // '87_MinerHelmetRight',
  // '88_MinerJeansRight', // Body but no sleeves
  // '89_MinerPickaxeRight',
  // '90_PajamaHatRight',
  sleeveWearableRight("91_PajamaPants"),
  // '92_BedtimeMilkRight',
  // '93_FluffyBlanketRight',
  // '94_RunnerSweatbandRight',
  // '95_RunnerShortsRight', // Body but no sleeves
  // '96_WaterBottleRight',
  // '97_PillboxHatRight',
  // '98_LadySkirtRight', // Body but no sleeves
  // '99_LadyParasolRight',
  // '100_LadyClutchRight',
  // '101_WitchHatRight',
  sleeveWearableRight("102_WitchCape"),
  // '103_WitchWandRight',
  // '104_PortalMageHelmetRight',
  sleeveWearableRight("105_PortalMageArmor"),
  // '106_PortalMageAxeRight',
  // '107_PortalMageBlackAxeRight',
  // '108_RastaDredsRight',
  sleeveWearableRight("109_RastaShirt"),
  // '110_JamaicanFlagRight',
  // '111_HazmatHoodRight',
  sleeveWearableRight("112_HazmatSuit"),
  // '113_UraniumRodRight',
  sleeveWearableRight("114_RedHawaiianShirt"),
  sleeveWearableRight("115_BlueHawaiianShirt"),
  // '116_CoconutRight',
  // '117_DealWithItShadesRight',
  // '118_WaterJugRight',
  // '119_BabyBottleRight',
  // '120_MartiniRight',
  // '121_WineBottleRight',
  // '122_MilkshakeRight',
  // '123_AppleJuiceRight',
  // '124_BeerHelmetRight',
  // sleeveWearableRight("125_TrackSuit"),
  // '126_KinshipPotionRight',
  // '127_GreaterKinshipPotionRight',
  // '128_XPPotionRight',
  // '129_GreaterXPPotionRight',
  // '130_FireballRight',
  // '131_DragonHornsRight',
  // '132_DragonWingsRight',
  // '133_PointyHornsRight', // Body wearable but not sleeves
  // '134_L2SignRight',
  sleeveWearableRight("135_PolygonShirt"),
  // '136_PolygonCapRight',
  // '137_VoteSignRight',
  sleeveWearableRight("138_SnapshotShirt"),
  // '139_SnapshotHatRight',
  // '140_ElfEarsRight',
  // '141_GemstoneRingRight',
  // '142_PrincessTiaraRight',
  // '143_GoldNecklaceRight',
  // '144_PrincessHairRight',
  // '145_GodliLocksRight',
  // '146_ImperialMoustacheRight',
  // '147_TinyCrownRight',
  // '148_RoyalScepterRight',
  // '149_RoyalCrownRight',
  sleeveWearableRight("150_RoyalRobes"),
  // '151_CommonRoflRight',
  // '152_UncommonRoflRight',
  // '153_RareRoflRight',
  // '154_LegendaryRoflRight',
  // '155_MythicalRoflRight',
  // '156_GodlikeRoflRight',
  // '157_LilPumpGoateeRight',
  // '158_LilPumpDrinkRight',
  // '159_LilPumpShadesRight',
  sleeveWearableRight("160_LilPumpThreads"),
  // '161_LilPumpDreadsRight',
  sleeveWearableRight("162_MiamiShirt"),
  // '199_SteampunkGlassesRight',
  // '200_SteampunkRight',
  // '201_SteampunkGlove',
  // '202_CyberpunkVRRight',
  sleeveWearableRight("203_GamerJacket"),
  // '204_CyberpunkControlRight',
  // '205_CoffeeCupRight',
  // '206_AagentRadioRight',
  // sleeveWearableRight('207_BikerJacket'),
  sleeveWearableRight("213_H4xx0rShirt"),
  sleeveWearableRight("220_PunkShirt"),
  sleeveWearableRight("222_PirateCoat"),
  sleeveWearableRight("231_ComfyPoncho"),
  // sleeveWearableRight('232_PonchoHoodie'),
  sleeveWearableRight("234_ShaamanPoncho"),
  sleeveWearableRight("241_WGMIShirt"),
  sleeveWearableRight("244_VNeckShirt"),
  sleeveWearableRight("248_UpOnlyShirt"),
  sleeveWearableRight("250_CoinGeckoTee"),
  sleeveWearableRight("253_AastronautSuit"),
  sleeveWearableRight("256_LilBubbleSpaceSuit"),
  sleeveWearableRight("258_Hanfu"),
  sleeveWearableRight("293_LeatherTunic"),
  sleeveWearableRight("297_AnimalSkins"),
  sleeveWearableRight("303_Kimono"),
  sleeveWearableRight("307_FairyWings"),
  sleeveWearableRight("310_PlateArmor"),
  sleeveWearableRight("314_YoroiArmor"),
  "sleeves gap",
  "sleeves gap",

  sleeveWearableRight("316_MarineJacket"),
  sleeveWearableRight("317_ThaaveSuit"),
  sleeveWearableRight("318_TrackSuit"),

  // forge wearables
  sleeveWearableRight("350_PixelcraftTee"),
  sleeveWearableRight("362_FAKEShirt"),
  sleeveWearableRight("366_HeavenlyRobes"),

  sleeveWearableRight("372_PartyDress"),
  sleeveWearableRight("373_Overalls"),
  sleeveWearableRight("383_SandboxHoodie"),
];

export const wearablesBackSleeveSvgs = [
  // '0_VoidRight',
  // '1_CamoHatRight',
  // '2_CamoPantsRight', // body but doesn't have sleeves
  // '3_MK2GrenadeRight',
  // '4_SnowCamoHatRight',
  // "5_SnowCamoPantsRight", // body but no sleeves
  // '6_M67GrenadeRight',
  // '7_MarineCapRight',
  sleeveWearableRight("8_MarineJacket"), // sleeveWearableRight("8_MarineJacket"),
  // '9_WalkieTalkie',
  // '10_LinkWhiteHatRight',
  sleeveWearableRight("11_MessDress"), // sleeveWearableRight("11_MessDress"),
  // '12_LinkBubblyRight',
  // '13_SergeyBeardRight',
  // '14_SergeyEyesRight',
  sleeveWearableRight("15_RedPlaid"), // sleeveWearableRight("15_RedPlaid"),
  sleeveWearableRight("16_BluePlaid"), //  sleeveWearableRight("16_BluePlaid"),
  // '17_LinkCubeRight',
  // '18_AaveHeroMaskRight',
  sleeveWearableRight("19_AaveHeroShirt"), // sleeveWearableRight("19_AaveHeroShirt"),
  // '20_AavePlushRight',
  // '21_CaptainAaveMaskRight',
  sleeveWearableRight("22_CaptainAaveSuit"), // sleeveWearableRight("22_CaptainAaveSuit"),
  // '23_CaptainAaveShieldRight',
  // '24_ThaaveHelmetRight',
  sleeveWearableRight("25_ThaaveSuit"),
  // '26_ThaaveHammerRight',
  // '27_MarcHairRight',
  sleeveWearableRight("28_MarcOutfit"), // sleeveWearableRight("28_MarcOutfit"),
  // '29_REKTSignRight',
  // '30_JordanHairRight',
  sleeveWearableRight("31_JordanSuit"), // sleeveWearableRight("31_JordanSuit"),
  // '32_AaveFlagRight',
  // '33_StaniHairRight',
  // '34_StaniVestRight', // sleeveWearableRight("34_StaniVest"),
  // '35_AaveBoatRight',
  // '36_ETHMaxiGlassesRight',
  sleeveWearableRight("37_ETHTShirt"),
  // '38_32ETHCoinRight',
  // '39_FoxyMaskRight',
  // '40_FoxyTailRight', // body but no sleeves
  // '41_TrezorWalletRight',
  // '42_NogaraEagleMaskRight',
  sleeveWearableRight("43_NogaraEagleArmor"),
  // '44_DAOEggRight',
  // '45_ApeMaskRight',
  sleeveWearableRight("46_HalfRektShirt"),
  // '47_WaifuPillowRight',
  // '48_XibotMohawkRight',
  // '49_CoderdanShadesRight',
  sleeveWearableRight("50_GldnXrossRobe"),
  // '51_MudgenDiamondRight',
  // '52_GalaxyBrainRight',
  // '53_AllSeeingEyesRight',
  sleeveWearableRight("54_LlamacornShirt"),
  // '55_AagentHeadsetRight',
  sleeveWearableRight("56_AagentShirt"),
  // '57_AagentShadesRight',
  // '58_AagentPistolRight',
  // '59_AagentFedoraHatRight',
  // '60_WizardHatRight',
  // '61_WizardHatLegendaryRight',
  // '62_WizardHatMythicalRight',
  // '63_WizardHatGodlikeRight',
  // '64_WizardStaffRight',
  // '65_WizardStaffLegendaryRight',
  // '66_FutureWizardVisorRight',
  // '67_FarmerStrawHatRight',
  // '68_FarmerJeansRight', // Body but no sleeves
  // '69_FarmerPitchforkRight',
  // '70_FarmerHandsawRight',
  // '71_SantagotchiHatRight',
  // '72_JaayHairpieceRight',
  // '73_JaayGlassesRight',
  sleeveWearableRight("74_JaayHaoSuit"),
  // '75_OKexSignRight',
  // '76_BigGHSTTokenRight',
  // '77_BitcoinBeanieRight',
  // '78_SkaterJeansRight', // Body but no sleeves
  // '79_SkateboardRight',
  // '80_SushiHeadbandRight',
  // '81_SushiRobeRight', // Body but not sleeves
  // '82_SushiRollRight',
  // '83_SushiKnifeRight',
  // '84_GentlemanHatRight',
  sleeveWearableRight("85_GentlemanSuit"),
  // '86_GentlemanMonocleRight',
  // '87_MinerHelmetRight',
  // '88_MinerJeansRight', // Body but no sleeves
  // '89_MinerPickaxeRight',
  // '90_PajamaHatRight',
  sleeveWearableRight("91_PajamaPants"),
  // '92_BedtimeMilkRight',
  // '93_FluffyBlanketRight',
  // '94_RunnerSweatbandRight',
  // '95_RunnerShortsRight', // Body but no sleeves
  // '96_WaterBottleRight',
  // '97_PillboxHatRight',
  // '98_LadySkirtRight', // Body but no sleeves
  // '99_LadyParasolRight',
  // '100_LadyClutchRight',
  // '101_WitchHatRight',
  sleeveWearableRight("102_WitchCape"),
  // '103_WitchWandRight',
  // '104_PortalMageHelmetRight',
  sleeveWearableRight("105_PortalMageArmor"),
  // '106_PortalMageAxeRight',
  // '107_PortalMageBlackAxeRight',
  // '108_RastaDredsRight',
  sleeveWearableRight("109_RastaShirt"),
  // '110_JamaicanFlagRight',
  // '111_HazmatHoodRight',
  sleeveWearableRight("112_HazmatSuit"),
  // '113_UraniumRodRight',
  sleeveWearableRight("114_RedHawaiianShirt"),
  sleeveWearableRight("115_BlueHawaiianShirt"),
  // '116_CoconutRight',
  // '117_DealWithItShadesRight',
  // '118_WaterJugRight',
  // '119_BabyBottleRight',
  // '120_MartiniRight',
  // '121_WineBottleRight',
  // '122_MilkshakeRight',
  // '123_AppleJuiceRight',
  // '124_BeerHelmetRight',
  sleeveWearableRight("125_TrackSuit"),
  // '126_KinshipPotionRight',
  // '127_GreaterKinshipPotionRight',
  // '128_XPPotionRight',
  // '129_GreaterXPPotionRight',
  // '130_FireballRight',
  // '131_DragonHornsRight',
  // '132_DragonWingsRight',
  // '133_PointyHornsRight', // Body wearable but not sleeves
  // '134_L2SignRight',
  sleeveWearableRight("135_PolygonShirt"),
  // '136_PolygonCapRight',
  // '137_VoteSignRight',
  sleeveWearableRight("138_SnapshotShirt"),
  // '139_SnapshotHatRight',
  // '140_ElfEarsRight',
  // '141_GemstoneRingRight',
  // '142_PrincessTiaraRight',
  // '143_GoldNecklaceRight',
  // '144_PrincessHairRight',
  // '145_GodliLocksRight',
  // '146_ImperialMoustacheRight',
  // '147_TinyCrownRight',
  // '148_RoyalScepterRight',
  // '149_RoyalCrownRight',
  sleeveWearableRight("150_RoyalRobes"),
  // '151_CommonRoflRight',
  // '152_UncommonRoflRight',
  // '153_RareRoflRight',
  // '154_LegendaryRoflRight',
  // '155_MythicalRoflRight',
  // '156_GodlikeRoflRight',
  // '157_LilPumpGoateeRight',
  // '158_LilPumpDrinkRight',
  // '159_LilPumpShadesRight',
  sleeveWearableRight("160_LilPumpThreads"),
  // '161_LilPumpDreadsRight',
  sleeveWearableRight("162_MiamiShirt"),
  // '199_SteampunkGlassesRight',
  // '200_SteampunkRight',
  // '201_SteampunkGlove',
  // '202_CyberpunkVRRight',
  sleeveWearableRight("203_GamerJacket"),
  // '204_CyberpunkControlRight',
  // '205_CoffeeCupRight',
  // '206_AagentRadioRight',
  // sleeveWearableRight('207_BikerJacket'),
  sleeveWearableRight("213_H4xx0rShirt"),
  sleeveWearableRight("220_PunkShirt"),
  sleeveWearableRight("222_PirateCoat"),
  sleeveWearableRight("231_ComfyPoncho"),
  // sleeveWearableRight('232_PonchoHoodie'),
  sleeveWearableRight("234_ShaamanPoncho"),
  sleeveWearableRight("241_WGMIShirt"),
  sleeveWearableRight("244_VNeckShirt"),
  sleeveWearableRight("248_UpOnlyShirt"),
  sleeveWearableRight("250_CoinGeckoTee"),
  sleeveWearableRight("253_AastronautSuit"),
  sleeveWearableRight("256_LilBubbleSpaceSuit"),
  sleeveWearableRight("258_Hanfu"),
  sleeveWearableRight("293_LeatherTunic"),
  sleeveWearableRight("297_AnimalSkins"),
  sleeveWearableRight("303_Kimono"),
  sleeveWearableRight("307_FairyWings"),
  sleeveWearableRight("310_PlateArmor"),
  sleeveWearableRight("314_YoroiArmor"),

  sleeveWearableRight("316_MarineJacket"),
  sleeveWearableRight("317_ThaaveSuit"),
  sleeveWearableRight("318_TrackSuit"),
  // forge wearables
  sleeveWearableRight("350_PixelcraftTee"),
  sleeveWearableRight("362_FAKEShirt"),
  sleeveWearableRight("366_HeavenlyRobes"),
  //forge wearables2
  sleeveWearableRight("372_PartyDress"),
  sleeveWearableRight("373_Overalls"),
  sleeveWearableRight("383_SandboxHoodie"),
];

function stripSvg(svg: string) {
  // removes svg tag
  if (svg.includes("viewBox")) {
    svg = svg.slice(svg.indexOf(">") + 1);
    svg = svg.replace("</svg>", "");
  }
  return svg;
}

function readSvg(name: string) {
  return stripSvg(fs.readFileSync(`./svgs/svgItems/${name}.svg`, "utf8"));
}

function wearable(name: string) {
  const svg = readSvg(name);
  // svg = `<g>${svg}</g>`
  return svg;
}

function bodyWearable(name: string) {
  let svg = readSvg(name);
  const back = readSvg(`${name}Back`);
  const backLeftSleevesUp =
    '<g class="gotchi-sleeves gotchi-sleeves-left gotchi-sleeves-up">' +
    readSvg(`${name}BackLeftUp`) +
    "</g>";
  const backLeft = readSvg(`${name}BackLeft`);
  const backRightSleevesUp =
    '<g class="gotchi-sleeves gotchi-sleeves-right gotchi-sleeves-up">' +
    readSvg(`${name}BackRightUp`) +
    "</g>";
  const backRight = readSvg(`${name}BackRight`);

  svg =
    "<g>" +
    back +
    backLeftSleevesUp +
    backLeft +
    backRightSleevesUp +
    backRight +
    "</g>";
  return svg;
}

function bodyWearableLeft(name: string) {
  let svg;
  const left = readSvg(`${name}SideLeft`);
  svg = "<g>" + left + "</g>";
  return svg;
}

function bodyWearableRight(name: string) {
  let svg;
  const right = readSvg(`${name}SideRight`);
  svg = "<g>" + right + "</g>";
  return svg;
}

function sleeveWearableLeft(name: string) {
  let svg;
  const leftSleevesUp =
    '<g class="gotchi-sleeves gotchi-sleeves-left gotchi-sleeves-up">' +
    readSvg(`${name}SideLeftUp`) +
    "</g>";
  const leftSleevesDown =
    '<g class="gotchi-sleeves gotchi-sleeves-left gotchi-sleeves-down">' +
    readSvg(`${name}SideLeftDown`) +
    "</g>";
  svg = "<g>" + leftSleevesUp + leftSleevesDown + "</g>";
  return svg;
}

function sleeveWearableRight(name: string) {
  let svg;
  const rightSleevesUp =
    '<g class="gotchi-sleeves gotchi-sleeves-right gotchi-sleeves-up">' +
    readSvg(`${name}SideRightUp`) +
    "</g>";
  const rightSleevesDown =
    '<g class="gotchi-sleeves gotchi-sleeves-right gotchi-sleeves-down">' +
    readSvg(`${name}SideRightDown`) +
    "</g>";
  svg = "<g>" + rightSleevesUp + rightSleevesDown + "</g>";
  return svg;
}

function EmptySvg() {
  return stripSvg(fs.readFileSync(`./svgs/svgItems/EmptyFile.svg`, "utf8"));
}
