const fs = require('fs')

const wearablesRightSvgs = [
  wearable('0_VoidRight'),
  wearable('1_CamoHatRight'),
  wearable('2_CamoPantsRight'), // body but doesn't have sleeves
  wearable('3_MK2GrenadeRight'),
  wearable('4_SnowCamoHatRight'),
  wearable('5_SnowCamoPantsRight'), // body but no sleeves
  wearable('6_M67GrenadeRight'),
  wearable('7_MarineCapRight'),
  bodyWearable('8_MarineJacketRight'), // bodyWearable("8_MarineJacket"),
  wearable('9_WalkieTalkieRight'),
  wearable('10_LinkWhiteHatRight'),
  bodyWearable('11_MessDressRight'), // bodyWearable("11_MessDress"),
  wearable('12_LinkBubblyRight'),
  wearable('13_SergeyBeardRight'),
  wearable('14_SergeyEyesRight'),
  bodyWearable('15_RedPlaidRight'), // bodyWearable("15_RedPlaid"),
  bodyWearable('16_BluePlaidRight'), //  bodyWearable("16_BluePlaid"),
  wearable('17_LinkCubeRight'),
  wearable('18_AaveHeroMaskRight'),
  bodyWearable('19_AaveHeroShirtRight'), // bodyWearable("19_AaveHeroShirt"),
  wearable('20_AavePlushRight'),
  wearable('21_CaptainAaveMaskRight'),
  bodyWearable('22_CaptainAaveSuitRight'), // bodyWearable("22_CaptainAaveSuit"),
  wearable('23_CaptainAaveShieldRight'),
  wearable('24_ThaaveHelmetRight'),
  wearable('25_ThaaveSuitRight'), // bodyWearable("25_ThaaveSuit"),
  wearable('26_ThaaveHammerRight'),
  wearable('27_MarcHairRight'),
  bodyWearable('28_MarcOutfitRight'), // bodyWearable("28_MarcOutfit"),
  wearable('29_REKTSignRight'),
  wearable('30_JordanHairRight'),
  bodyWearable('31_JordanSuitRight'), // bodyWearable("31_JordanSuit"),
  wearable('32_AaveFlagRight'),
  wearable('33_StaniHairRight'),
  wearable('34_StaniVestRight'), // bodyWearable("34_StaniVest"),
  wearable('35_AaveBoatRight'),
  wearable('36_ETHMaxiGlassesRight'),
  bodyWearable('37_ETHTShirtRight'),
  wearable('38_32ETHCoinRight'),
  wearable('39_FoxyMaskRight'),
  wearable('40_FoxyTailRight'), // body but no sleeves
  wearable('41_TrezorWalletRight'),
  wearable('42_NogaraEagleMaskRight'),
  bodyWearable('43_NogaraEagleArmorRight'),
  wearable('44_DAOEggRight'),
  wearable('45_ApeMaskRight'),
  bodyWearable('46_HalfRektShirtRight'),
  wearable('47_WaifuPillowRight'),
  wearable('48_XibotMohawkRight'),
  wearable('49_CoderdanShadesRight'),
  bodyWearable('50_GldnXrossRobeRight'),
  wearable('51_MudgenDiamondRight'),
  wearable('52_GalaxyBrainRight'),
  wearable('53_AllSeeingEyesRight'),
  bodyWearable('54_LlamacornShirtRight'),
  wearable('55_AagentHeadsetRight'),
  bodyWearable('56_AagentShirtRight'),
  wearable('57_AagentShadesRight'),
  wearable('58_AagentPistolRight'),
  wearable('59_AagentFedoraHatRight'),
  wearable('60_WizardHatRight'),
  wearable('61_WizardHatLegendaryRight'),
  wearable('62_WizardHatMythicalRight'),
  wearable('63_WizardHatGodlikeRight'),
  wearable('64_WizardStaffRight'),
  wearable('65_WizardStaffLegendaryRight'),
  wearable('66_FutureWizardVisorRight'),
  wearable('67_FarmerStrawHatRight'),
  wearable('68_FarmerJeansRight'), // Body but no sleeves
  wearable('69_FarmerPitchforkRight'),
  wearable('70_FarmerHandsawRight'),
  wearable('71_SantagotchiHatRight'),
  wearable('72_JaayHairpieceRight'),
  wearable('73_JaayGlassesRight'),
  bodyWearable('74_JaayHaoSuitRight'),
  wearable('75_OKexSignRight'),
  wearable('76_BigGHSTTokenRight'),
  wearable('77_BitcoinBeanieRight'),
  wearable('78_SkaterJeansRight'), // Body but no sleeves
  wearable('79_SkateboardRight'),
  wearable('80_SushiHeadbandRight'),
  wearable('81_SushiRobeRight'), // Body but not sleeves
  wearable('82_SushiRollRight'),
  wearable('83_SushiKnifeRight'),
  wearable('84_GentlemanHatRight'),
  bodyWearable('85_GentlemanSuitRight'),
  wearable('86_GentlemanMonocleRight'),
  wearable('87_MinerHelmetRight'),
  wearable('88_MinerJeansRight'), // Body but no sleeves
  wearable('89_MinerPickaxeRight'),
  wearable('90_PajamaHatRight'),
  bodyWearable('91_PajamaPantsRight'),
  wearable('92_BedtimeMilkRight'),
  wearable('93_FluffyBlanketRight'),
  wearable('94_RunnerSweatbandRight'),
  wearable('95_RunnerShortsRight'), // Body but no sleeves
  wearable('96_WaterBottleRight'),
  wearable('97_PillboxHatRight'),
  wearable('98_LadySkirtRight'), // Body but no sleeves
  wearable('99_LadyParasolRight'),
  wearable('100_LadyClutchRight'),
  wearable('101_WitchHatRight'),
  bodyWearable('102_WitchCapeRight'),
  wearable('103_WitchWandRight'),
  wearable('104_PortalMageHelmetRight'),
  bodyWearable('105_PortalMageArmorRight'),
  wearable('106_PortalMageAxeRight'),
  wearable('107_PortalMageBlackAxeRight'),
  wearable('108_RastaDredsRight'),
  bodyWearable('109_RastaShirtRight'),
  wearable('110_JamaicanFlagRight'),
  wearable('111_HazmatHoodRight'),
  bodyWearable('112_HazmatSuitRight'),
  wearable('113_UraniumRodRight'),
  bodyWearable('114_RedHawaiianShirtRight'),
  bodyWearable('115_BlueHawaiianShirtRight'),
  wearable('116_CoconutRight'),
  wearable('117_DealWithItShadesRight'),
  wearable('118_WaterJugRight'),
  wearable('119_BabyBottleRight'),
  wearable('120_MartiniRight'),
  wearable('121_WineBottleRight'),
  wearable('122_MilkshakeRight'),
  wearable('123_AppleJuiceRight'),
  wearable('124_BeerHelmetRight'),
  wearable('125_TrackSuitRight'),
  wearable('126_KinshipPotionRight'),
  wearable('127_GreaterKinshipPotionRight'),
  wearable('128_XPPotionRight'),
  wearable('129_GreaterXPPotionRight'),
  wearable('130_FireballRight'),
  wearable('131_DragonHornsRight'),
  wearable('132_DragonWingsRight'),
  wearable('133_PointyHornsRight'), // Body wearable but not sleeves
  wearable('134_L2SignRight'),
  bodyWearable('135_PolygonShirtRight'),
  wearable('136_PolygonCapRight'),
  wearable('137_VoteSignRight'),
  bodyWearable('138_SnapshotShirtRight'),
  wearable('139_SnapshotHatRight'),
  wearable('140_ElfEarsRight'),
  wearable('141_GemstoneRingRight'),
  wearable('142_PrincessTiaraRight'),
  wearable('143_GoldNecklaceRight'),
  wearable('144_PrincessHairRight'),
  wearable('145_GodliLocksRight'),
  wearable('146_ImperialMoustacheRight'),
  wearable('147_TinyCrownRight'),
  wearable('148_RoyalScepterRight'),
  wearable('149_RoyalCrownRight'),
  bodyWearable('150_RoyalRobesRight'),
  wearable('151_CommonRoflRight'),
  wearable('152_UncommonRoflRight'),
  wearable('153_RareRoflRight'),
  wearable('154_LegendaryRoflRight'),
  wearable('155_MythicalRoflRight'),
  wearable('156_GodlikeRoflRight'),
  wearable('157_LilPumpGoateeRight'),
  wearable('158_LilPumpDrinkRight'),
  wearable('159_LilPumpShadesRight'),
  bodyWearable('160_LilPumpThreadsRight'),
  wearable('161_LilPumpDreadsRight'),
  bodyWearable('162_MiamiShirtRight')

]

const wearablesBackSvgs = [
  wearable('0_VoidRight'),
  wearable('1_CamoHatRight'),
  wearable('2_CamoPantsRight'), // body but doesn't have sleeves
  wearable('3_MK2GrenadeRight'),
  wearable('4_SnowCamoHatBack'),
  wearable('5_SnowCamoPantsBack'), // body but no sleeves
  wearable('6_M67GrenadeBack'),
  wearable('7_MarineCapBack'),
  bodyWearable('8_MarineJacketBack'), // bodyWearable("8_MarineJacket"),
  wearable('9_WalkieTalkieBack'),
  wearable('10_LinkWhiteHatBack'),
  bodyWearable('11_MessDressBack'), // bodyWearable("11_MessDress"),
  wearable('12_LinkBubblyBack'),
  wearable('13_SergeyBeardBack'),
  wearable('14_SergeyEyesBack'),
  bodyWearable('15_RedPlaidBack'), // bodyWearable("15_RedPlaid"),
  bodyWearable('16_BluePlaidBack'), //  bodyWearable("16_BluePlaid"),
  wearable('17_LinkCubeBack'),
  wearable('18_AaveHeroMaskBack'),
  bodyWearable('19_AaveHeroShirtBack'), // bodyWearable("19_AaveHeroShirt"),
  wearable('20_AavePlushBack'),
  wearable('21_CaptainAaveMaskBack'),
  bodyWearable('22_CaptainAaveSuitBack'), // bodyWearable("22_CaptainAaveSuit"),
  wearable('23_CaptainAaveShieldBack'),
  wearable('24_ThaaveHelmetBack'),
  wearable('25_ThaaveSuitBack'), // bodyWearable("25_ThaaveSuit"),
  wearable('26_ThaaveHammerBack'),
  wearable('27_MarcHairBack'),
  bodyWearable('28_MarcOutfitBack'), // bodyWearable("28_MarcOutfit"),
  wearable('29_REKTSignBack'),
  wearable('30_JordanHairBack'),
  bodyWearable('31_JordanSuitBack'), // bodyWearable("31_JordanSuit"),
  wearable('32_AaveFlagBack'),
  wearable('33_StaniHairBack'),
  wearable('34_StaniVestBack'), // bodyWearable("34_StaniVest"),
  wearable('35_AaveBoatBack'),
  wearable('36_ETHMaxiGlassesBack'),
  bodyWearable('37_ETHTShirtBack'),
  wearable('38_32ETHCoinBack'),
  wearable('39_FoxyMaskBack'),
  wearable('40_FoxyTailBack'), // body but no sleeves
  wearable('41_TrezorWalletBack'),
  wearable('42_NogaraEagleMaskBack'),
  bodyWearable('43_NogaraEagleArmorBack'),
  wearable('44_DAOEggBack'),
  wearable('45_ApeMaskBack'),
  bodyWearable('46_HalfRektShirtBack'),
  wearable('47_WaifuPillowBack'),
  wearable('48_XibotMohawkBack'),
  wearable('49_CoderdanShadesBack'),
  bodyWearable('50_GldnXrossRobeBack'),
  wearable('51_MudgenDiamondBack'),
  wearable('52_GalaxyBrainBack'),
  wearable('53_AllSeeingEyesBack'),
  bodyWearable('54_LlamacornShirtBack'),
  wearable('55_AagentHeadsetBack'),
  bodyWearable('56_AagentShirtBack'),
  wearable('57_AagentShadesBack'),
  wearable('58_AagentPistolBack'),
  wearable('59_AagentFedoraHatBack'),
  wearable('60_WizardHatBack'),
  wearable('61_WizardHatLegendaryBack'),
  wearable('62_WizardHatMythicalBack'),
  wearable('63_WizardHatGodlikeBack'),
  wearable('64_WizardStaffBack'),
  wearable('65_WizardStaffLegendaryBack'),
  wearable('66_FutureWizardVisorBack'),
  wearable('67_FarmerStrawHatBack'),
  wearable('68_FarmerJeansBack'), // Body but no sleeves
  wearable('69_FarmerPitchforkBack'),
  wearable('70_FarmerHandsawBack'),
  wearable('71_SantagotchiHatBack'),
  wearable('72_JaayHairpieceBack'),
  wearable('73_JaayGlassesBack'),
  bodyWearable('74_JaayHaoSuitBack'),
  wearable('75_OKexSignBack'),
  wearable('76_BigGHSTTokenBack'),
  wearable('77_BitcoinBeanieBack'),
  wearable('78_SkaterJeansBack'), // Body but no sleeves
  wearable('79_SkateboardBack'),
  wearable('80_SushiHeadbandBack'),
  wearable('81_SushiRobeBack'), // Body but not sleeves
  wearable('82_SushiRollBack'),
  wearable('83_SushiKnifeBack'),
  wearable('84_GentlemanHatBack'),
  bodyWearable('85_GentlemanSuitBack'),
  wearable('86_GentlemanMonocleBack'),
  wearable('87_MinerHelmetBack'),
  wearable('88_MinerJeansBack'), // Body but no sleeves
  wearable('89_MinerPickaxeBack'),
  wearable('90_PajamaHatBack'),
  bodyWearable('91_PajamaPantsBack'),
  wearable('92_BedtimeMilkBack'),
  wearable('93_FluffyBlanketBack'),
  wearable('94_RunnerSweatbandBack'),
  wearable('95_RunnerShortsBack'), // Body but no sleeves
  wearable('96_WaterBottleBack'),
  wearable('97_PillboxHatBack'),
  wearable('98_LadySkirtBack'), // Body but no sleeves
  wearable('99_LadyParasolBack'),
  wearable('100_LadyClutchBack'),
  wearable('101_WitchHatBack'),
  bodyWearable('102_WitchCapeBack'),
  wearable('103_WitchWandBack'),
  wearable('104_PortalMageHelmetBack'),
  bodyWearable('105_PortalMageArmorBack'),
  wearable('106_PortalMageAxeBack'),
  wearable('107_PortalMageBlackAxeBack'),
  wearable('108_RastaDredsBack'),
  bodyWearable('109_RastaShirtBack'),
  wearable('110_JamaicanFlagBack'),
  wearable('111_HazmatHoodBack'),
  bodyWearable('112_HazmatSuitBack'),
  wearable('113_UraniumRodBack'),
  bodyWearable('114_RedHawaiianShirtBack'),
  bodyWearable('115_BlueHawaiianShirtBack'),
  wearable('116_CoconutBack'),
  wearable('117_DealWithItShadesBack'),
  wearable('118_WaterJugBack'),
  wearable('119_BabyBottleBack'),
  wearable('120_MartiniBack'),
  wearable('121_WineBottleBack'),
  wearable('122_MilkshakeBack'),
  wearable('123_AppleJuiceBack'),
  wearable('124_BeerHelmetBack'),
  wearable('125_TrackSuitBack'),
  wearable('126_KinshipPotionBack'),
  wearable('127_GreaterKinshipPotionBack'),
  wearable('128_XPPotionBack'),
  wearable('129_GreaterXPPotionBack'),
  wearable('130_FireballBack'),
  wearable('131_DragonHornsBack'),
  wearable('132_DragonWingsBack'),
  wearable('133_PointyHornsBack'), // Body wearable but not sleeves
  wearable('134_L2SignBack'),
  bodyWearable('135_PolygonShirtBack'),
  wearable('136_PolygonCapBack'),
  wearable('137_VoteSignBack'),
  bodyWearable('138_SnapshotShirtBack'),
  wearable('139_SnapshotHatBack'),
  wearable('140_ElfEarsBack'),
  wearable('141_GemstoneRingBack'),
  wearable('142_PrincessTiaraBack'),
  wearable('143_GoldNecklaceBack'),
  wearable('144_PrincessHairBack'),
  wearable('145_GodliLocksBack'),
  wearable('146_ImperialMoustacheBack'),
  wearable('147_TinyCrownBack'),
  wearable('148_RoyalScepterBack'),
  wearable('149_RoyalCrownBack'),
  bodyWearable('150_RoyalRobesBack'),
  wearable('151_CommonRoflBack'),
  wearable('152_UncommonRoflBack'),
  wearable('153_RareRoflBack'),
  wearable('154_LegendaryRoflBack'),
  wearable('155_MythicalRoflBack'),
  wearable('156_GodlikeRoflBack'),
  wearable('157_LilPumpGoateeBack'),
  wearable('158_LilPumpDrinkBack'),
  wearable('159_LilPumpShadesBack'),
  bodyWearable('160_LilPumpThreadsBack'),
  wearable('161_LilPumpDreadsBack'),
  bodyWearable('162_MiamiShirtBack')

]

const wearablesLeftSvgs = [
  wearable('0_VoidLeft'),
  wearable('1_CamoHatLeft'),
  wearable('2_CamoPantsLeft'), // body but doesn't have sleeves
  wearable('3_MK2GrenadeLeft'),
  wearable('4_SnowCamoHatLeft'),
  wearable('5_SnowCamoPantsLeft'), // body but no sleeves
  wearable('6_M67GrenadeLeft'),
  wearable('7_MarineCapLeft'),
  bodyWearable('8_MarineJacketLeft'), // bodyWearable("8_MarineJacket"),
  wearable('9_WalkieTalkieLeft'),
  wearable('10_LinkWhiteHatLeft'),
  bodyWearable('11_MessDressLeft'), // bodyWearable("11_MessDress"),
  wearable('12_LinkBubblyLeft'),
  wearable('13_SergeyBeardLeft'),
  wearable('14_SergeyEyesLeft'),
  bodyWearable('15_RedPlaidLeft'), // bodyWearable("15_RedPlaid"),
  bodyWearable('16_BluePlaidLeft'), //  bodyWearable("16_BluePlaid"),
  wearable('17_LinkCubeLeft'),
  wearable('18_AaveHeroMaskLeft'),
  bodyWearable('19_AaveHeroShirtLeft'), // bodyWearable("19_AaveHeroShirt"),
  wearable('20_AavePlushLeft'),
  wearable('21_CaptainAaveMaskLeft'),
  bodyWearable('22_CaptainAaveSuitLeft'), // bodyWearable("22_CaptainAaveSuit"),
  wearable('23_CaptainAaveShieldLeft'),
  wearable('24_ThaaveHelmetLeft'),
  wearable('25_ThaaveSuitLeft'), // bodyWearable("25_ThaaveSuit"),
  wearable('26_ThaaveHammerLeft'),
  wearable('27_MarcHairLeft'),
  bodyWearable('28_MarcOutfitLeft'), // bodyWearable("28_MarcOutfit"),
  wearable('29_REKTSignLeft'),
  wearable('30_JordanHairLeft'),
  bodyWearable('31_JordanSuitLeft'), // bodyWearable("31_JordanSuit"),
  wearable('32_AaveFlagLeft'),
  wearable('33_StaniHairLeft'),
  wearable('34_StaniVestLeft'), // bodyWearable("34_StaniVest"),
  wearable('35_AaveBoatLeft'),
  wearable('36_ETHMaxiGlassesLeft'),
  bodyWearable('37_ETHTShirtLeft'),
  wearable('38_32ETHCoinLeft'),
  wearable('39_FoxyMaskLeft'),
  wearable('40_FoxyTailLeft'), // body but no sleeves
  wearable('41_TrezorWalletLeft'),
  wearable('42_NogaraEagleMaskLeft'),
  bodyWearable('43_NogaraEagleArmorLeft'),
  wearable('44_DAOEggLeft'),
  wearable('45_ApeMaskLeft'),
  bodyWearable('46_HalfRektShirtLeft'),
  wearable('47_WaifuPillowLeft'),
  wearable('48_XibotMohawkLeft'),
  wearable('49_CoderdanShadesLeft'),
  bodyWearable('50_GldnXrossRobeLeft'),
  wearable('51_MudgenDiamondLeft'),
  wearable('52_GalaxyBrainLeft'),
  wearable('53_AllSeeingEyesLeft'),
  bodyWearable('54_LlamacornShirtLeft'),
  wearable('55_AagentHeadsetLeft'),
  bodyWearable('56_AagentShirtLeft'),
  wearable('57_AagentShadesLeft'),
  wearable('58_AagentPistolLeft'),
  wearable('59_AagentFedoraHatLeft'),
  wearable('60_WizardHatLeft'),
  wearable('61_WizardHatLegendaryLeft'),
  wearable('62_WizardHatMythicalLeft'),
  wearable('63_WizardHatGodlikeLeft'),
  wearable('64_WizardStaffLeft'),
  wearable('65_WizardStaffLegendaryLeft'),
  wearable('66_FutureWizardVisorLeft'),
  wearable('67_FarmerStrawHatLeft'),
  wearable('68_FarmerJeansLeft'), // Body but no sleeves
  wearable('69_FarmerPitchforkLeft'),
  wearable('70_FarmerHandsawLeft'),
  wearable('71_SantagotchiHatLeft'),
  wearable('72_JaayHairpieceLeft'),
  wearable('73_JaayGlassesLeft'),
  bodyWearable('74_JaayHaoSuitLeft'),
  wearable('75_OKexSignLeft'),
  wearable('76_BigGHSTTokenLeft'),
  wearable('77_BitcoinBeanieLeft'),
  wearable('78_SkaterJeansLeft'), // Body but no sleeves
  wearable('79_SkateboardLeft'),
  wearable('80_SushiHeadbandLeft'),
  wearable('81_SushiRobeLeft'), // Body but not sleeves
  wearable('82_SushiRollLeft'),
  wearable('83_SushiKnifeLeft'),
  wearable('84_GentlemanHatLeft'),
  bodyWearable('85_GentlemanSuitLeft'),
  wearable('86_GentlemanMonocleLeft'),
  wearable('87_MinerHelmetLeft'),
  wearable('88_MinerJeansLeft'), // Body but no sleeves
  wearable('89_MinerPickaxeLeft'),
  wearable('90_PajamaHatLeft'),
  bodyWearable('91_PajamaPantsLeft'),
  wearable('92_BedtimeMilkLeft'),
  wearable('93_FluffyBlanketLeft'),
  wearable('94_RunnerSweatbandLeft'),
  wearable('95_RunnerShortsLeft'), // Body but no sleeves
  wearable('96_WaterBottleLeft'),
  wearable('97_PillboxHatLeft'),
  wearable('98_LadySkirtLeft'), // Body but no sleeves
  wearable('99_LadyParasolLeft'),
  wearable('100_LadyClutchLeft'),
  wearable('101_WitchHatLeft'),
  bodyWearable('102_WitchCapeLeft'),
  wearable('103_WitchWandLeft'),
  wearable('104_PortalMageHelmetLeft'),
  bodyWearable('105_PortalMageArmorLeft'),
  wearable('106_PortalMageAxeLeft'),
  wearable('107_PortalMageBlackAxeLeft'),
  wearable('108_RastaDredsLeft'),
  bodyWearable('109_RastaShirtLeft'),
  wearable('110_JamaicanFlagLeft'),
  wearable('111_HazmatHoodLeft'),
  bodyWearable('112_HazmatSuitLeft'),
  wearable('113_UraniumRodLeft'),
  bodyWearable('114_RedHawaiianShirtLeft'),
  bodyWearable('115_BlueHawaiianShirtLeft'),
  wearable('116_CoconutLeft'),
  wearable('117_DealWithItShadesLeft'),
  wearable('118_WaterJugLeft'),
  wearable('119_BabyBottleLeft'),
  wearable('120_MartiniLeft'),
  wearable('121_WineBottleLeft'),
  wearable('122_MilkshakeLeft'),
  wearable('123_AppleJuiceLeft'),
  wearable('124_BeerHelmetLeft'),
  wearable('125_TrackSuitLeft'),
  wearable('126_KinshipPotionLeft'),
  wearable('127_GreaterKinshipPotionLeft'),
  wearable('128_XPPotionLeft'),
  wearable('129_GreaterXPPotionLeft'),
  wearable('130_FireballLeft'),
  wearable('131_DragonHornsLeft'),
  wearable('132_DragonWingsLeft'),
  wearable('133_PointyHornsLeft'), // Body wearable but not sleeves
  wearable('134_L2SignLeft'),
  bodyWearable('135_PolygonShirtLeft'),
  wearable('136_PolygonCapLeft'),
  wearable('137_VoteSignLeft'),
  bodyWearable('138_SnapshotShirtLeft'),
  wearable('139_SnapshotHatLeft'),
  wearable('140_ElfEarsLeft'),
  wearable('141_GemstoneRingLeft'),
  wearable('142_PrincessTiaraLeft'),
  wearable('143_GoldNecklaceLeft'),
  wearable('144_PrincessHairLeft'),
  wearable('145_GodliLocksLeft'),
  wearable('146_ImperialMoustacheLeft'),
  wearable('147_TinyCrownLeft'),
  wearable('148_RoyalScepterLeft'),
  wearable('149_RoyalCrownLeft'),
  bodyWearable('150_RoyalRobesLeft'),
  wearable('151_CommonRoflLeft'),
  wearable('152_UncommonRoflLeft'),
  wearable('153_RareRoflLeft'),
  wearable('154_LegendaryRoflLeft'),
  wearable('155_MythicalRoflLeft'),
  wearable('156_GodlikeRoflLeft'),
  wearable('157_LilPumpGoateeLeft'),
  wearable('158_LilPumpDrinkLeft'),
  wearable('159_LilPumpShadesLeft'),
  bodyWearable('160_LilPumpThreadsLeft'),
  wearable('161_LilPumpDreadsLeft'),
  bodyWearable('162_MiamiShirtLeft')

]

function stripSvg (svg) {
  // removes svg tag
  if (svg.includes('viewBox')) {
    svg = svg.slice(svg.indexOf('>') + 1)
    svg = svg.replace('</svg>', '')
  }
  return svg
}

function readSvg (name) {
  return stripSvg(fs.readFileSync(`./svgs/svgItems/${name}.svg`, 'utf8'))
}

function wearable (name) {
  const svg = readSvg(name)
  // svg = `<g>${svg}</g>`
  return svg
}

function bodyWearable (name) {
  let svg = readSvg(name)
  const leftSleevesUp = '<g class="gotchi-sleeves gotchi-sleeves-left gotchi-sleeves-up">' + readSvg(`${name}LeftUp`) + '</g>'
  const leftSleeves = '<g class="gotchi-sleeves gotchi-sleeves-left gotchi-sleeves-down">' + readSvg(`${name}Left`) + '</g>'
  const rightSleevesUp = '<g class="gotchi-sleeves gotchi-sleeves-right gotchi-sleeves-up">' + readSvg(`${name}RightUp`) + '</g>'
  const rightSleeves = '<g class="gotchi-sleeves gotchi-sleeves-right gotchi-sleeves-down">' + readSvg(`${name}Right`) + '</g>'
  svg = '<g>' + svg + leftSleevesUp + leftSleeves + rightSleevesUp + rightSleeves + '</g>'
  return svg
}

exports.wearablesLeftSvgs = wearablesLeftSvgs
exports.wearablesRightSvgs = wearablesRightSvgs
exports.wearablesBackSvgs = wearablesBackSvgs
