/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { LibAavegotchi, LibAavegotchiInterface } from "../LibAavegotchi";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "kinship",
        type: "uint256",
      },
    ],
    name: "AavegotchiInteract",
    type: "event",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212204d64d186b9a72e45a2eeaae25f0177e7a0f65e8356788808e5fbdf371ee6615d64736f6c63430008010033";

export class LibAavegotchi__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LibAavegotchi> {
    return super.deploy(overrides || {}) as Promise<LibAavegotchi>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibAavegotchi {
    return super.attach(address) as LibAavegotchi;
  }
  connect(signer: Signer): LibAavegotchi__factory {
    return super.connect(signer) as LibAavegotchi__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibAavegotchiInterface {
    return new utils.Interface(_abi) as LibAavegotchiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibAavegotchi {
    return new Contract(address, _abi, signerOrProvider) as LibAavegotchi;
  }
}
