/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AavegotchiGameFacetInterface extends ethers.utils.Interface {
  functions: {
    "aavegotchiLevel(uint256)": FunctionFragment;
    "aavegotchiNameAvailable(string)": FunctionFragment;
    "availableSkillPoints(uint256)": FunctionFragment;
    "baseRarityScore(int16[6])": FunctionFragment;
    "claimAavegotchi(uint256,uint256,uint256)": FunctionFragment;
    "currentHaunt()": FunctionFragment;
    "getNumericTraits(uint256)": FunctionFragment;
    "ghstAddress()": FunctionFragment;
    "interact(uint256[])": FunctionFragment;
    "kinship(uint256)": FunctionFragment;
    "modifiedTraitsAndRarityScore(uint256)": FunctionFragment;
    "portalAavegotchiTraits(uint256)": FunctionFragment;
    "rarityMultiplier(int16[6])": FunctionFragment;
    "revenueShares()": FunctionFragment;
    "setAavegotchiName(uint256,string)": FunctionFragment;
    "spendSkillPoints(uint256,int16[4])": FunctionFragment;
    "xpUntilNextLevel(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "aavegotchiLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "aavegotchiNameAvailable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "availableSkillPoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "baseRarityScore",
    values: [
      [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAavegotchi",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentHaunt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNumericTraits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ghstAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interact",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "kinship",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "modifiedTraitsAndRarityScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "portalAavegotchiTraits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rarityMultiplier",
    values: [
      [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revenueShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAavegotchiName",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "spendSkillPoints",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "xpUntilNextLevel",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "aavegotchiLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aavegotchiNameAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableSkillPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseRarityScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAavegotchi",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentHaunt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumericTraits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ghstAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "interact", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kinship", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "modifiedTraitsAndRarityScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "portalAavegotchiTraits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rarityMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revenueShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAavegotchiName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spendSkillPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xpUntilNextLevel",
    data: BytesLike
  ): Result;

  events: {
    "ClaimAavegotchi(uint256)": EventFragment;
    "LockAavegotchi(uint256,uint256)": EventFragment;
    "SetAavegotchiName(uint256,string,string)": EventFragment;
    "SetBatchId(uint256,uint256[])": EventFragment;
    "SpendSkillpoints(uint256,int16[4])": EventFragment;
    "UnLockAavegotchi(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ClaimAavegotchi"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LockAavegotchi"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAavegotchiName"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetBatchId"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SpendSkillpoints"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnLockAavegotchi"): EventFragment;
}

export type ClaimAavegotchiEvent = TypedEvent<
  [BigNumber] & { _tokenId: BigNumber }
>;

export type LockAavegotchiEvent = TypedEvent<
  [BigNumber, BigNumber] & { _tokenId: BigNumber; _time: BigNumber }
>;

export type SetAavegotchiNameEvent = TypedEvent<
  [BigNumber, string, string] & {
    _tokenId: BigNumber;
    _oldName: string;
    _newName: string;
  }
>;

export type SetBatchIdEvent = TypedEvent<
  [BigNumber, BigNumber[]] & { _batchId: BigNumber; tokenIds: BigNumber[] }
>;

export type SpendSkillpointsEvent = TypedEvent<
  [BigNumber, [number, number, number, number]] & {
    _tokenId: BigNumber;
    _values: [number, number, number, number];
  }
>;

export type UnLockAavegotchiEvent = TypedEvent<
  [BigNumber, BigNumber] & { _tokenId: BigNumber; _time: BigNumber }
>;

export class AavegotchiGameFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AavegotchiGameFacetInterface;

  functions: {
    aavegotchiLevel(
      _experience: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { level_: BigNumber }>;

    aavegotchiNameAvailable(
      _name: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { available_: boolean }>;

    availableSkillPoints(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    baseRarityScore(
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rarityScore_: BigNumber }>;

    claimAavegotchi(
      _tokenId: BigNumberish,
      _option: BigNumberish,
      _stakeAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    currentHaunt(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        [BigNumber, BigNumber, string, number] & {
          hauntMaxSize: BigNumber;
          portalPrice: BigNumber;
          bodyColor: string;
          totalCount: number;
        }
      ] & {
        hauntId_: BigNumber;
        haunt_: [BigNumber, BigNumber, string, number] & {
          hauntMaxSize: BigNumber;
          portalPrice: BigNumber;
          bodyColor: string;
          totalCount: number;
        };
      }
    >;

    getNumericTraits(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [[number, number, number, number, number, number]] & {
        numericTraits_: [number, number, number, number, number, number];
      }
    >;

    ghstAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { contract_: string }>;

    interact(
      _tokenIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    kinship(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { score_: BigNumber }>;

    modifiedTraitsAndRarityScore(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [[number, number, number, number, number, number], BigNumber] & {
        numericTraits_: [number, number, number, number, number, number];
        rarityScore_: BigNumber;
      }
    >;

    portalAavegotchiTraits(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          }
        ]
      ] & {
        portalAavegotchiTraits_: [
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          },
          [
            BigNumber,
            [number, number, number, number, number, number],
            string,
            BigNumber
          ] & {
            randomNumber: BigNumber;
            numericTraits: [number, number, number, number, number, number];
            collateralType: string;
            minimumStake: BigNumber;
          }
        ];
      }
    >;

    rarityMultiplier(
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { multiplier_: BigNumber }>;

    revenueShares(
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, string] & {
          burnAddress: string;
          daoAddress: string;
          rarityFarming: string;
          pixelCraft: string;
        }
      ]
    >;

    setAavegotchiName(
      _tokenId: BigNumberish,
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    spendSkillPoints(
      _tokenId: BigNumberish,
      _values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    xpUntilNextLevel(
      _experience: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { requiredXp_: BigNumber }>;
  };

  aavegotchiLevel(
    _experience: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  aavegotchiNameAvailable(
    _name: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  availableSkillPoints(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  baseRarityScore(
    _numericTraits: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimAavegotchi(
    _tokenId: BigNumberish,
    _option: BigNumberish,
    _stakeAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  currentHaunt(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      [BigNumber, BigNumber, string, number] & {
        hauntMaxSize: BigNumber;
        portalPrice: BigNumber;
        bodyColor: string;
        totalCount: number;
      }
    ] & {
      hauntId_: BigNumber;
      haunt_: [BigNumber, BigNumber, string, number] & {
        hauntMaxSize: BigNumber;
        portalPrice: BigNumber;
        bodyColor: string;
        totalCount: number;
      };
    }
  >;

  getNumericTraits(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[number, number, number, number, number, number]>;

  ghstAddress(overrides?: CallOverrides): Promise<string>;

  interact(
    _tokenIds: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  kinship(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  modifiedTraitsAndRarityScore(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [[number, number, number, number, number, number], BigNumber] & {
      numericTraits_: [number, number, number, number, number, number];
      rarityScore_: BigNumber;
    }
  >;

  portalAavegotchiTraits(
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      },
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      },
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      },
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      },
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      },
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      },
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      },
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      },
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      },
      [
        BigNumber,
        [number, number, number, number, number, number],
        string,
        BigNumber
      ] & {
        randomNumber: BigNumber;
        numericTraits: [number, number, number, number, number, number];
        collateralType: string;
        minimumStake: BigNumber;
      }
    ]
  >;

  rarityMultiplier(
    _numericTraits: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  revenueShares(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string] & {
      burnAddress: string;
      daoAddress: string;
      rarityFarming: string;
      pixelCraft: string;
    }
  >;

  setAavegotchiName(
    _tokenId: BigNumberish,
    _name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  spendSkillPoints(
    _tokenId: BigNumberish,
    _values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  xpUntilNextLevel(
    _experience: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    aavegotchiLevel(
      _experience: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    aavegotchiNameAvailable(
      _name: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    availableSkillPoints(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baseRarityScore(
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimAavegotchi(
      _tokenId: BigNumberish,
      _option: BigNumberish,
      _stakeAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    currentHaunt(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        [BigNumber, BigNumber, string, number] & {
          hauntMaxSize: BigNumber;
          portalPrice: BigNumber;
          bodyColor: string;
          totalCount: number;
        }
      ] & {
        hauntId_: BigNumber;
        haunt_: [BigNumber, BigNumber, string, number] & {
          hauntMaxSize: BigNumber;
          portalPrice: BigNumber;
          bodyColor: string;
          totalCount: number;
        };
      }
    >;

    getNumericTraits(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number, number, number, number, number, number]>;

    ghstAddress(overrides?: CallOverrides): Promise<string>;

    interact(
      _tokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    kinship(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    modifiedTraitsAndRarityScore(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [[number, number, number, number, number, number], BigNumber] & {
        numericTraits_: [number, number, number, number, number, number];
        rarityScore_: BigNumber;
      }
    >;

    portalAavegotchiTraits(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        },
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        },
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        },
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        },
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        },
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        },
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        },
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        },
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        },
        [
          BigNumber,
          [number, number, number, number, number, number],
          string,
          BigNumber
        ] & {
          randomNumber: BigNumber;
          numericTraits: [number, number, number, number, number, number];
          collateralType: string;
          minimumStake: BigNumber;
        }
      ]
    >;

    rarityMultiplier(
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revenueShares(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        burnAddress: string;
        daoAddress: string;
        rarityFarming: string;
        pixelCraft: string;
      }
    >;

    setAavegotchiName(
      _tokenId: BigNumberish,
      _name: string,
      overrides?: CallOverrides
    ): Promise<void>;

    spendSkillPoints(
      _tokenId: BigNumberish,
      _values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: CallOverrides
    ): Promise<void>;

    xpUntilNextLevel(
      _experience: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "ClaimAavegotchi(uint256)"(
      _tokenId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _tokenId: BigNumber }>;

    ClaimAavegotchi(
      _tokenId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _tokenId: BigNumber }>;

    "LockAavegotchi(uint256,uint256)"(
      _tokenId?: BigNumberish | null,
      _time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { _tokenId: BigNumber; _time: BigNumber }
    >;

    LockAavegotchi(
      _tokenId?: BigNumberish | null,
      _time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { _tokenId: BigNumber; _time: BigNumber }
    >;

    "SetAavegotchiName(uint256,string,string)"(
      _tokenId?: BigNumberish | null,
      _oldName?: null,
      _newName?: null
    ): TypedEventFilter<
      [BigNumber, string, string],
      { _tokenId: BigNumber; _oldName: string; _newName: string }
    >;

    SetAavegotchiName(
      _tokenId?: BigNumberish | null,
      _oldName?: null,
      _newName?: null
    ): TypedEventFilter<
      [BigNumber, string, string],
      { _tokenId: BigNumber; _oldName: string; _newName: string }
    >;

    "SetBatchId(uint256,uint256[])"(
      _batchId?: BigNumberish | null,
      tokenIds?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber[]],
      { _batchId: BigNumber; tokenIds: BigNumber[] }
    >;

    SetBatchId(
      _batchId?: BigNumberish | null,
      tokenIds?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber[]],
      { _batchId: BigNumber; tokenIds: BigNumber[] }
    >;

    "SpendSkillpoints(uint256,int16[4])"(
      _tokenId?: BigNumberish | null,
      _values?: null
    ): TypedEventFilter<
      [BigNumber, [number, number, number, number]],
      { _tokenId: BigNumber; _values: [number, number, number, number] }
    >;

    SpendSkillpoints(
      _tokenId?: BigNumberish | null,
      _values?: null
    ): TypedEventFilter<
      [BigNumber, [number, number, number, number]],
      { _tokenId: BigNumber; _values: [number, number, number, number] }
    >;

    "UnLockAavegotchi(uint256,uint256)"(
      _tokenId?: BigNumberish | null,
      _time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { _tokenId: BigNumber; _time: BigNumber }
    >;

    UnLockAavegotchi(
      _tokenId?: BigNumberish | null,
      _time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { _tokenId: BigNumber; _time: BigNumber }
    >;
  };

  estimateGas: {
    aavegotchiLevel(
      _experience: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    aavegotchiNameAvailable(
      _name: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    availableSkillPoints(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baseRarityScore(
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimAavegotchi(
      _tokenId: BigNumberish,
      _option: BigNumberish,
      _stakeAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    currentHaunt(overrides?: CallOverrides): Promise<BigNumber>;

    getNumericTraits(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ghstAddress(overrides?: CallOverrides): Promise<BigNumber>;

    interact(
      _tokenIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    kinship(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    modifiedTraitsAndRarityScore(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    portalAavegotchiTraits(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rarityMultiplier(
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revenueShares(overrides?: CallOverrides): Promise<BigNumber>;

    setAavegotchiName(
      _tokenId: BigNumberish,
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    spendSkillPoints(
      _tokenId: BigNumberish,
      _values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    xpUntilNextLevel(
      _experience: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    aavegotchiLevel(
      _experience: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    aavegotchiNameAvailable(
      _name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    availableSkillPoints(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    baseRarityScore(
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimAavegotchi(
      _tokenId: BigNumberish,
      _option: BigNumberish,
      _stakeAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    currentHaunt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNumericTraits(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ghstAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    interact(
      _tokenIds: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    kinship(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    modifiedTraitsAndRarityScore(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    portalAavegotchiTraits(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rarityMultiplier(
      _numericTraits: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revenueShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAavegotchiName(
      _tokenId: BigNumberish,
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    spendSkillPoints(
      _tokenId: BigNumberish,
      _values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    xpUntilNextLevel(
      _experience: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
