/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CollateralEscrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CollateralEscrow__factory>;
    getContractFactory(
      name: "AavegotchiFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AavegotchiFacet__factory>;
    getContractFactory(
      name: "AavegotchiGameFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AavegotchiGameFacet__factory>;
    getContractFactory(
      name: "BridgeFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BridgeFacet__factory>;
    getContractFactory(
      name: "CollateralFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CollateralFacet__factory>;
    getContractFactory(
      name: "DAOFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DAOFacet__factory>;
    getContractFactory(
      name: "ERC1155MarketplaceFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155MarketplaceFacet__factory>;
    getContractFactory(
      name: "ERC721MarketplaceFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721MarketplaceFacet__factory>;
    getContractFactory(
      name: "EscrowFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowFacet__factory>;
    getContractFactory(
      name: "ItemsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItemsFacet__factory>;
    getContractFactory(
      name: "ItemsTransferFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItemsTransferFacet__factory>;
    getContractFactory(
      name: "MetaTransactionsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MetaTransactionsFacet__factory>;
    getContractFactory(
      name: "ShopFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShopFacet__factory>;
    getContractFactory(
      name: "SvgFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SvgFacet__factory>;
    getContractFactory(
      name: "SvgViewsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SvgViewsFacet__factory>;
    getContractFactory(
      name: "VoucherMigrationFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VoucherMigrationFacet__factory>;
    getContractFactory(
      name: "VrfFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VrfFacet__factory>;
    getContractFactory(
      name: "XingyunFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.XingyunFacet__factory>;
    getContractFactory(
      name: "InitDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InitDiamond__factory>;
    getContractFactory(
      name: "ILink",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILink__factory>;
    getContractFactory(
      name: "LibAavegotchi",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibAavegotchi__factory>;
    getContractFactory(
      name: "LibERC1155Marketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibERC1155Marketplace__factory>;
    getContractFactory(
      name: "LibERC721Marketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibERC721Marketplace__factory>;
    getContractFactory(
      name: "LibSvg",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibSvg__factory>;
    getContractFactory(
      name: "AavegotchiFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AavegotchiFacet__factory>;
    getContractFactory(
      name: "BridgeFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BridgeFacet__factory>;
    getContractFactory(
      name: "ItemsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItemsFacet__factory>;
    getContractFactory(
      name: "InitDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InitDiamond__factory>;
    getContractFactory(
      name: "GHSTFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GHSTFacet__factory>;
    getContractFactory(
      name: "InitDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InitDiamond__factory>;
    getContractFactory(
      name: "IGHSTDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGHSTDiamond__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC173",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC173__factory>;
    getContractFactory(
      name: "ILink",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILink__factory>;
    getContractFactory(
      name: "RafflesContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RafflesContract__factory>;
    getContractFactory(
      name: "Diamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Diamond__factory>;
    getContractFactory(
      name: "DiamondCutFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondCutFacet__factory>;
    getContractFactory(
      name: "DiamondLoupeFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondLoupeFacet__factory>;
    getContractFactory(
      name: "OwnershipFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnershipFacet__factory>;
    getContractFactory(
      name: "IDiamondCut",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondCut__factory>;
    getContractFactory(
      name: "IDiamondLoupe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondLoupe__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155TokenReceiver__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC173",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC173__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721TokenReceiver__factory>;
    getContractFactory(
      name: "LibDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibDiamond__factory>;
    getContractFactory(
      name: "LibERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibERC1155__factory>;
    getContractFactory(
      name: "LibERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibERC721__factory>;
    getContractFactory(
      name: "ERC20Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Token__factory>;
    getContractFactory(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataURI__factory>;
    getContractFactory(
      name: "IERC1155TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155TokenReceiver__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC173",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC173__factory>;
    getContractFactory(
      name: "LibERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibERC20__factory>;
    getContractFactory(
      name: "LinkTokenMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LinkTokenMock__factory>;
    getContractFactory(
      name: "MyFacet1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MyFacet1__factory>;

    getContractAt(
      name: "CollateralEscrow",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CollateralEscrow__factory>;
    getContractAt(
      name: "AavegotchiFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AavegotchiFacet__factory>;
    getContractAt(
      name: "AavegotchiGameFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AavegotchiGameFacet__factory>;
    getContractAt(
      name: "BridgeFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BridgeFacet__factory>;
    getContractAt(
      name: "CollateralFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CollateralFacet__factory>;
    getContractAt(
      name: "DAOFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DAOFacet__factory>;
    getContractAt(
      name: "ERC1155MarketplaceFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155MarketplaceFacet__factory>;
    getContractAt(
      name: "ERC721MarketplaceFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721MarketplaceFacet__factory>;
    getContractAt(
      name: "EscrowFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowFacet__factory>;
    getContractAt(
      name: "ItemsFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItemsFacet__factory>;
    getContractAt(
      name: "ItemsTransferFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItemsTransferFacet__factory>;
    getContractAt(
      name: "MetaTransactionsFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MetaTransactionsFacet__factory>;
    getContractAt(
      name: "ShopFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ShopFacet__factory>;
    getContractAt(
      name: "SvgFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SvgFacet__factory>;
    getContractAt(
      name: "SvgViewsFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SvgViewsFacet__factory>;
    getContractAt(
      name: "VoucherMigrationFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VoucherMigrationFacet__factory>;
    getContractAt(
      name: "VrfFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VrfFacet__factory>;
    getContractAt(
      name: "XingyunFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.XingyunFacet__factory>;
    getContractAt(
      name: "InitDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InitDiamond__factory>;
    getContractAt(
      name: "ILink",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILink__factory>;
    getContractAt(
      name: "LibAavegotchi",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibAavegotchi__factory>;
    getContractAt(
      name: "LibERC1155Marketplace",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibERC1155Marketplace__factory>;
    getContractAt(
      name: "LibERC721Marketplace",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibERC721Marketplace__factory>;
    getContractAt(
      name: "LibSvg",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibSvg__factory>;
    getContractAt(
      name: "AavegotchiFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AavegotchiFacet__factory>;
    getContractAt(
      name: "BridgeFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BridgeFacet__factory>;
    getContractAt(
      name: "ItemsFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItemsFacet__factory>;
    getContractAt(
      name: "InitDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InitDiamond__factory>;
    getContractAt(
      name: "GHSTFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GHSTFacet__factory>;
    getContractAt(
      name: "InitDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InitDiamond__factory>;
    getContractAt(
      name: "IGHSTDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGHSTDiamond__factory>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155__factory>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165__factory>;
    getContractAt(
      name: "IERC173",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC173__factory>;
    getContractAt(
      name: "ILink",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILink__factory>;
    getContractAt(
      name: "RafflesContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RafflesContract__factory>;
    getContractAt(
      name: "Diamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Diamond__factory>;
    getContractAt(
      name: "DiamondCutFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondCutFacet__factory>;
    getContractAt(
      name: "DiamondLoupeFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondLoupeFacet__factory>;
    getContractAt(
      name: "OwnershipFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnershipFacet__factory>;
    getContractAt(
      name: "IDiamondCut",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondCut__factory>;
    getContractAt(
      name: "IDiamondLoupe",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondLoupe__factory>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155__factory>;
    getContractAt(
      name: "IERC1155TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155TokenReceiver__factory>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165__factory>;
    getContractAt(
      name: "IERC173",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC173__factory>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20__factory>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721__factory>;
    getContractAt(
      name: "IERC721TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721TokenReceiver__factory>;
    getContractAt(
      name: "LibDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibDiamond__factory>;
    getContractAt(
      name: "LibERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibERC1155__factory>;
    getContractAt(
      name: "LibERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibERC721__factory>;
    getContractAt(
      name: "ERC20Token",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Token__factory>;
    getContractAt(
      name: "IERC1155MetadataURI",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataURI__factory>;
    getContractAt(
      name: "IERC1155TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155TokenReceiver__factory>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165__factory>;
    getContractAt(
      name: "IERC173",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC173__factory>;
    getContractAt(
      name: "LibERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibERC20__factory>;
    getContractAt(
      name: "LinkTokenMock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LinkTokenMock__factory>;
    getContractAt(
      name: "MyFacet1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MyFacet1__factory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt: (
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ) => Promise<ethers.Contract>;
  }
}
