/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LibERC721MarketplaceInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "ERC721ListingCancelled(uint256,uint256,uint256)": EventFragment;
    "ERC721ListingRemoved(uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ERC721ListingCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ERC721ListingRemoved"): EventFragment;
}

export type ERC721ListingCancelledEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber] & {
    listingId: BigNumber;
    category: BigNumber;
    time: BigNumber;
  }
>;

export type ERC721ListingRemovedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber] & {
    listingId: BigNumber;
    category: BigNumber;
    time: BigNumber;
  }
>;

export class LibERC721Marketplace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LibERC721MarketplaceInterface;

  functions: {};

  callStatic: {};

  filters: {
    "ERC721ListingCancelled(uint256,uint256,uint256)"(
      listingId?: BigNumberish | null,
      category?: null,
      time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { listingId: BigNumber; category: BigNumber; time: BigNumber }
    >;

    ERC721ListingCancelled(
      listingId?: BigNumberish | null,
      category?: null,
      time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { listingId: BigNumber; category: BigNumber; time: BigNumber }
    >;

    "ERC721ListingRemoved(uint256,uint256,uint256)"(
      listingId?: BigNumberish | null,
      category?: null,
      time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { listingId: BigNumber; category: BigNumber; time: BigNumber }
    >;

    ERC721ListingRemoved(
      listingId?: BigNumberish | null,
      category?: null,
      time?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber],
      { listingId: BigNumber; category: BigNumber; time: BigNumber }
    >;
  };

  estimateGas: {};

  populateTransaction: {};
}
