const itemTypes = [
  {
    svgId: 211,
    name: "Guy Fawkes Mask",
    setId: [94, 114],
    author: "xibot",
    description: "",
    dimensions: { x: 15, y: 6, width: 34, height: 39 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [0, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "head",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 212,
    name: "1337 Laptop",
    setId: [94, 95, 112, 114],
    author: "xibot",
    description: "",
    dimensions: { x: 0, y: 30, width: 16, height: 14 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 3000,
    maxQuantity: 50,
    traitModifiers: [-2, 0, 0, 3, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "hands",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 213,
    name: "H4xx0r Shirt",
    setId: [94, 95],
    author: "xibot",
    description: "",
    dimensions: { x: 10, y: 31, width: 44, height: 22 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [-4, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "body",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 214,
    name: "Matrix Eyes",
    setId: [95],
    author: "xibot",
    description: "",
    dimensions: { x: 20, y: 22, width: 24, height: 8 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: 5,
    traitModifiers: [-3, -3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "eyes",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 215,
    name: "Cyborg Eye",
    setId: [96],
    author: "xibot",
    description: "",
    dimensions: { x: 32, y: 15, width: 17, height: 19 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [2, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "eyes",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 216,
    name: "Rainbow Vomit",
    setId: [96],
    author: "xibot",
    description: "",
    dimensions: { x: 22, y: 32, width: 20, height: 23 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 3000,
    maxQuantity: 50,
    traitModifiers: [0, 0, -5, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "face",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 217,
    name: "Energy Gun",
    setId: [96],
    author: "xibot",
    description: "",
    dimensions: { x: 2, y: 33, width: 13, height: 11 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 3000,
    maxQuantity: 50,
    traitModifiers: [2, 3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "hands",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 218,
    name: "Mohawk",
    setId: [97],
    author: "xibot",
    description: "",
    dimensions: { x: 27, y: 0, width: 10, height: 22 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [1, 1, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "head",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 219,
    name: "Mutton Chops",
    setId: [97],
    author: "xibot",
    description: "",
    dimensions: { x: 15, y: 21, width: 34, height: 19 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, 0, 2, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "face",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 220,
    name: "Punk Shirt",
    setId: [97],
    author: "xibot",
    description: "",
    dimensions: { x: 9, y: 32, width: 46, height: 21 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [1, 3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "body",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 221,
    name: "Pirate Hat",
    setId: [98],
    author: "xibot",
    description: "",
    dimensions: { x: 7, y: 0, width: 50, height: 20 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [0, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "head",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 222,
    name: "Pirate Coat",
    setId: [98],
    author: "xibot",
    description: "",
    dimensions: { x: 10, y: 31, width: 44, height: 24 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, 0, 1, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "body",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 223,
    name: "Hook Hand",
    setId: [98],
    author: "xibot",
    description: "",
    dimensions: { x: 1, y: 35, width: 9, height: 9 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, 0, 1, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "hands",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 224,
    name: "Pirate Patch",
    setId: [98],
    author: "xibot",
    description: "",
    dimensions: { x: 15, y: 21, width: 34, height: 10 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, 0, 2, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "eyes",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 225,
    name: "Basketball",
    setId: [99],
    author: "xibot",
    description: "",
    dimensions: { x: 1, y: 28, width: 13, height: 13 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [1, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "hands",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 226,
    name: "Red Headband",
    setId: [99],
    author: "xibot",
    description: "",
    dimensions: { x: 15, y: 14, width: 34, height: 6 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [2, -1, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "head",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 227,
    name: "23 Jersey",
    setId: [99],
    author: "xibot",
    description: "",
    dimensions: { x: 15, y: 33, width: 34, height: 22 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [1, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "body",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 228,
    name: "10 Gallon Hat",
    setId: [100, 113],
    author: "xibot",
    description: "",
    dimensions: { x: 9, y: 3, width: 46, height: 18 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [0, 0, 0, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "head",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 229,
    name: "Lasso",
    setId: [100],
    author: "xibot",
    description: "",
    dimensions: { x: 2, y: 23, width: 12, height: 26 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, 1, 0, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "hands",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 230,
    name: "Wraangler Jeans",
    setId: [100],
    author: "xibot",
    description: "",
    dimensions: { x: 15, y: 40, width: 34, height: 15 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [0, 1, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "body",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 231,
    name: "Comfy Poncho",
    setId: [101, 102, 103, 104, 113],
    author: "rod",
    description: "",
    dimensions: { x: 12, y: 31, width: 40, height: 24 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [-2, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "body",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 232,
    name: "Poncho Hoodie",
    setId: [101, 102, 103, 104],
    author: "rod",
    description: "",
    dimensions: { x: 12, y: 1, width: 40, height: 30 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [-1, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "head",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 233,
    name: "Uncommon Cacti",
    setId: [101, 105],
    author: "xibot",
    description: "",
    dimensions: { x: 40, y: 45, width: 23, height: 17 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, 0, -1, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "pet",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 234,
    name: "Shaaman Poncho",
    setId: [105, 106, 107, 108, 111],
    author: "xibot",
    description: "",
    dimensions: { x: 12, y: 31, width: 40, height: 24 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 3000,
    maxQuantity: 50,
    traitModifiers: [-5, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "body",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 235,
    name: "Shaaman Hoodie",
    setId: [105, 106, 107, 108, 111],
    author: "xibot",
    description: "",
    dimensions: { x: 12, y: 1, width: 40, height: 30 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [-4, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "head",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 236,
    name: "Blue Cacti",
    setId: [102, 106],
    author: "xibot",
    description: "",
    dimensions: { x: 40, y: 45, width: 23, height: 17 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, 0, -1, 2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "pet",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 237,
    name: "Mythical Cacti",
    setId: [103, 107],
    author: "xibot",
    description: "",
    dimensions: { x: 1, y: 48, width: 62, height: 14 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 3000,
    maxQuantity: 50,
    traitModifiers: [0, 0, -2, 3, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "pet",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 238,
    name: "Godlike Cacti",
    setId: [104, 108, 111],
    author: "xibot",
    description: "",
    dimensions: { x: 1, y: 48, width: 62, height: 14 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: 5,
    traitModifiers: [0, 0, -3, 3, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "pet",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 239,
    name: "Wagie Cap",
    setId: [109],
    author: "xibot",
    description: "",
    dimensions: { x: 15, y: 4, width: 34, height: 19 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "head",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 240,
    name: "Headphones",
    setId: [109],
    author: "xibot",
    description: "",
    dimensions: { x: 11, y: 2, width: 42, height: 29 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "face",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 241,
    name: "WGMI Shirt",
    setId: [109],
    author: "xibot",
    description: "",
    dimensions: { x: 12, y: 32, width: 40, height: 21 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, -3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "body",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 242,
    name: "Yellow Manbun",
    setId: [110, 112],
    author: "esveebee",
    description: "",
    dimensions: { x: 15, y: 0, width: 34, height: 22 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [-2, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "head",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 243,
    name: "Tinted Shades",
    setId: [110, 112],
    author: "esveebee",
    description: "",
    dimensions: { x: 15, y: 22, width: 34, height: 9 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, -3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "eyes",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
  {
    svgId: 244,
    name: "V-Neck Shirt",
    setId: [110, 112],
    author: "esveebee",
    description: "",
    dimensions: { x: 12, y: 32, width: 40, height: 23 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, -3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: "body",
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
  },
];

function stringToSlotPositions(str) {
  if (str.length === 0)
    return [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 0 Body
  else if (str === "body")
    return [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 1 Face
  else if (str === "face")
    return [
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 2 Eyes
  else if (str === "eyes")
    return [
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 3 Head
  else if (str === "head")
    return [
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 4/5 Either hand
  else if (str === "hands")
    return [
      false,
      false,
      false,
      false,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 4 Left hand
  else if (str === "handLeft")
    return [
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 5 Right Hand
  else if (str === "handRight")
    return [
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 6 Pet
  else if (str === "pet")
    return [
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 7 Background
  else if (str === "background")
    return [
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  else {
    throw Error("Wrong slot string: " + str);
  }
}

function calculateRarityScoreModifier(maxQuantity) {
  if (maxQuantity >= 1000) return 1;
  if (maxQuantity >= 500) return 2;
  if (maxQuantity >= 250) return 5;
  if (maxQuantity >= 100) return 10;
  if (maxQuantity >= 10) return 20;
  if (maxQuantity >= 1) return 50;
  return 0;
}

function getItemTypes() {
  const result = [];
  for (const itemType of itemTypes) {
    itemType.ghstPrice = ethers.utils.parseEther(itemType.ghstPrice.toString());

    itemType.slotPositions = stringToSlotPositions(itemType.slotPositions);
    if (itemType.dimensions === "" || itemType.dimensions === 0) {
      itemType.dimensions = { x: 0, y: 0, width: 0, height: 0 };
    }
    itemType.rarityScoreModifier = calculateRarityScoreModifier(
      itemType.maxQuantity
    );
    if (!Array.isArray(itemType.allowedCollaterals)) {
      throw Error("Is not array.");
    }
    result.push(itemType);
  }

  return result;
}

exports.itemTypes = getItemTypes();
