const itemTypes = [
  [
    {
      id: 211,
      name: "Guy Fauwkes Mask",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 15, y: 6, width: 34, height: 39 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 5,
      maxQuantity: 1000,
      traitModifiers: [0, 0, 1, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "head",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 212,
      name: "1337 Laptop",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 0, y: 30, width: 16, height: 14 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 3000,
      maxQuantity: 50,
      traitModifiers: [-2, 0, 0, 3, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "hands",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 213,
      name: "H4xx0r Shirt ",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 10, y: 31, width: 44, height: 22 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 300,
      maxQuantity: 100,
      traitModifiers: [-4, 0, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "body",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 214,
      name: "Matrix Eyes",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 20, y: 22, width: 24, height: 8 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10000,
      maxQuantity: 5,
      traitModifiers: [-3, -3, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "eyes",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 215,
      name: "Cyborg Eye",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 32, y: 15, width: 17, height: 19 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 300,
      maxQuantity: 100,
      traitModifiers: [2, 2, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "eyes",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 216,
      name: "Rainbow Vomit",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 22, y: 32, width: 20, height: 23 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 3000,
      maxQuantity: 50,
      traitModifiers: [0, 0, -5, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "face",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 217,
      name: "Energy Gun",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 2, y: 33, width: 13, height: 11 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 3000,
      maxQuantity: 50,
      traitModifiers: [2, 3, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "hands",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 218,
      name: "Mohawk",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 27, y: 0, width: 10, height: 22 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10,
      maxQuantity: 500,
      traitModifiers: [1, 1, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "head",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 219,
      name: "Mutton Chops",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 15, y: 21, width: 34, height: 19 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 100,
      maxQuantity: 250,
      traitModifiers: [0, 0, 2, -1, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "face",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 220,
      name: "Punk Shirt",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 9, y: 32, width: 46, height: 21 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 300,
      maxQuantity: 100,
      traitModifiers: [1, 3, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "body",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 221,
      name: "Pirate Hat",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 7, y: 0, width: 50, height: 20 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 5,
      maxQuantity: 1000,
      traitModifiers: [0, 0, 0, -1, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "head",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 222,
      name: "Pirate Coat",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 10, y: 31, width: 44, height: 24 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10,
      maxQuantity: 500,
      traitModifiers: [0, 0, 1, -1, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "body",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 223,
      name: "Hook Hand",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 1, y: 35, width: 9, height: 9 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10,
      maxQuantity: 500,
      traitModifiers: [0, 0, 1, -1, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "hands",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 224,
      name: "Pirate Patch",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 15, y: 21, width: 34, height: 10 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 100,
      maxQuantity: 250,
      traitModifiers: [0, 0, 2, -1, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "eyes",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 225,
      name: "Basketball",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 1, y: 28, width: 13, height: 13 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 5,
      maxQuantity: 1000,
      traitModifiers: [1, 0, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "hands",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 226,
      name: "Red Headband",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 15, y: 14, width: 34, height: 6 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 100,
      maxQuantity: 250,
      traitModifiers: [2, -1, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "head",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 227,
      name: "23 Jersey",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 15, y: 33, width: 34, height: 22 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 100,
      maxQuantity: 250,
      traitModifiers: [1, -2, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "body",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 228,
      name: "10 Gallon Hat",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 9, y: 3, width: 46, height: 18 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 5,
      maxQuantity: 1000,
      traitModifiers: [0, 0, 0, 1, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "head",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 229,
      name: "Lasso",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 2, y: 23, width: 12, height: 26 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10,
      maxQuantity: 500,
      traitModifiers: [0, 1, 0, 1, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "hands",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 230,
      name: "Wraangler Jeans",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 15, y: 40, width: 34, height: 15 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 5,
      maxQuantity: 1000,
      traitModifiers: [0, 1, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "body",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 231,
      name: "Comfy Poncho",
      setId: [],
      author: "rod",
      desc: "",
      dimensions: { x: 12, y: 31, width: 40, height: 24 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10,
      maxQuantity: 500,
      traitModifiers: [-2, 0, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "body",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 232,
      name: "Poncho Hoodie",
      setId: [],
      author: "rod",
      desc: "",
      dimensions: { x: 12, y: 1, width: 40, height: 30 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 5,
      maxQuantity: 1000,
      traitModifiers: [-1, 0, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "head",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 233,
      name: "Uncommon Cacti",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 40, y: 45, width: 23, height: 17 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10,
      maxQuantity: 500,
      traitModifiers: [0, 0, -1, 1, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "pet",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 234,
      name: "Shaaman Poncho",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 12, y: 31, width: 40, height: 24 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 3000,
      maxQuantity: 50,
      traitModifiers: [-5, 0, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "body",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 235,
      name: "Shaaman Hoodie",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 12, y: 1, width: 40, height: 30 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 300,
      maxQuantity: 100,
      traitModifiers: [-4, 0, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "head",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 236,
      name: "Blue Cacti",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 40, y: 45, width: 23, height: 17 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 100,
      maxQuantity: 250,
      traitModifiers: [0, 0, -1, 2, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "pet",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 237,
      name: "Mythical Cacti",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 1, y: 48, width: 62, height: 14 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 3000,
      maxQuantity: 50,
      traitModifiers: [0, 0, -2, 3, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "pet",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 238,
      name: "Godlike Cacti",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 1, y: 48, width: 62, height: 14 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10000,
      maxQuantity: 5,
      traitModifiers: [0, 0, -3, 3, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "pet",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 239,
      name: "Wagie Cap",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 15, y: 4, width: 34, height: 19 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10,
      maxQuantity: 500,
      traitModifiers: [0, -2, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "head",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 240,
      name: "Headphones",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 11, y: 2, width: 42, height: 29 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 10,
      maxQuantity: 500,
      traitModifiers: [0, -2, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "face",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 241,
      name: "WGMI Shirt",
      setId: [],
      author: "xibot",
      desc: "",
      dimensions: { x: 12, y: 32, width: 40, height: 21 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 100,
      maxQuantity: 250,
      traitModifiers: [0, -3, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "body",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 242,
      name: "Yellow Manbun",
      setId: [],
      author: "esveebee",
      desc: "",
      dimensions: { x: 15, y: 0, width: 34, height: 22 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 300,
      maxQuantity: 100,
      traitModifiers: [-2, -2, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "head",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 243,
      name: "Tinted Shades",
      setId: [],
      author: "esveebee",
      desc: "",
      dimensions: { x: 15, y: 22, width: 34, height: 9 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 100,
      maxQuantity: 250,
      traitModifiers: [0, -3, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "eyes",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
    {
      id: 244,
      name: "V-Neck Shirt",
      setId: [],
      author: "esveebee",
      desc: "",
      dimensions: { x: 12, y: 32, width: 40, height: 23 },
      allowedCollaterals: [],
      minLevel: 1,
      ghstPrice: 100,
      maxQuantity: 250,
      traitModifiers: [0, -3, 0, 0, 0, 0],
      canPurchaseWithGhst: false,
      slotPositions: "body",
      category: 0,
      canBeTransferred: true,
      totalQuantity: 0,
      experienceBonus: 0,
      kinshipBonus: 0,
    },
  ],
];

function stringToSlotPositions(str) {
  if (str.length === 0)
    return [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 0 Body
  else if (str === "body")
    return [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 1 Face
  else if (str === "face")
    return [
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 2 Eyes
  else if (str === "eyes")
    return [
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 3 Head
  else if (str === "head")
    return [
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 4/5 Either hand
  else if (str === "hands")
    return [
      false,
      false,
      false,
      false,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 4 Left hand
  else if (str === "handLeft")
    return [
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 5 Right Hand
  else if (str === "handRight")
    return [
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 6 Pet
  else if (str === "pet")
    return [
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  // Slot 7 Background
  else if (str === "background")
    return [
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ];
  else {
    throw Error("Wrong slot string: " + str);
  }
}

function calculateRarityScoreModifier(maxQuantity) {
  if (maxQuantity >= 1000) return 1;
  if (maxQuantity >= 500) return 2;
  if (maxQuantity >= 250) return 5;
  if (maxQuantity >= 100) return 10;
  if (maxQuantity >= 10) return 20;
  if (maxQuantity >= 1) return 50;
  return 0;
}

function getItemTypes() {
  const result = [];
  for (const itemType of itemTypes) {
    itemType.ghstPrice = ethers.utils.parseEther(itemType.ghstPrice.toString());

    itemType.slotPositions = stringToSlotPositions(itemType.slotPositions);
    if (itemType.dimensions === "" || itemType.dimensions === 0) {
      itemType.dimensions = { x: 0, y: 0, width: 0, height: 0 };
    }
    itemType.rarityScoreModifier = calculateRarityScoreModifier(
      itemType.maxQuantity
    );
    if (!Array.isArray(itemType.allowedCollaterals)) {
      throw Error("Is not array.");
    }
    result.push(itemType);
  }

  return result;
}

exports.itemTypes = getItemTypes();
