const { isThrowStatement } = require('typescript')

/* global ethers */
const WEARABLE_SLOT_BODY = 0
const WEARABLE_SLOT_FACE = 1
const WEARABLE_SLOT_EYES = 2
const WEARABLE_SLOT_HEAD = 3
const WEARABLE_SLOT_HAND_LEFT = 4
const WEARABLE_SLOT_HAND_RIGHT = 5
const WEARABLE_SLOT_PET_FRONT = 6
const WEARABLE_SLOT_PET_BACK = 7
const WEARABLE_SLOT_BG = 8

const itemTypes = [
  {
    svgId: 0,
    name: 'The Void',
    setId: [],
    author: 'Xibot',
    description: 'The Void',
    dimensions: '',
    x: 0,
    y: 0,
    width: 0,
    height: 0,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 0,
    maxQuantity: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: '',
    category: 0,
    canBeTransferred: false,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },

  {
    svgId: 1,
    name: 'Camo Hat',
    setId: [1],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 2, width: 34, height: 20 },
    x: 15,
    y: 2,
    width: 34,
    height: 20,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 1, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 2,
    name: 'Camo Pants',
    setId: [1],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 41, width: 34, height: 14 },
    x: 15,
    y: 41,
    width: 34,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 1, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 3,
    name: 'MK2 Grenade',
    setId: [1],
    author: 'Xibot',
    description: '',
    dimensions: { x: 5, y: 31, width: 8, height: 11 },
    x: 5,
    y: 31,
    width: 8,
    height: 11,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 1, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 4,
    name: 'Snow Camo Hat',
    setId: [2],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 2, width: 34, height: 20 },
    x: 15,
    y: 2,
    width: 34,
    height: 20,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [0, 1, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 5,
    name: 'Snow Camo Pants',
    setId: [2, 69],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 41, width: 34, height: 14 },
    x: 15,
    y: 41,
    width: 34,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [0, 1, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 6,
    name: 'M67 Grenade',
    setId: [2],
    author: 'Xibot',
    description: '',
    dimensions: { x: 4, y: 31, width: 9, height: 11 },
    x: 4,
    y: 31,
    width: 9,
    height: 11,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [0, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 7,
    name: 'Marine Cap',
    setId: [3],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 1, width: 39, height: 27 },
    x: 12,
    y: 1,
    width: 39,
    height: 27,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '300',
    traitModifiers: [0, 2, 0, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 8,
    name: 'Marine Jacket',
    setId: [3],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 32, width: 40, height: 23 },
    x: 12,
    y: 32,
    width: 40,
    height: 23,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '300',
    traitModifiers: [0, 2, 0, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 9,
    name: 'Walkie Talkie',
    setId: [3],
    author: 'Xibot',
    description: '',
    dimensions: { x: 3, y: 31, width: 7, height: 15 },
    x: 3,
    y: 31,
    width: 7,
    height: 15,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '300',
    traitModifiers: [1, 0, 1, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 10,
    name: 'Link White Hat',
    setId: [4],
    author: 'Xibot',
    description: '',
    dimensions: { x: 9, y: 1, width: 46, height: 20 },
    x: 9,
    y: 1,
    width: 46,
    height: 20,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '150',
    traitModifiers: [0, 2, 0, 2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 11,
    name: 'Link Mess Dress',
    setId: [4],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 32, width: 40, height: 23 },
    x: 12,
    y: 32,
    width: 40,
    height: 23,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '150',
    traitModifiers: [0, 2, 0, 2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 12,
    name: 'Link Bubbly',
    setId: [4, 61],
    author: 'Xibot',
    description: '',
    dimensions: { x: 5, y: 25, width: 5, height: 19 },
    x: 5,
    y: 25,
    width: 5,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '150',
    traitModifiers: [2, 0, 0, -2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 13,
    name: 'Sergey Beard',
    setId: [5, 6, 7, 68, 69],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 6, width: 34, height: 34 },
    x: 15,
    y: 6,
    width: 34,
    height: 34,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [-1, 1, 0, 3, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'face',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 14,
    name: 'Sergey Eyes',
    setId: [5, 6, 7],
    author: 'Xibot',
    description: '',
    dimensions: { x: 22, y: 22, width: 20, height: 8 },
    x: 22,
    y: 22,
    width: 20,
    height: 8,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, 0, 1, 4, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 15,
    name: 'Red Plaid',
    setId: [5],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 22 },
    x: 12,
    y: 33,
    width: 40,
    height: 23,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [3, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 16,
    name: 'Blue Plaid',
    setId: [6, 7],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 22 },
    x: 12,
    y: 33,
    width: 40,
    height: 23,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [-4, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 17,
    name: 'Link Cube',
    setId: [7],
    author: 'Xibot',
    description: '',
    dimensions: { x: 1, y: 31, width: 12, height: 16 },
    x: 1,
    y: 31,
    width: 12,
    height: 16,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [0, 0, 0, 6, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 18,
    name: 'Aave Hero Mask',
    setId: [8],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 19, width: 38, height: 13 },
    x: 15,
    y: 19,
    width: 38,
    height: 13,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'face',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 19,
    name: 'Aave Hero Shirt',
    setId: [8, 61],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 32, width: 40, height: 19 },
    x: 12,
    y: 32,
    width: 40,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 20,
    name: 'Aave Plush',
    setId: [8],
    author: 'Xibot',
    description: '',
    dimensions: { x: 1, y: 32, width: 13, height: 13 },
    x: 1,
    y: 32,
    width: 13,
    height: 13,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 21,
    name: 'Captain Aave Mask',
    setId: [9],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 6, width: 42, height: 28 },
    x: 11,
    y: 6,
    width: 42,
    height: 28,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [1, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 22,
    name: 'Captain Aave Suit',
    setId: [9],
    author: 'Xibot',
    description: '',
    dimensions: { x: 7, y: 33, width: 50, height: 22 },
    x: 7,
    y: 34,
    width: 50,
    height: 24,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [1, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 23,
    name: 'Captain Aave Shield',
    setId: [9],
    author: 'Xibot',
    description: '',
    dimensions: { x: 3, y: 32, width: 20, height: 20 },
    x: 3,
    y: 32,
    width: 20,
    height: 20,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [2, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 24,
    name: 'Thaave Helmet',
    setId: [10],
    author: 'Xibot',
    description: '',
    dimensions: { x: 9, y: 6, width: 46, height: 24 },
    x: 9,
    y: 6,
    width: 46,
    height: 24,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [2, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 25,
    name: 'Thaave Suit',
    setId: [10, 65],
    author: 'Xibot',
    description: '',
    dimensions: { x: 9, y: 33, width: 46, height: 22 },
    x: 9,
    y: 33,
    width: 46,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [2, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 26,
    name: 'Thaave Hammer',
    setId: [10],
    author: 'Xibot',
    description: '',
    dimensions: { x: 0, y: 28, width: 14, height: 14 },
    x: 0,
    y: 28,
    width: 14,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [3, 0, 0, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 27,
    name: 'Marc Hair',
    setId: [11],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 6, width: 34, height: 20 },
    x: 15,
    y: 6,
    width: 34,
    height: 20,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '100',
    traitModifiers: [2, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 28,
    name: 'Marc Outfit',
    setId: [11],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 22 },
    x: 12,
    y: 33,
    width: 40,
    height: 23,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '100',
    traitModifiers: [2, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 29,
    name: 'REKT Sign',
    setId: [11, 62],
    author: 'Xibot',
    description: '',
    dimensions: { x: 0, y: 24, width: 17, height: 23 },
    x: 0,
    y: 24,
    width: 17,
    height: 23,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '100',
    traitModifiers: [0, 0, 0, -4, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'handLeft',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 30,
    name: 'Jordan Hair',
    setId: [12],
    author: 'Xibot',
    description: '',
    dimensions: { x: 7, y: 0, width: 50, height: 34 },
    x: 7,
    y: 0,
    width: 50,
    height: 34,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, -2, 3, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 31,
    name: 'Jordan Suit',
    setId: [12],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 22 },
    x: 12,
    y: 33,
    width: 40,
    height: 23,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [-3, 0, 1, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 32,
    name: 'Aave Flag',
    setId: [12, 13],
    author: 'Xibot',
    description: '',
    dimensions: { x: 0, y: 24, width: 12, height: 25 },
    x: 0,
    y: 24,
    width: 12,
    height: 25,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, -2, 3, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 33,
    name: 'Stani Hair',
    setId: [13, 14],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 6, width: 34, height: 18 },
    x: 15,
    y: 6,
    width: 34,
    height: 18,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [0, -3, 0, 3, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 34,
    name: 'Stani Vest',
    setId: [13, 14],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 33, width: 34, height: 16 },
    x: 15,
    y: 33,
    width: 34,
    height: 16,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [3, -3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 35,
    name: 'Aave Boat',
    setId: [13, 14, 67],
    author: 'Xibot',
    description: '',
    dimensions: { x: 5, y: 46, width: 57, height: 15 },
    x: 5,
    y: 46,
    width: 57,
    height: 15,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [0, -6, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'pet',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 36,
    name: 'ETH Logo Glasses',
    setId: [15, 61],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 19, width: 34, height: 13 },
    x: 15,
    y: 19,
    width: 34,
    height: 13,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 37,
    name: 'ETH Tshirt',
    setId: [15],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 19 },
    x: 12,
    y: 32,
    width: 40,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 38,
    name: '32 ETH Coin',
    setId: [15],
    author: 'Xibot',
    description: '',
    dimensions: { x: 1, y: 31, width: 14, height: 14 },
    x: 1,
    y: 31,
    width: 14,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'handLeft',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 39,
    name: 'Foxy Mask',
    setId: [16],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 2, width: 34, height: 40 },
    x: 15,
    y: 2,
    width: 34,
    height: 40,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [0, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 40,
    name: 'Foxy Tail',
    setId: [16, 61, 70],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 22, width: 49, height: 28 },
    x: 49,
    y: 22,
    width: 15,
    height: 28,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [0, -1, -1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 41,
    name: 'Trezor Wallet',
    setId: [16],
    author: 'Xibot',
    description: '',
    dimensions: { x: 4, y: 31, width: 9, height: 14 },
    x: 4,
    y: 31,
    width: 9,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [-1, -1, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 42,
    name: 'Eagle Mask',
    setId: [17],
    author: 'Xibot',
    description: '',
    dimensions: { x: 5, y: 6, width: 54, height: 27 },
    x: 5,
    y: 6,
    width: 54,
    height: 27,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [1, 0, 2, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 43,
    name: 'Eagle Armor',
    setId: [17],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 22 },
    x: 12,
    y: 33,
    width: 40,
    height: 23,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [2, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 44,
    name: 'DAO Egg',
    setId: [17],
    author: 'Xibot',
    description: '',
    dimensions: { x: 0, y: 27, width: 16, height: 22 },
    x: 0,
    y: 27,
    width: 16,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [1, 0, 0, 2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'handLeft',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 45,
    name: 'Ape Mask',
    setId: [18, 62],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 6, width: 42, height: 36 },
    x: 11,
    y: 6,
    width: 42,
    height: 35,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '100',
    traitModifiers: [0, 1, 0, -3, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 46,
    name: 'Halfrekt Shirt',
    setId: [18, 62],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 19 },
    x: 12,
    y: 32,
    width: 40,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '100',
    traitModifiers: [1, 1, 0, -2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 47,
    name: 'Waifu Pillow',
    setId: [18, 63],
    author: 'Xibot',
    description: '',
    dimensions: { x: 0, y: 23, width: 17, height: 30 },
    x: 0,
    y: 23,
    width: 17,
    height: 30,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '100',
    traitModifiers: [0, 0, 0, -4, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 48,
    name: 'Xibot Mohawk',
    setId: [19],
    author: 'Xibot',
    description: '',
    dimensions: { x: 27, y: 0, width: 10, height: 22 },
    x: 27,
    y: 0,
    width: 10,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [5, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 49,
    name: 'Coderdan Shades',
    setId: [19],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 19, width: 34, height: 12 },
    x: 15,
    y: 19,
    width: 34,
    height: 12,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, 5, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 50,
    name: 'GldnXross Robe',
    setId: [19],
    author: 'Xibot',
    description: '',
    dimensions: { x: 10, y: 33, width: 44, height: 24 },
    x: 10,
    y: 33,
    width: 44,
    height: 24,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, 0, 5, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 51,
    name: 'Mudgen Diamond',
    setId: [19, 21],
    author: 'Xibot',
    description: '',
    dimensions: { x: 0, y: 33, width: 13, height: 10 },
    x: 2,
    y: 33,
    width: 13,
    height: 10,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, 0, 0, 5, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 52,
    name: 'Galaxy Brain',
    setId: [20, 21],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 1, width: 42, height: 22 },
    x: 11,
    y: 1,
    width: 42,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [0, 0, 0, 6, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 53,
    name: 'All-Seeing Eyes',
    setId: [20, 21],
    author: 'Xibot',
    description: '',
    dimensions: { x: 18, y: 19, width: 28, height: 12 },
    x: 18,
    y: 19,
    width: 28,
    height: 12,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [-6, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 54,
    name: 'Llamacorn Shirt',
    setId: [20, 21],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 21 },
    x: 12,
    y: 32,
    width: 40,
    height: 21,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [-3, -3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 55,
    name: 'Aagent Headset',
    setId: [22, 23, 24],
    author: 'Xibot',
    description: '',
    dimensions: { x: 48, y: 25, width: 3, height: 7 },
    x: 48,
    y: 25,
    width: 3,
    height: 7,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, 1, 1, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'face',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 56,
    name: 'Aagent Shirt',
    setId: [22, 23, 24],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 19 },
    x: 12,
    y: 32,
    width: 40,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [-1, 1, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 57,
    name: 'Aagent Shades',
    setId: [22, 23, 24],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 22, width: 34, height: 9 },
    x: 15,
    y: 22,
    width: 34,
    height: 9,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [-1, 0, 2, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 58,
    name: 'Aagent Pistol',
    setId: [22, 24],
    author: 'Xibot',
    description: '',
    dimensions: { x: 2, y: 34, width: 9, height: 7 },
    x: 2,
    y: 34,
    width: 9,
    height: 7,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, 3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 59,
    name: 'Aagent Fedora Hat',
    setId: [22, 63],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 4, width: 42, height: 17 },
    x: 11,
    y: 4,
    width: 42,
    height: 17,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [-2, 0, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 60,
    name: 'Common Wizard Hat',
    setId: [25, 29],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 0, width: 42, height: 22 },
    x: 11,
    y: 0,
    width: 42,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 0, 1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 61,
    name: 'Legendary Wizard Hat',
    setId: [26, 30],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 0, width: 42, height: 22 },
    x: 11,
    y: 0,
    width: 42,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [0, 0, 2, 2, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 62,
    name: 'Mythical Wizard Hat',
    setId: [27, 31],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 0, width: 42, height: 22 },
    x: 11,
    y: 0,
    width: 42,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, 0, 2, 3, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 63,
    name: 'Godlike Wizard Hat',
    setId: [28, 32],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 0, width: 42, height: 22 },
    x: 11,
    y: 0,
    width: 42,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [0, 0, 2, 4, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 64,
    name: 'Common Wizard Staff',
    setId: [25, 26, 27, 28],
    author: 'Xibot',
    description: '',
    dimensions: { x: 7, y: 24, width: 7, height: 31 },
    x: 7,
    y: 24,
    width: 7,
    height: 31,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [1, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 65,
    name: 'Legendary Wizard Staff',
    setId: [29, 30, 31, 32],
    author: 'Xibot',
    description: '',
    dimensions: { x: 6, y: 22, width: 9, height: 33 },
    x: 6,
    y: 22,
    width: 9,
    height: 33,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [2, 0, 0, 2, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 66,
    name: 'Wizard Visor',
    setId: [25, 26, 27, 28, 29, 30, 31, 32],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 22, width: 34, height: 8 },
    x: 15,
    y: 22,
    width: 34,
    height: 8,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [1, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 67,
    name: 'Straw Hat',
    setId: [33, 34, 68],
    author: 'Xibot',
    description: '',
    dimensions: { x: 7, y: 2, width: 50, height: 20 },
    x: 7,
    y: 2,
    width: 50,
    height: 20,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [-1, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 68,
    name: 'Farmer Jeans',
    setId: [33, 34, 68],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 41, width: 34, height: 14 },
    x: 15,
    y: 41,
    width: 34,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 69,
    name: 'Pitchfork',
    setId: [33, 68],
    author: 'Xibot',
    description: '',
    dimensions: { x: 7, y: 24, width: 7, height: 31 },
    x: 7,
    y: 24,
    width: 7,
    height: 31,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 1, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 70,
    name: 'Handsaw',
    setId: [34],
    author: 'Cryptofluffycat',
    description: '',
    dimensions: { x: 7, y: 19, width: 5, height: 27 },
    x: 7,
    y: 19,
    width: 5,
    height: 27,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, 3, 0, -2, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 71,
    name: 'Red Santa Hat',
    setId: [69],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 0, width: 42, height: 22 },
    x: 11,
    y: 0,
    width: 42,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 0,
    maxQuantity: '250',
    traitModifiers: [0, -1, -2, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 72,
    name: 'Jaay Hairpiece',
    setId: [35, 36],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 6, width: 36, height: 16 },
    x: 15,
    y: 6,
    width: 36,
    height: 16,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 0,
    maxQuantity: '30',
    traitModifiers: [0, 0, 0, -5, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 73,
    name: 'Jaay Glasses',
    setId: [35, 36],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 21, width: 34, height: 10 },
    x: 15,
    y: 21,
    width: 34,
    height: 10,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 0,
    maxQuantity: '10',
    traitModifiers: [-2, -2, 0, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 74,
    name: 'Jaay Suit',
    setId: [35, 36, 63],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 32, width: 42, height: 23 },
    x: 11,
    y: 31,
    width: 42,
    height: 24,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 0,
    maxQuantity: '20',
    traitModifiers: [-2, 0, 0, -3, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 75,
    name: 'OKex Sign',
    setId: [36],
    author: 'Xibot',
    description: '',
    dimensions: { x: 1, y: 24, width: 13, height: 22 },
    x: 50,
    y: 24,
    width: 13,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 0,
    maxQuantity: '40',
    traitModifiers: [-5, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 76,
    name: 'Big GHST Token',
    setId: [64],
    author: 'Xibot',
    description: '',
    dimensions: { x: 1, y: 33, width: 12, height: 12 },
    x: 1,
    y: 33,
    width: 12,
    height: 12,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 0, 1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'handLeft',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 77,
    name: 'Bitcoin Beanie',
    setId: [37, 61, 65],
    author: 'Xibot',
    description: '',
    dimensions: { x: 13, y: 2, width: 38, height: 18 },
    x: 13,
    y: 2,
    width: 38,
    height: 18,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [1, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 78,
    name: 'Black Jeans',
    setId: [37],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 41, width: 34, height: 14 },
    x: 15,
    y: 41,
    width: 34,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [0, 1, 0, -1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 79,
    name: 'Skateboard',
    setId: [37],
    author: 'Xibot',
    description: '',
    dimensions: { x: 5, y: 25, width: 8, height: 26 },
    x: 5,
    y: 25,
    width: 8,
    height: 26,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [1, 0, 0, -2, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 80,
    name: 'Sushi Bandana',
    setId: [38, 39, 40],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 14, width: 38, height: 10 },
    x: 15,
    y: 14,
    width: 38,
    height: 10,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [-1, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 81,
    name: 'Sushi Coat',
    setId: [38, 39, 40],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 41, width: 36, height: 14 },
    x: 15,
    y: 41,
    width: 36,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [-2, 1, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 82,
    name: 'Sushi Piece',
    setId: [39, 40],
    author: 'Xibot',
    description: '',
    dimensions: { x: 0, y: 29, width: 19, height: 15 },
    x: 44,
    y: 29,
    width: 19,
    height: 15,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [0, 0, -4, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 83,
    name: 'Sushi Knife',
    setId: [38],
    author: 'Xibot',
    description: '',
    dimensions: { x: 7, y: 25, width: 6, height: 18 },
    x: 7,
    y: 25,
    width: 6,
    height: 18,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [0, 3, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 84,
    name: 'Gentleman Hat',
    setId: [41],
    author: 'Xibot',
    description: '',
    dimensions: { x: 9, y: 2, width: 46, height: 18 },
    x: 9,
    y: 2,
    width: 46,
    height: 18,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [-1, -3, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 85,
    name: 'Gentleman Coat',
    setId: [41],
    author: 'Xibot',
    description: '',
    dimensions: { x: 12, y: 32, width: 40, height: 23 },
    x: 12,
    y: 32,
    width: 40,
    height: 23,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [-1, -3, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 86,
    name: 'Monocle',
    setId: [41],
    author: 'Xibot',
    description: '',
    dimensions: { x: 34, y: 21, width: 12, height: 21 },
    x: 34,
    y: 21,
    width: 12,
    height: 21,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, -2, 0, 3, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 87,
    name: 'Miner Helmet',
    setId: [42],
    author: 'Xibot',
    description: '',
    dimensions: { x: 13, y: 4, width: 38, height: 18 },
    x: 13,
    y: 4,
    width: 38,
    height: 18,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [1, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 88,
    name: 'Miner Jeans',
    setId: [42],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 41, width: 34, height: 14 },
    x: 15,
    y: 41,
    width: 34,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [1, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 89,
    name: 'Pickaxe',
    setId: [42, 65],
    author: 'Xibot',
    description: '',
    dimensions: { x: 0, y: 30, width: 14, height: 14 },
    x: 0,
    y: 30,
    width: 14,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [1, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 90,
    name: 'Pajama Hat',
    setId: [43, 44, 45, 66],
    author: 'Xibot',
    description: '',
    dimensions: { x: 8, y: 0, width: 43, height: 22 },
    x: 8,
    y: 0,
    width: 43,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, -1, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 91,
    name: 'Pajama Shirt',
    setId: [43, 44, 45, 66],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 33, width: 42, height: 22 },
    x: 11,
    y: 31,
    width: 42,
    height: 24,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [0, -1, -1, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 92,
    name: 'Bedtime Milk',
    setId: [43, 45],
    author: 'Xibot',
    description: '',
    dimensions: { x: 4, y: 34, width: 6, height: 10 },
    x: 4,
    y: 34,
    width: 6,
    height: 10,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [0, -2, -1, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 93,
    name: 'Fluffy Pillow',
    setId: [45],
    author: 'Xibot',
    description: '',
    dimensions: { x: 3, y: 36, width: 11, height: 19 },
    x: 50,
    y: 36,
    width: 11,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [0, 0, -4, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 94,
    name: 'Sweatband',
    setId: [46, 47, 48, 49],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 14, width: 34, height: 6 },
    x: 15,
    y: 14,
    width: 34,
    height: 6,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [2, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 95,
    name: 'Track Shorts',
    setId: [47, 48],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 41, width: 34, height: 14 },
    x: 15,
    y: 41,
    width: 34,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [1, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 96,
    name: 'Water bottle',
    setId: [46, 48],
    author: 'Xibot',
    description: '',
    dimensions: { x: 7, y: 31, width: 6, height: 13 },
    x: 7,
    y: 31,
    width: 6,
    height: 13,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [2, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 97,
    name: 'Pillbox Hat',
    setId: [50, 51, 52],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 3, width: 42, height: 18 },
    x: 11,
    y: 3,
    width: 42,
    height: 18,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [1, -1, -2, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 98,
    name: 'Day Dress',
    setId: [50, 51, 52],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 40, width: 34, height: 15 },
    x: 15,
    y: 40,
    width: 34,
    height: 15,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [1, -1, -2, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 99,
    name: 'Parasol',
    setId: [51, 52],
    author: 'Xibot',
    description: '',
    dimensions: { x: 1, y: 21, width: 17, height: 25 },
    x: 1,
    y: 21,
    width: 17,
    height: 25,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [1, -1, -3, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 100,
    name: 'Clutch',
    setId: [50, 52],
    author: 'Xibot',
    description: '',
    dimensions: { x: 4, y: 37, width: 9, height: 14 },
    x: 51,
    y: 37,
    width: 9,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [1, -2, -2, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 101,
    name: 'Witchy Hat',
    setId: [53],
    author: 'Xibot',
    description: '',
    dimensions: { x: 11, y: 0, width: 42, height: 22 },
    x: 11,
    y: 0,
    width: 42,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [0, 1, 3, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 102,
    name: 'Witchy Cloak',
    setId: [53],
    author: 'Xibot',
    description: '',
    dimensions: { x: 9, y: 29, width: 46, height: 26 },
    x: 9,
    y: 29,
    width: 46,
    height: 26,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [0, 1, 3, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 103,
    name: 'Witchy Wand',
    setId: [53],
    author: 'Xibot',
    description: '',
    dimensions: { x: 3, y: 33, width: 11, height: 11 },
    x: 3,
    y: 33,
    width: 11,
    height: 11,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, 2, 2, 1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 104,
    name: 'Portal Mage Helmet',
    setId: [54, 55],
    author: 'Esveebee',
    description: '',
    dimensions: { x: 8, y: 1, width: 48, height: 35 },
    x: 8,
    y: 1,
    width: 48,
    height: 35,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [2, 1, 1, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 105,
    name: 'Portal Mage Armor',
    setId: [54, 55],
    author: 'Esveebee',
    description: '',
    dimensions: { x: 7, y: 29, width: 50, height: 26 },
    x: 7,
    y: 29,
    width: 50,
    height: 26,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [1, 2, 2, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 106,
    name: 'Portal Mage Axe',
    setId: [54, 69],
    author: 'Esveebee',
    description: '',
    dimensions: { x: 0, y: 18, width: 14, height: 28 },
    x: 0,
    y: 18,
    width: 14,
    height: 28,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [0, 4, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 107,
    name: 'Portal Mage Black Axe',
    setId: [55],
    author: 'Esveebee',
    description: '',
    dimensions: { x: 0, y: 18, width: 14, height: 28 },
    x: 0,
    y: 18,
    width: 14,
    height: 28,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [0, 6, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 108,
    name: 'Rasta Hat',
    setId: [56],
    author: 'Cawito',
    description: '',
    dimensions: { x: 11, y: 3, width: 42, height: 29 },
    x: 11,
    y: 3,
    width: 42,
    height: 29,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [-1, -1, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 109,
    name: 'Rasta Shirt',
    setId: [56, 70],
    author: 'Cawito',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 19 },
    x: 12,
    y: 32,
    width: 40,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [-1, -1, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 110,
    name: 'Jamaican Flag',
    setId: [56],
    author: 'Cawito',
    description: '',
    dimensions: { x: 2, y: 24, width: 10, height: 28 },
    x: 2,
    y: 24,
    width: 10,
    height: 28,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [-1, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 111,
    name: 'Hazmat Hood',
    setId: [57, 58],
    author: 'ShadowLord Obeesus',
    description: '',
    dimensions: { x: 15, y: 6, width: 34, height: 34 },
    x: 15,
    y: 6,
    width: 34,
    height: 34,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [1, -1, 2, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 112,
    name: 'Hazmat Suit',
    setId: [57, 58],
    author: 'ShadowLord Obeesus',
    description: '',
    dimensions: { x: 7, y: 31, width: 50, height: 24 },
    x: 7,
    y: 31,
    width: 50,
    height: 24,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [2, -1, 1, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 113,
    name: 'Uranium Rod',
    setId: [58],
    author: 'ShadowLord Obeesus',
    description: '',
    dimensions: { x: 8, y: 26, width: 3, height: 19 },
    x: 8,
    y: 26,
    width: 3,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: '5',
    traitModifiers: [6, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
    FIELD23: '',
    FIELD24: 'Total NRG',
    FIELD25: 'Total AGG',
    FIELD26: 'Total SPK',
    FIELD27: 'Total BRN'
  },
  {
    svgId: 114,
    name: 'Red Hawaiian Shirt',
    setId: [60, 67],
    author: 'Rod',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 18 },
    x: 12,
    y: 32,
    width: 40,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [-3, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0,
    FIELD23: 'Aggregate Sum:',
    FIELD24: '#REF!',
    FIELD25: '#REF!',
    FIELD26: '#REF!',
    FIELD27: '#REF!'
  },
  {
    svgId: 115,
    name: 'Blue Hawaiian Shirt',
    setId: [59, 64],
    author: 'Rod',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 18 },
    x: 12,
    y: 32,
    width: 40,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [-2, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 116,
    name: 'Coconut',
    setId: [59, 60],
    author: 'SnottySnake',
    description: '',
    dimensions: { x: 1, y: 27, width: 12, height: 18 },
    x: 1,
    y: 27,
    width: 12,
    height: 18,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [0, 0, -3, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 117,
    name: 'Cool shades',
    setId: [59, 60, 67],
    author: 'Xibot',
    description: '',
    dimensions: { x: 15, y: 22, width: 34, height: 8 },
    x: 15,
    y: 22,
    width: 34,
    height: 8,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '1000',
    traitModifiers: [0, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 118,
    name: 'Water Jug',
    setId: [47, 49],
    author: 'Qurka',
    description: '',
    dimensions: { x: 1, y: 21, width: 16, height: 26 },
    x: 1,
    y: 21,
    width: 16,
    height: 26,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [2, 0, 0, 2, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 119,
    name: 'Baby Bottle',
    setId: [66],
    author: 'Cawito',
    description: '',
    dimensions: { x: 6, y: 27, width: 7, height: 17 },
    x: 6,
    y: 27,
    width: 7,
    height: 17,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [0, -1, -3, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 120,
    name: 'Martini',
    setId: [67],
    author: 'Cawito',
    description: '',
    dimensions: { x: 1, y: 25, width: 14, height: 19 },
    x: 1,
    y: 25,
    width: 14,
    height: 19,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [-1, 0, 0, -3, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 121,
    name: 'Wine',
    setId: [],
    author: 'Cawito',
    description: '',
    dimensions: { x: 6, y: 23, width: 7, height: 22 },
    x: 51,
    y: 23,
    width: 7,
    height: 22,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: '250',
    traitModifiers: [0, 0, 0, -3, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 122,
    name: 'Milkshake',
    setId: [],
    author: 'SnottySnake',
    description: '',
    dimensions: { x: 2, y: 21, width: 12, height: 29 },
    x: 2,
    y: 21,
    width: 12,
    height: 29,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, 0, -5, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 123,
    name: 'Apple Juice',
    setId: [57],
    author: 'Xibot',
    description: '',
    dimensions: { x: 3, y: 30, width: 8, height: 14 },
    x: 3,
    y: 30,
    width: 8,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: '500',
    traitModifiers: [0, 0, -2, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 124,
    name: 'Beer Helmet',
    setId: [70],
    author: 'Vanilladelphia',
    description: '',
    dimensions: { x: 5, y: 2, width: 54, height: 29 },
    x: 5,
    y: 2,
    width: 54,
    height: 29,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: '50',
    traitModifiers: [0, 0, 0, -5, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 125,
    name: 'Track Suit',
    setId: [48, 49],
    author: 'KA WAI LEONG',
    description: '',
    dimensions: { x: 11, y: 31, width: 42, height: 24 },
    x: 11,
    y: 31,
    width: 42,
    height: 24,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: '125',
    traitModifiers: [2, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 126,
    name: 'Kinship Potion',
    setId: [],
    author: 'SnottySnake',
    description: '+2 to Kinship',
    dimensions: { x: 27, y: 37, width: 10, height: 14 },
    x: 27,
    y: 37,
    width: 10,
    height: 14,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: '500',
    traitModifiers: [0, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: '',
    category: 2,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 2
  },
  {
    svgId: 127,
    name: 'Greater Kinship Potion',
    setId: [],
    author: 'SnottySnake',
    description: '+10 to Kinship',
    dimensions: '',
    x: null,
    y: null,
    width: null,
    height: null,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 20,
    maxQuantity: '250',
    traitModifiers: [0, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: '',
    category: 2,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 10
  },
  {
    svgId: 128,
    name: 'XP Potion',
    setId: [],
    author: 'Xibot',
    description: '+20 to XP',
    dimensions: { x: 3, y: 26, width: 10, height: 18 },
    x: 3,
    y: 26,
    width: 10,
    height: 18,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 20,
    maxQuantity: '500',
    traitModifiers: [0, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: '',
    category: 2,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 20,
    kinshipBonus: 0
  },
  {
    svgId: 129,
    name: 'Greater XP Potion',
    setId: [],
    author: 'Xibot',
    description: '+50 to XP',
    dimensions: '',
    x: null,
    y: null,
    width: null,
    height: null,
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 50,
    maxQuantity: '250',
    traitModifiers: [0, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: '',
    category: 2,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 50,
    kinshipBonus: 0
  }
]

function eightBitIntArrayToUint (array) {
  if (array.length === 0) {
    return ethers.BigNumber.from(0)
  }
  const uint = []
  for (const num of array) {
    if (num > 127) {
      throw (Error('Value beyond signed 8 int '))
    }
    const value = ethers.BigNumber.from(num).toTwos(8)
    uint.unshift(value.toHexString().slice(2))
  }
  return ethers.BigNumber.from('0x' + uint.join(''))
}

function boolsArrayToUint16 (bools) {
  const uint = []
  for (const b of bools) {
    if (b) {
      uint.push('1')
    } else {
      uint.push('0')
    }
  }
  // console.log(bools)
  // console.log(uint.join(''))
  // console.log(uint.join('').padStart(16, '0'))
  // console.log('-------------')
  return parseInt(uint.join('').padStart(16, '0'), 2)
}

function dimensions ({ x, y, width, height }) {
  const result = []
  for (const v of [x, y, width, height]) {
    result.unshift(v.toString(16).padStart(2, '0'))
  }
  // console.log('dimensions:')
  // console.log(ethers.BigNumber.from('0x' + result.join('')))
  return ethers.BigNumber.from('0x' + result.join(''))
}

// const WEARABLE_SLOT_BODY = 0
// const WEARABLE_SLOT_FACE = 1
// const WEARABLE_SLOT_EYES = 2
// const WEARABLE_SLOT_HEAD = 3
// const WEARABLE_SLOT_HAND_LEFT = 4
// const WEARABLE_SLOT_HAND_RIGHT = 5
// const WEARABLE_SLOT_PET = 6
// const WEARABLE_SLOT_BG = 7

// function stringToSlotPositions(str) {
//   if (str.length === 0) {
//     return 0
//   }
//   //Slot 0 Body
//   else if (str === 'body') return boolsArrayToUint16([true])

//   //Slot 1 Face
//   else if (str === 'face') return boolsArrayToUint16([true, false])

//   //Slot 2 Eyes
//   else if (str === 'eyes') return boolsArrayToUint16([true, false, false])

//   //Slot 3 Head
//   else if (str === 'head') return boolsArrayToUint16([true, false, false, false])

//   //Slot 4/5 Either hand
//   else if (str === 'hands') return boolsArrayToUint16([true, true, false, false, false, false])

//   //Slot 4 Left hand
//   else if (str === 'handLeft') return boolsArrayToUint16([true, false, false, false, false])

//   //Slot 5 Right Hand
//   else if (str === 'handRight') return boolsArrayToUint16([true, false, false, false, false, false])

//   //Slot 6 Pet
//   else if (str === 'pet') return boolsArrayToUint16([true, false, false, false, false, false, false])

//   //Slot 7 Background
//   else if (str === 'background') return boolsArrayToUint16([true, false, false, false, false, false, false, false])

//   else {
//     throw (Error('Wrong slot string: ' + str))
//   }
// }

function stringToSlotPositions (str) {
  if (str.length === 0) {
    return [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
  }
  // Slot 0 Body
  else if (str === 'body') return [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 1 Face
  else if (str === 'face') return [false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 2 Eyes
  else if (str === 'eyes') return [false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 3 Head
  else if (str === 'head') return [false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 4/5 Either hand
  else if (str === 'hands') return [false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false]

  // Slot 4 Left hand
  else if (str === 'handLeft') return [false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 5 Right Hand
  else if (str === 'handRight') return [false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false]

  // Slot 6 Pet
  else if (str === 'pet') return [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false]

  // Slot 7 Background
  else if (str === 'background') return [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false]

  else {
    throw (Error('Wrong slot string: ' + str))
  }
}

function calculateRarityScoreModifier (maxQuantity) {
  if (maxQuantity >= 1000) return 1
  if (maxQuantity >= 500) return 2
  if (maxQuantity >= 250) return 5
  if (maxQuantity >= 100) return 10
  if (maxQuantity >= 10) return 20
  if (maxQuantity >= 1) return 50
  return 0
}

function getItemTypes () {
  const result = []
  for (const itemType of itemTypes) {
    itemType.ghstPrice = ethers.utils.parseEther(itemType.ghstPrice.toString())
    itemType.traitModifiers = itemType.traitModifiers
    itemType.slotPositions = stringToSlotPositions(itemType.slotPositions)
    if (itemType.dimensions === '' || itemType.dimensions === 0) {
      itemType.dimensions = { x: 0, y: 0, width: 0, height: 0 }
    } else {
      itemType.dimensions = itemType.dimensions
    }

    itemType.rarityScoreModifier = calculateRarityScoreModifier(itemType.maxQuantity)
    if (!Array.isArray(itemType.allowedCollaterals)) {
      throw Error('Is not array.')
    }
    result.push(itemType)
  }
  return result
}

exports.itemTypes = getItemTypes()
