/* global ethers hre */
/* eslint-disable  prefer-const */

//const { LedgerSigner } = require('@ethersproject/hardware-wallets')

const itemTypes = [
  {
    svgId: 130,
    name: 'Fireball',
    setId: [73, 74],
    author: 'xibot',
    description: '',
    dimensions: { x: 51, y: 31, width: 10, height: 12 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [0, 1, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 131,
    name: 'Dragon Horns',
    setId: [73, 86],
    author: 'xibot',
    description: '',
    dimensions: { x: 19, y: 3, width: 26, height: 15 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, 1, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 132,
    name: 'Dragon Wings',
    setId: [73, 74, 86],
    author: 'xibot',
    description: '',
    dimensions: { x: 2, y: 19, width: 60, height: 31 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, 2, 1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 133,
    name: 'Pointy Horns',
    setId: [74],
    author: 'xibot',
    description: '',
    dimensions: { x: 19, y: 4, width: 26, height: 14 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [0, 2, 2, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 134,
    name: 'L2 Sign',
    setId: [72],
    author: 'xibot',
    description: '',
    dimensions: { x: 50, y: 24, width: 13, height: 23 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [0, 0, 0, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 135,
    name: 'Polygon Shirt',
    setId: [72],
    author: 'xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 20 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, 0, 0, 2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 136,
    name: 'Polygon Cap',
    setId: [72],
    author: 'xibot',
    description: '',
    dimensions: { x: 7, y: 4, width: 42, height: 17 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, -1, 0, 2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 137,
    name: 'Vote Sign',
    setId: [71],
    author: 'xibot',
    description: '',
    dimensions: { x: 48, y: 24, width: 17, height: 23 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [0, -1, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 138,
    name: 'Snapshot Shirt',
    setId: [71],
    author: 'xibot',
    description: '',
    dimensions: { x: 12, y: 33, width: 40, height: 20 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, -2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 139,
    name: 'Snapshot Cap',
    setId: [71],
    author: 'xibot',
    description: '',
    dimensions: { x: 7, y: 4, width: 42, height: 17 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, -3, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 140,
    name: 'Elf Ears',
    setId: [75, 76, 77, 78],
    author: 'xibot',
    description: '',
    dimensions: { x: 9, y: 18, width: 46, height: 12 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [0, 0, -1, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'face',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 141,
    name: 'Gemstone Ring',
    setId: [75, 76, 77, 78],
    author: 'xibot',
    description: '',
    dimensions: { x: 5, y: 29, width: 8, height: 14 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [0, 0, -1, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 142,
    name: 'Princess Tiara',
    setId: [75, 76],
    author: 'xibot',
    description: '',
    dimensions: { x: 15, y: 8, width: 34, height: 10 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [0, 0, -2, 1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 143,
    name: 'Gold Necklace',
    setId: [76, 77, 78],
    author: 'xibot',
    description: '',
    dimensions: { x: 15, y: 34, width: 34, height: 12 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [2, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 144,
    name: 'Princess Hair',
    setId: [77],
    author: 'xibot',
    description: '',
    dimensions: { x: 15, y: 6, width: 34, height: 45 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: 50,
    traitModifiers: [0, 0, -3, 2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 145,
    name: 'Godli Locks',
    setId: [78],
    author: 'xibot',
    description: '',
    dimensions: { x: 15, y: 6, width: 34, height: 45 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: 5,
    traitModifiers: [0, 0, -4, 2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 146,
    name: 'Imperial Moustache',
    setId: [79, 80, 81, 82, 85],
    author: 'xibot',
    description: '',
    dimensions: { x: 19, y: 32, width: 26, height: 7 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [-1, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'face',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 147,
    name: 'Tiny Crown',
    setId: [79, 80],
    author: 'xibot',
    description: '',
    dimensions: { x: 26, y: 4, width: 12, height: 6 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [-1, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 148,
    name: 'Royal Scepter',
    setId: [79, 80, 81, 82],
    author: 'xibot',
    description: '',
    dimensions: { x: 53, y: 28, width: 6, height: 21 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [-2, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 149,
    name: 'Royal Crown',
    setId: [81, 82],
    author: 'xibot',
    description: '',
    dimensions: { x: 15, y: 6, width: 34, height: 12 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [-2, 0, 0, -2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 150,
    name: 'Royal Robes',
    setId: [80, 81, 812],
    author: 'xibot',
    description: '',
    dimensions: { x: 10, y: 30, width: 44, height: 25 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: 50,
    traitModifiers: [-3, 0, 0, -2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 151,
    name: 'Common Rofl',
    setId: [],
    author: 'xibot',
    description: '',
    dimensions: { x: 42, y: 43, width: 20, height: 18 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 5,
    maxQuantity: 1000,
    traitModifiers: [0, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'pet',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 152,
    name: 'Uncommon Rofl',
    setId: [],
    author: 'xibot',
    description: '',
    dimensions: { x: 42, y: 43, width: 20, height: 18 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [-1, 0, 0, -1, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'pet',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 153,
    name: 'Rare Rofl',
    setId: [],
    author: 'xibot',
    description: '',
    dimensions: { x: 42, y: 43, width: 20, height: 18 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [-1, 0, 0, -2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'pet',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 154,
    name: 'Legendary Rofl',
    setId: [],
    author: 'xibot',
    description: '',
    dimensions: { x: 42, y: 43, width: 20, height: 18 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [-2, 0, 0, -2, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'pet',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 155,
    name: 'Mythical Rofl',
    setId: [],
    author: 'xibot',
    description: '',
    dimensions: { x: 42, y: 38, width: 20, height: 23 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: 50,
    traitModifiers: [-2, 0, 0, -3, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'pet',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 156,
    name: 'Godlike Rofl',
    setId: [82],
    author: 'xibot',
    description: '',
    dimensions: { x: 35, y: 38, width: 34, height: 23 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: 5,
    traitModifiers: [-3, 0, 0, -3, 0, 0],
    canPurchaseWithGhst: false,
    slotPositions: 'pet',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 157,
    name: 'Lil Pump Goatee',
    setId: [83, 84],
    author: 'xibot',
    description: '',
    dimensions: { x: 29, y: 37, width: 6, height: 3 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10,
    maxQuantity: 500,
    traitModifiers: [1, 1, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'face',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 158,
    name: 'Lil Pump Drank',
    setId: [83, 84],
    author: 'xibot',
    description: '',
    dimensions: { x: 4, y: 31, width: 8, height: 13 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 100,
    maxQuantity: 250,
    traitModifiers: [1, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'hands',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 159,
    name: 'Lil Pump Shades',
    setId: [83, 84],
    author: 'xibot',
    description: '',
    dimensions: { x: 15, y: 19, width: 34, height: 12 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 300,
    maxQuantity: 100,
    traitModifiers: [0, 3, 1, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'eyes',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 160,
    name: 'Lil Pump Threads',
    setId: [83, 84],
    author: 'xibot',
    description: '',
    dimensions: { x: 11, y: 33, width: 42, height: 22 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 2000,
    maxQuantity: 50,
    traitModifiers: [5, 0, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'body',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  },
  {
    svgId: 161,
    name: 'Lil Pump Dreads',
    setId: [83],
    author: 'xibot',
    description: '',
    dimensions: { x: 13, y: 6, width: 38, height: 27 },
    allowedCollaterals: [],
    minLevel: 1,
    ghstPrice: 10000,
    maxQuantity: 5,
    traitModifiers: [4, 2, 0, 0, 0, 0],
    canPurchaseWithGhst: true,
    slotPositions: 'head',
    category: 0,
    canBeTransferred: true,
    totalQuantity: 0,
    experienceBonus: 0,
    kinshipBonus: 0
  }
]

function stringToSlotPositions (str) {
  if (str.length === 0) return [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
  // Slot 0 Body
  else if (str === 'body') return [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 1 Face
  else if (str === 'face') return [false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 2 Eyes
  else if (str === 'eyes') return [false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 3 Head
  else if (str === 'head') return [false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 4/5 Either hand
  else if (str === 'hands') return [false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false]

  // Slot 4 Left hand
  else if (str === 'handLeft') return [false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false]

  // Slot 5 Right Hand
  else if (str === 'handRight') return [false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false]

  // Slot 6 Pet
  else if (str === 'pet') return [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false]

  // Slot 7 Background
  else if (str === 'background') return [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false]

  else {
    throw (Error('Wrong slot string: ' + str))
  }
}

function calculateRarityScoreModifier (maxQuantity) {
  if (maxQuantity >= 1000) return 1
  if (maxQuantity >= 500) return 2
  if (maxQuantity >= 250) return 5
  if (maxQuantity >= 100) return 10
  if (maxQuantity >= 10) return 20
  if (maxQuantity >= 1) return 50
  return 0
}

function getItemTypes () {
  const result = []
  for (const itemType of itemTypes) {
    itemType.ghstPrice = ethers.utils.parseEther(itemType.ghstPrice.toString())
    itemType.slotPositions = stringToSlotPositions(itemType.slotPositions)
    if (itemType.dimensions === '' || itemType.dimensions === 0) {
      itemType.dimensions = { x: 0, y: 0, width: 0, height: 0 }
    }
    itemType.rarityScoreModifier = calculateRarityScoreModifier(itemType.maxQuantity)
    if (!Array.isArray(itemType.allowedCollaterals)) {
      throw Error('Is not array.')
    }
    result.push(itemType)
  }
  return result
}

exports.itemTypes = getItemTypes()
