import { ItemTypeInputNew } from "../../../scripts/itemTypeHelpers";

export const itemTypes: ItemTypeInputNew[] = [
  {
    name: "CHAAMPION of Rarity Farming SZN2 (Rarity)", //0
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of rarity for Rarity Farming SZN 2. Aamazing! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 265,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN2 (Kinship)", //1
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of kinship for Rarity Farming SZN 2. Aamazing! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 266,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN2 (XP)", //2
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of XP for Rarity Farming SZN 2. Aamazing! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 267,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 RARITY 2nd Place", //3
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all gotchis in the rarity category for Rarity Farming SZN 2. Incredible! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 268,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 KINSHIP 2nd Place", //4
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all gotchis in the kinship category for Rarity Farming SZN 2. Incredible! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 269,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 XP 2nd Place", //5
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all gotchis in the XP category for Rarity Farming SZN 2. Incredible! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 270,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 RARITY 3rd Place", //6
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all gotchis in the rarity category for Rarity Farming SZN 2. Impressive! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 271,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 KINSHIP 3rd Place", //7
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all gotchis in the kinship category for Rarity Farming SZN 2. Impressive! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 272,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 XP 3rd Place", //8
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all gotchis in the XP category for Rarity Farming SZN 2. Impressive! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 273,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 Raanked", //9
    description:
      "This Aavegotchi achieved leaderboard ranking in at least one category during the second season of Rarity Farming. From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 274,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "common",
    maxQuantity: 11000,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 ROOKIE OF THE YEAR", //10
    description:
      "This Aavegotchi was the best performing of all Haunt 2 Aavegotchis during Rarity Farming Season 2. This includes the gotchi's Base Rartity Score and ranking on the Rookie Kinship and XP leaderboards. From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 275,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN2 (Rookie Kinship)", //11
    description:
      "Scored across all four rounds, this Aavegotchi delivered the best rookie kinship scores for Rarity Farming SZN 2! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 276,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN2 (Rookie XP)", //12
    description:
      "Scored across all four rounds, this Aavegotchi delivered the best rookie XP scores for Rarity Farming SZN 2! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 277,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 KINSHIP ROOKIE 2nd Place", //13
    description:
      "Scored across all four rounds, this Aavegotchi ranked 2nd overall for Rarity Farming SZN 2 rookie kinship scores! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 278,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 XP ROOKIE 2nd Place", //14
    description:
      "Scored across all four rounds, this Aavegotchi ranked 2nd overall for Rarity Farming SZN 2 rookie XP scores! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 279,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 KINSHIP ROOKIE 3rd Place", //15
    description:
      "Scored across all four rounds, this Aavegotchi ranked 3rd overall for Rarity Farming SZN 2 rookie kinship scores! From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 280,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 XP ROOKIE 3rd Place", //16
    description:
      "Scored across all four rounds, this Aavegotchi ranked 3rd overall for Rarity Farming SZN 2 rookie XP scores!   From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 281,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 RARITY Top 10", //17
    description:
      "This Aavegotchi achieved a rank in the top 10 of RARITY for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 282,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 10,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 KINSHIP Top 10", //18
    description:
      "This Aavegotchi achieved a rank in the top 10 of KINSHIP for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 283,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 10,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 XP Top 10", //19
    description:
      "This Aavegotchi achieved a rank in the top 10 of EXPERIENCE for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 284,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 10,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 RARITY Top 100", //20
    description:
      "This Aavegotchi achieved a rank in the top 100 of RARITY for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 285,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 KINSHIP Top 100", //21
    description:
      "This Aavegotchi achieved a rank in the top 100 of KINSHIP for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 286,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 XP Top 100", //22
    description:
      "This Aavegotchi achieved a rank in the top 100 of EXPERIENCE for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 287,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 XP ROOKIE Top 10", //23
    description:
      "This Aavegotchi achieved a rank in the top 10 on the ROOKIE XP leaderboard for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 288,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 10,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 KINSHIP ROOKIE Top 10", //24
    description:
      "This Aavegotchi achieved a rank in the top 10 of the ROOKIE KINSHIP leaderboard for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 289,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 10,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 XP ROOKIE Top 100", //25
    description:
      "This Aavegotchi achieved a rank in the top 100 on the ROOKIE XP leaderboard for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 290,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN2 KINSHIP ROOKIE Top 100", //26
    description:
      "This Aavegotchi achieved a rank in the top 100 of the ROOKIE KINSHIP leaderboard for Rarity Farming SZN 2.  From October 12 to Dec 7, 2021, the second season of Rarity Farming distributed a staggering 2 million GHST. The frenly competition featured three main leaderboards that any summoned Aavegotchi could participate in plus two additional Rookie Leaderboards for Haunt 2 Aavegotchis.",
    svgId: 291,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
];
