import { ItemTypeInputNew } from "../../../scripts/itemTypeHelpers";

export const itemTypes: ItemTypeInputNew[] = [
  {
    name: "CHAAMPION of Rarity Farming SZN4 (Rarity)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of RARITY for Rarity Farming SZN 4. FANTASTIC! From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 334,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN4 (Kinship)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of KINSHIP for Rarity Farming SZN 4. FANTASTIC! From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 335,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN4 (XP)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of XP for Rarity Farming SZN 4. FANTASTIC! From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 336,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 RARITY 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all RARITY for Rarity Farming SZN 4. Incredible! From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 337,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 KINSHIP 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all KINSHIP for Rarity Farming SZN 4. Incredible! From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 338,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 XP 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all XP for Rarity Farming SZN 4. Incredible! From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 5k to 7500 winning gotchis each round!",
    svgId: 339,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 RARITY 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all RARITY for Rarity Farming SZN 4. Impressive! From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 340,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 KINSHIP 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all KINSHIP for Rarity Farming SZN 4. Impressive! From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 341,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 XP 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all XP for Rarity Farming SZN 4. Impressive! From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 342,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 Raanked",
    description:
      "This Aavegotchi achieved leaderboard ranking in at least one category during the fourth season of Rarity Farming. From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 343,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "common",
    maxQuantity: 12809,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 RARITY Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of RARITY for Rarity Farming SZN 4. From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 344,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 7,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 KINSHIP Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of KINSHIP for Rarity Farming SZN 4. From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 345,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 7,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 XP Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of XP for Rarity Farming SZN 4. From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 346,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 7,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 RARITY Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of RARITY for Rarity Farming SZN 4. From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 347,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 KINSHIP Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of KINSHIP for Rarity Farming SZN 4. From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 348,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN4 XP Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of XP for Rarity Farming SZN 4. From July 28th to September 22nd, 2022, the fourth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 349,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
];
