import { ItemTypeInputNew } from "../../itemTypeHelpers";

export const itemTypes: ItemTypeInputNew[] = [
  {
    name: "CHAAMPION of Rarity Farming SZN6 (Rarity)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of RARITY for Rarity Farming SZN 6. FANTASTIC! From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 404,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN6 (Kinship)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of KINSHIP for Rarity Farming SZN 6. FANTASTIC! From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 405,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN6 (XP)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of XP for Rarity Farming SZN 6. FANTASTIC! From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 406,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 RARITY 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all RARITY for Rarity Farming SZN 6. Incredible! From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 407,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 KINSHIP 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all KINSHIP for Rarity Farming SZN 6. Incredible! From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 408,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 XP 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all XP for Rarity Farming SZN 6. Incredible! From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 5k to 7500 winning gotchis each round!",
    svgId: 409,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 RARITY 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all RARITY for Rarity Farming SZN 6. Impressive! From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 410,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 KINSHIP 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all KINSHIP for Rarity Farming SZN 6. Impressive! From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 411,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 XP 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all XP for Rarity Farming SZN 6. Impressive! From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 412,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 Raanked",
    description:
      "This Aavegotchi achieved leaderboard ranking in at least one category during the fifth season of Rarity Farming. From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 413,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "common",
    maxQuantity: 12846,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 RARITY Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of RARITY for Rarity Farming SZN 6. From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 414,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 7,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 KINSHIP Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of KINSHIP for Rarity Farming SZN 6. From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 415,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 7,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 XP Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of XP for Rarity Farming SZN 6. From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 416,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 7,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 RARITY Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of RARITY for Rarity Farming SZN 6. From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 417,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 KINSHIP Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of KINSHIP for Rarity Farming SZN 6. From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 418,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN6 XP Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of XP for Rarity Farming SZN 6. From June 21st to August 10th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 419,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
];
