import { ItemTypeInputNew } from "../../itemTypeHelpers";

export const itemTypes: ItemTypeInputNew[] = [
  {
    name: "CHAAMPION of Rarity Farming SZN5 (Rarity)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of RARITY for Rarity Farming SZN 5. FANTASTIC! From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 388,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN5 (Kinship)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of KINSHIP for Rarity Farming SZN 5. FANTASTIC! From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 389,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN5 (XP)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of XP for Rarity Farming SZN 5. FANTASTIC! From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 390,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 RARITY 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all RARITY for Rarity Farming SZN 5. Incredible! From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 391,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 KINSHIP 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all KINSHIP for Rarity Farming SZN 5. Incredible! From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 392,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 XP 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all XP for Rarity Farming SZN 5. Incredible! From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 5k to 7500 winning gotchis each round!",
    svgId: 393,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 RARITY 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all RARITY for Rarity Farming SZN 5. Impressive! From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 394,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 KINSHIP 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all KINSHIP for Rarity Farming SZN 5. Impressive! From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 395,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 XP 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all XP for Rarity Farming SZN 5. Impressive! From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 396,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 Raanked",
    description:
      "This Aavegotchi achieved leaderboard ranking in at least one category during the fifth season of Rarity Farming. From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 397,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "common",
    maxQuantity: 12809,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 RARITY Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of RARITY for Rarity Farming SZN 5. From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 398,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 7,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 KINSHIP Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of KINSHIP for Rarity Farming SZN 5. From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 399,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 7,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 XP Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of XP for Rarity Farming SZN 5. From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 400,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 7,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 RARITY Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of RARITY for Rarity Farming SZN 5. From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 401,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 KINSHIP Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of KINSHIP for Rarity Farming SZN 5. From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 402,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN5 XP Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of XP for Rarity Farming SZN 5. From January 31st to March 28th, 2023, the fifth season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards has 7500 winning gotchis each round!",
    svgId: 403,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
];
