import { ItemTypeInputNew } from "../../../scripts/itemTypeHelpers";

export const itemTypes: ItemTypeInputNew[] = [
  {
    name: "CHAAMPION of Rarity Farming SZN3 (Rarity)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of RARITY for Rarity Farming SZN 3. Aamazing! From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 316,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN3 (Kinship)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of KINSHIP for Rarity Farming SZN 3. Aamazing! From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 317,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "CHAAMPION of Rarity Farming SZN3 (XP)",
    description:
      "Scored across all four rounds, this Aavegotchi is the ultimate chaampion of XP for Rarity Farming SZN 3. Aamazing! From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 318,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 RARITY 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all RARITY for Rarity Farming SZN 3. Incredible! From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 319,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 KINSHIP 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all KINSHIP for Rarity Farming SZN 3. Incredible! From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 320,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 XP 2nd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 2nd highest ranked of all XP for Rarity Farming SZN 3. Incredible! From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 321,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 RARITY 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all RARITY for Rarity Farming SZN 3. Impressive! From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 322,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 KINSHIP 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all KINSHIP for Rarity Farming SZN 3. Impressive! From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 323,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 XP 3rd Place",
    description:
      "Scored across all four rounds, this Aavegotchi is the 3rd highest ranked of all XP for Rarity Farming SZN 3. Impressive! From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 324,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "godlike",
    maxQuantity: 1,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 Raanked",
    description:
      "This Aavegotchi achieved leaderboard ranking in at least one category during the third season of Rarity Farming. From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 325,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "common",
    maxQuantity: 12565,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 RARITY Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of RARITY for Rarity Farming SZN 3. From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 326,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 10,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 KINSHIP Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of KINSHIP for Rarity Farming SZN 3. From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 327,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 10,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 XP Top 10",
    description:
      "This Aavegotchi achieved a rank in the top 10 of XP for Rarity Farming SZN 3. From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 328,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "mythical",
    maxQuantity: 10,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 RARITY Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of RARITY for Rarity Farming SZN 3. From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 329,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 KINSHIP Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of KINSHIP for Rarity Farming SZN 3. From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 330,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
  {
    name: "Rarity Farming SZN3 XP Top 100",
    description:
      "This Aavegotchi achieved a rank in the top 100 of XP for Rarity Farming SZN 3. From February 24 to April 22, 2022, the third season of Rarity Farming distributed 1.5 million GHST over 8 weeks. Each of the 3 leaderboards increased from 5k to 7500 winning gotchis each round!",
    svgId: 331,
    minLevel: 0,
    canBeTransferred: false,
    rarityLevel: "legendary",
    maxQuantity: 90,
    totalQuantity: 0,
    setId: [],
    author: "xibot",
    dimensions: { x: 0, y: 0, width: 0, height: 0 },
    allowedCollaterals: [],
    ghstPrice: 0,
    traitModifiers: [0, 0, 0, 0, 0, 0],
    slotPositions: "none",
    category: 1,
    experienceBonus: 0,
    kinshipBonus: 0,
    canPurchaseWithGhst: false,
  },
];
